### ISSUE TITLE
Memory access fault with gpt-oss:20b

### ISSUE THREAD

**Issue by Expro** [ollama/ollama#11697]
### What is the issue?

Prompting gpt-oss:20b on 0.11.1 results in error:

Memory access fault by GPU node-1 (Agent handle: 0x7f3b0c66f890) on address 0x7f360519e000. Reason: Page not present or supervisor privilege.

### Relevant log output

```shell
time=2025-08-05T20:35:49.174Z level=INFO source=ggml.go:367 msg="offloading 24 repeating layers to GPU"
time=2025-08-05T20:35:49.174Z level=INFO source=ggml.go:373 msg="offloading output layer to GPU"
time=2025-08-05T20:35:49.174Z level=INFO source=ggml.go:378 msg="offloaded 25/25 layers to GPU"
time=2025-08-05T20:35:49.174Z level=INFO source=ggml.go:381 msg="model weights" buffer=ROCm0 size="11.7 GiB"
time=2025-08-05T20:35:49.174Z level=INFO source=ggml.go:381 msg="model weights" buffer=CPU size="1.1 GiB"
time=2025-08-05T20:35:49.188Z level=INFO source=ggml.go:672 msg="compute graph" backend=ROCm0 buffer_type=ROCm0 size="2.1 GiB"
time=2025-08-05T20:35:49.188Z level=INFO source=ggml.go:672 msg="compute graph" backend=CPU buffer_type=CPU size="5.6 MiB"
time=2025-08-05T20:36:11.960Z level=INFO source=server.go:637 msg="llama runner started in 25.11 seconds"
Memory access fault by GPU node-1 (Agent handle: 0x7fedb466f890) on address 0x7fec0d423000. Reason: Page not present or supervisor privilege.
time=2025-08-05T20:36:34.898Z level=ERROR source=server.go:807 msg="post predict" error="Post \"http://127.0.0.1:33281/completion\": EOF"
[GIN] 2025/08/05 - 20:36:34 | 200 | 48.888797725s |      10.244.2.0 | POST     "/api/chat"
time=2025-08-05T20:36:35.320Z level=WARN source=server.go:517 msg="llama runner process no longer running" sys=134 string="signal: aborted (core dumped)"
```

### OS

Docker

### GPU

AMD

### CPU

AMD

### Ollama version

0.11.1

**Comment by dtori** [comment]
Same
$ ollama run gpt-oss:20b
>>> Hello
Error: model runner has unexpectedly stopped, this may be due to resource limitations or an internal error, check ollama server logs for details

(ubuntu linux, rtx3090)

**Comment by ayylmaonade** [comment]
+1
Having the same issue here.
**I found a temporary workaround**: You have to disable flash attention. Just serve ollama like this; `OLLAMA_FLASH_ATTENTION=0 ollama serve** until they solve it. 7900 XTX, Arch Linux, Kernel 6.15.9.

**Comment by AlKhrulev** [comment]
+1 Same problem as @dtori on M4 Pro 48 Gb with Ollama 0.11.0 running as a brew service

**Comment by pdevine** [comment]
This should be fixed in `0.11.2`.

**Comment by AlKhrulev** [comment]
> This should be fixed in `0.11.2`.

yup, can confirm that it is working now. Thanks!
