### ISSUE TITLE
`ROCm error: invalid device function` on AMD RX 7900 XTX (gfx1100) after models were initially working

### ISSUE THREAD

**Issue by atomskz** [ollama/ollama#11975]
### **Environment**
*   **Ollama Version:** `0.11.5`
*   **Operating System:** `Windows 11` (native)
*   **GPU:** `AMD Radeon RX 7900 XTX (gfx1100)` with `24 GB VRAM`
*   **System RAM:** `64 GB`
*   **Relevant `ollama run` command:** The issue occurs with any model, e.g., `ollama run qwen:4b`.

### **Issue Description**

After a fresh native Windows install of Ollama, two large models (`qwen3:30b` and `gpt-oss:20b`) loaded and ran successfully on the GPU. After a short period of testing, the models disappeared from the list (`ollama list` showed nothing). Subsequent attempts to pull and run any model now fail with the error: `"Error: model runner has unexpectedly stopped, this may be due to resource limitations or an internal error. Check Ollama server logs for details."`

The server logs show a critical `ROCm error: invalid device function` during the model inference step, specifically in the `ggml_cuda_mul_mat_q` function.

### **Additional Context**
*   The issue began **after** models were working correctly. The initial success suggests drivers and hardware are fundamentally compatible.
*   The problem persists across multiple reboots and a full uninstall/reinstall of Ollama (including deleting the `C:\Users\<user>\.ollama` directory).
*   The log message `"one or more GPUs detected that are unable to accurately report free memory"` appears, but this was also present during the initial successful runs.
*   The integrated GPU (AMD Radeon(TM) Graphics, `gfx1036`) is correctly detected and skipped as unsupported. The discrete GPU (`gfx1100`) is the target.

### Relevant log output

```shell
time=2025-08-20T10:41:53.048+05:00 level=INFO source=routes.go:1318 msg="server config" env="map[CUDA_VISIBLE_DEVICES: GPU_DEVICE_ORDINAL: HIP_VISIBLE_DEVICES: HSA_OVERRIDE_GFX_VERSION: HTTPS_PROXY: HTTP_PROXY: NO_PROXY: OLLAMA_CONTEXT_LENGTH:4096 OLLAMA_DEBUG:INFO OLLAMA_FLASH_ATTENTION:false OLLAMA_GPU_OVERHEAD:0 OLLAMA_HOST:http://127.0.0.1:11434 OLLAMA_INTEL_GPU:false OLLAMA_KEEP_ALIVE:5m0s OLLAMA_KV_CACHE_TYPE: OLLAMA_LLM_LIBRARY: OLLAMA_LOAD_TIMEOUT:5m0s OLLAMA_MAX_LOADED_MODELS:0 OLLAMA_MAX_QUEUE:512 OLLAMA_MODELS:C:\\Users\\user\\.ollama\\models OLLAMA_MULTIUSER_CACHE:false OLLAMA_NEW_ENGINE:false OLLAMA_NEW_ESTIMATES:false OLLAMA_NOHISTORY:false OLLAMA_NOPRUNE:false OLLAMA_NUM_PARALLEL:1 OLLAMA_ORIGINS:[http://localhost https://localhost http://localhost:* https://localhost:* http://127.0.0.1 https://127.0.0.1 http://127.0.0.1:* https://127.0.0.1:* http://0.0.0.0 https://0.0.0.0 http://0.0.0.0:* https://0.0.0.0:* app://* file://* tauri://* vscode-webview://* vscode-file://*] OLLAMA_SCHED_SPREAD:false ROCR_VISIBLE_DEVICES:]"
time=2025-08-20T10:41:53.055+05:00 level=INFO source=images.go:477 msg="total blobs: 12"
time=2025-08-20T10:41:53.056+05:00 level=INFO source=images.go:484 msg="total unused blobs removed: 0"
time=2025-08-20T10:41:53.056+05:00 level=INFO source=routes.go:1371 msg="Listening on 127.0.0.1:11434 (version 0.11.5)"
time=2025-08-20T10:41:53.056+05:00 level=INFO source=gpu.go:217 msg="looking for compatible GPUs"
time=2025-08-20T10:41:53.056+05:00 level=INFO source=gpu_windows.go:167 msg=packages count=1
time=2025-08-20T10:41:53.056+05:00 level=INFO source=gpu_windows.go:214 msg="" package=0 cores=6 efficiency=0 threads=12
time=2025-08-20T10:41:53.397+05:00 level=INFO source=amd_windows.go:127 msg="unsupported Radeon iGPU detected skipping" id=0 total="24.2 GiB"
time=2025-08-20T10:41:53.698+05:00 level=INFO source=types.go:130 msg="inference compute" id=1 library=rocm variant="" compute=gfx1100 driver=6.4 name="AMD Radeon RX 7900 XTX" total="24.0 GiB" available="23.8 GiB"
[GIN] 2025/08/20 - 10:41:53 | 200 |       511.6µs |       127.0.0.1 | GET      "/"
[GIN] 2025/08/20 - 10:41:53 | 200 |      1.0433ms |       127.0.0.1 | GET      "/api/tags"
[GIN] 2025/08/20 - 10:41:53 | 200 |     31.9209ms |       127.0.0.1 | POST     "/api/show"
[GIN] 2025/08/20 - 10:41:59 | 200 |      1.0373ms |       127.0.0.1 | GET      "/api/tags"
[GIN] 2025/08/20 - 10:41:59 | 200 |     33.8056ms |       127.0.0.1 | POST     "/api/show"
[GIN] 2025/08/20 - 10:41:59 | 200 |     30.1593ms |       127.0.0.1 | POST     "/api/show"
time=2025-08-20T10:42:00.261+05:00 level=INFO source=sched.go:192 msg="one or more GPUs detected that are unable to accurately report free memory - disabling default concurrency"
llama_model_loader: loaded meta data with 33 key-value pairs and 398 tensors from C:\Users\user\.ollama\models\blobs\sha256-3e4cb14174460404e7a233e531675303b2fbf7749c02f91864fe311ab6344e4f (version GGUF V3 (latest))
llama_model_loader: Dumping metadata keys/values. Note: KV overrides do not apply in this output.
llama_model_loader: - kv   0:                       general.architecture str              = qwen3
llama_model_loader: - kv   1:                           general.basename str              = Qwen3
llama_model_loader: - kv   2:                          general.file_type u32              = 15
llama_model_loader: - kv   3:                           general.finetune str              = Thinking
llama_model_loader: - kv   4:                            general.license str              = apache-2.0
llama_model_loader: - kv   5:                       general.license.link str              = https://huggingface.co/Qwen/Qwen3-4B-...
llama_model_loader: - kv   6:                               general.name str              = Qwen3 4B Thinking 2507
llama_model_loader: - kv   7:                    general.parameter_count u64              = 4022468096
llama_model_loader: - kv   8:               general.quantization_version u32              = 2
llama_model_loader: - kv   9:                         general.size_label str              = 4B
llama_model_loader: - kv  10:                               general.tags arr[str,1]       = ["text-generation"]
llama_model_loader: - kv  11:                               general.type str              = model
llama_model_loader: - kv  12:                            general.version str              = 2507
llama_model_loader: - kv  13:                 qwen3.attention.head_count u32              = 32
llama_model_loader: - kv  14:              qwen3.attention.head_count_kv u32              = 8
llama_model_loader: - kv  15:                 qwen3.attention.key_length u32              = 128
llama_model_loader: - kv  16:     qwen3.attention.layer_norm_rms_epsilon f32              = 0.000001
llama_model_loader: - kv  17:               qwen3.attention.value_length u32              = 128
llama_model_loader: - kv  18:                          qwen3.block_count u32              = 36
llama_model_loader: - kv  19:                       qwen3.context_length u32              = 262144
llama_model_loader: - kv  20:                     qwen3.embedding_length u32              = 2560
llama_model_loader: - kv  21:                  qwen3.feed_forward_length u32              = 9728
llama_model_loader: - kv  22:                       qwen3.rope.freq_base f32              = 5000000.000000
llama_model_loader: - kv  23:                    tokenizer.chat_template str              = {%- if tools %}\n    {{- '<|im_start|>...
llama_model_loader: - kv  24:               tokenizer.ggml.add_bos_token bool             = false
llama_model_loader: - kv  25:                tokenizer.ggml.bos_token_id u32              = 151643
llama_model_loader: - kv  26:                tokenizer.ggml.eos_token_id u32              = 151645
llama_model_loader: - kv  27:                      tokenizer.ggml.merges arr[str,151387]  = ["Ġ Ġ", "ĠĠ ĠĠ", "i n", "Ġ t",...
llama_model_loader: - kv  28:                       tokenizer.ggml.model str              = gpt2
llama_model_loader: - kv  29:            tokenizer.ggml.padding_token_id u32              = 151643
llama_model_loader: - kv  30:                         tokenizer.ggml.pre str              = qwen2
llama_model_loader: - kv  31:                  tokenizer.ggml.token_type arr[i32,151936]  = [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...
llama_model_loader: - kv  32:                      tokenizer.ggml.tokens arr[str,151936]  = ["!", "\"", "#", "$", "%", "&", "'", ...
llama_model_loader: - type  f32:  145 tensors
llama_model_loader: - type q4_K:  216 tensors
llama_model_loader: - type q6_K:   37 tensors
print_info: file format = GGUF V3 (latest)
print_info: file type   = Q4_K - Medium
print_info: file size   = 2.32 GiB (4.95 BPW) 
load: printing all EOG tokens:
load:   - 151643 ('<|endoftext|>')
load:   - 151645 ('<|im_end|>')
load:   - 151662 ('<|fim_pad|>')
load:   - 151663 ('<|repo_name|>')
load:   - 151664 ('<|file_sep|>')
load: special tokens cache size = 26
load: token to piece cache size = 0.9311 MB
print_info: arch             = qwen3
print_info: vocab_only       = 1
print_info: model type       = ?B
print_info: model params     = 4.02 B
print_info: general.name     = Qwen3 4B Thinking 2507
print_info: vocab type       = BPE
print_info: n_vocab          = 151936
print_info: n_merges         = 151387
print_info: BOS token        = 151643 '<|endoftext|>'
print_info: EOS token        = 151645 '<|im_end|>'
print_info: EOT token        = 151645 '<|im_end|>'
print_info: PAD token        = 151643 '<|endoftext|>'
print_info: LF token         = 198 'Ċ'
print_info: FIM PRE token    = 151659 '<|fim_prefix|>'
print_info: FIM SUF token    = 151661 '<|fim_suffix|>'
print_info: FIM MID token    = 151660 '<|fim_middle|>'
print_info: FIM PAD token    = 151662 '<|fim_pad|>'
print_info: FIM REP token    = 151663 '<|repo_name|>'
print_info: FIM SEP token    = 151664 '<|file_sep|>'
print_info: EOG token        = 151643 '<|endoftext|>'
print_info: EOG token        = 151645 '<|im_end|>'
print_info: EOG token        = 151662 '<|fim_pad|>'
print_info: EOG token        = 151663 '<|repo_name|>'
print_info: EOG token        = 151664 '<|file_sep|>'
print_info: max token length = 256
llama_model_load: vocab only - skipping tensors
time=2025-08-20T10:42:00.727+05:00 level=INFO source=server.go:383 msg="starting runner" cmd="C:\\Users\\user\\AppData\\Local\\Programs\\Ollama\\ollama.exe runner --model C:\\Users\\user\\.ollama\\models\\blobs\\sha256-3e4cb14174460404e7a233e531675303b2fbf7749c02f91864fe311ab6344e4f --port 59471"
time=2025-08-20T10:42:00.752+05:00 level=INFO source=runner.go:864 msg="starting go runner"
ggml_cuda_init: GGML_CUDA_FORCE_MMQ:    no
ggml_cuda_init: GGML_CUDA_FORCE_CUBLAS: no
ggml_cuda_init: found 2 ROCm devices:
  Device 0: AMD Radeon(TM) Graphics, gfx1036 (0x1036), VMM: no, Wave Size: 32, ID: 0
  Device 1: AMD Radeon RX 7900 XTX, gfx1100 (0x1100), VMM: no, Wave Size: 32, ID: 1
load_backend: loaded ROCm backend from C:\Users\user\AppData\Local\Programs\Ollama\lib\ollama\ggml-hip.dll
load_backend: loaded CPU backend from C:\Users\user\AppData\Local\Programs\Ollama\lib\ollama\ggml-cpu-icelake.dll
time=2025-08-20T10:42:00.807+05:00 level=INFO source=ggml.go:104 msg=system CPU.0.SSE3=1 CPU.0.SSSE3=1 CPU.0.AVX=1 CPU.0.AVX2=1 CPU.0.F16C=1 CPU.0.FMA=1 CPU.0.BMI2=1 CPU.0.AVX512=1 CPU.0.AVX512_VBMI=1 CPU.0.AVX512_VNNI=1 CPU.0.LLAMAFILE=1 CPU.1.LLAMAFILE=1 ROCm.0.NO_VMM=1 ROCm.0.NO_PEER_COPY=1 ROCm.0.PEER_MAX_BATCH_SIZE=128 ROCm.1.NO_VMM=1 ROCm.1.NO_PEER_COPY=1 ROCm.1.PEER_MAX_BATCH_SIZE=128 compiler=cgo(clang)
time=2025-08-20T10:42:00.808+05:00 level=INFO source=runner.go:900 msg="Server listening on 127.0.0.1:59471"
time=2025-08-20T10:42:01.049+05:00 level=INFO source=server.go:488 msg="system memory" total="63.2 GiB" free="52.8 GiB" free_swap="53.1 GiB"
time=2025-08-20T10:42:01.050+05:00 level=INFO source=memory.go:36 msg="new model will fit in available VRAM across minimum required GPUs, loading" model=C:\Users\user\.ollama\models\blobs\sha256-3e4cb14174460404e7a233e531675303b2fbf7749c02f91864fe311ab6344e4f library=rocm parallel=1 required="3.8 GiB" gpus=1
time=2025-08-20T10:42:01.050+05:00 level=INFO source=server.go:531 msg=offload library=rocm layers.requested=-1 layers.model=37 layers.offload=37 layers.split=[37] memory.available="[23.7 GiB]" memory.gpu_overhead="0 B" memory.required.full="3.8 GiB" memory.required.partial="3.8 GiB" memory.required.kv="576.0 MiB" memory.required.allocations="[3.8 GiB]" memory.weights.total="2.3 GiB" memory.weights.repeating="2.0 GiB" memory.weights.nonrepeating="304.3 MiB" memory.graph.full="384.0 MiB" memory.graph.partial="384.0 MiB"
time=2025-08-20T10:42:01.051+05:00 level=INFO source=runner.go:799 msg=load request="{Operation:commit LoraPath:[] Parallel:1 BatchSize:512 FlashAttention:false KvSize:4096 KvCacheType: NumThreads:6 GPULayers:37[ID:1 Layers:37(0..36)] MultiUserCache:false ProjectorPath: MainGPU:0 UseMmap:true}"
llama_model_load_from_file_impl: using device ROCm0 (AMD Radeon(TM) Graphics) - 24634 MiB free
llama_model_load_from_file_impl: using device ROCm1 (AMD Radeon RX 7900 XTX) - 24410 MiB free
time=2025-08-20T10:42:01.655+05:00 level=INFO source=server.go:1234 msg="waiting for llama runner to start responding"
time=2025-08-20T10:42:01.656+05:00 level=INFO source=server.go:1268 msg="waiting for server to become available" status="llm server loading model"
llama_model_loader: loaded meta data with 33 key-value pairs and 398 tensors from C:\Users\user\.ollama\models\blobs\sha256-3e4cb14174460404e7a233e531675303b2fbf7749c02f91864fe311ab6344e4f (version GGUF V3 (latest))
llama_model_loader: Dumping metadata keys/values. Note: KV overrides do not apply in this output.
llama_model_loader: - kv   0:                       general.architecture str              = qwen3
llama_model_loader: - kv   1:                           general.basename str              = Qwen3
llama_model_loader: - kv   2:                          general.file_type u32              = 15
llama_model_loader: - kv   3:                           general.finetune str              = Thinking
llama_model_loader: - kv   4:                            general.license str              = apache-2.0
llama_model_loader: - kv   5:                       general.license.link str              = https://huggingface.co/Qwen/Qwen3-4B-...
llama_model_loader: - kv   6:                               general.name str              = Qwen3 4B Thinking 2507
llama_model_loader: - kv   7:                    general.parameter_count u64              = 4022468096
llama_model_loader: - kv   8:               general.quantization_version u32              = 2
llama_model_loader: - kv   9:                         general.size_label str              = 4B
llama_model_loader: - kv  10:                               general.tags arr[str,1]       = ["text-generation"]
llama_model_loader: - kv  11:                               general.type str              = model
llama_model_loader: - kv  12:                            general.version str              = 2507
llama_model_loader: - kv  13:                 qwen3.attention.head_count u32              = 32
llama_model_loader: - kv  14:              qwen3.attention.head_count_kv u32              = 8
llama_model_loader: - kv  15:                 qwen3.attention.key_length u32              = 128
llama_model_loader: - kv  16:     qwen3.attention.layer_norm_rms_epsilon f32              = 0.000001
llama_model_loader: - kv  17:               qwen3.attention.value_length u32              = 128
llama_model_loader: - kv  18:                          qwen3.block_count u32              = 36
llama_model_loader: - kv  19:                       qwen3.context_length u32              = 262144
llama_model_loader: - kv  20:                     qwen3.embedding_length u32              = 2560
llama_model_loader: - kv  21:                  qwen3.feed_forward_length u32              = 9728
llama_model_loader: - kv  22:                       qwen3.rope.freq_base f32              = 5000000.000000
llama_model_loader: - kv  23:                    tokenizer.chat_template str              = {%- if tools %}\n    {{- '<|im_start|>...
llama_model_loader: - kv  24:               tokenizer.ggml.add_bos_token bool             = false
llama_model_loader: - kv  25:                tokenizer.ggml.bos_token_id u32              = 151643
llama_model_loader: - kv  26:                tokenizer.ggml.eos_token_id u32              = 151645
llama_model_loader: - kv  27:                      tokenizer.ggml.merges arr[str,151387]  = ["Ġ Ġ", "ĠĠ ĠĠ", "i n", "Ġ t",...
llama_model_loader: - kv  28:                       tokenizer.ggml.model str              = gpt2
llama_model_loader: - kv  29:            tokenizer.ggml.padding_token_id u32              = 151643
llama_model_loader: - kv  30:                         tokenizer.ggml.pre str              = qwen2
llama_model_loader: - kv  31:                  tokenizer.ggml.token_type arr[i32,151936]  = [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...
llama_model_loader: - kv  32:                      tokenizer.ggml.tokens arr[str,151936]  = ["!", "\"", "#", "$", "%", "&", "'", ...
llama_model_loader: - type  f32:  145 tensors
llama_model_loader: - type q4_K:  216 tensors
llama_model_loader: - type q6_K:   37 tensors
print_info: file format = GGUF V3 (latest)
print_info: file type   = Q4_K - Medium
print_info: file size   = 2.32 GiB (4.95 BPW) 
load: printing all EOG tokens:
load:   - 151643 ('<|endoftext|>')
load:   - 151645 ('<|im_end|>')
load:   - 151662 ('<|fim_pad|>')
load:   - 151663 ('<|repo_name|>')
load:   - 151664 ('<|file_sep|>')
load: special tokens cache size = 26
load: token to piece cache size = 0.9311 MB
print_info: arch             = qwen3
print_info: vocab_only       = 0
print_info: n_ctx_train      = 262144
print_info: n_embd           = 2560
print_info: n_layer          = 36
print_info: n_head           = 32
print_info: n_head_kv        = 8
print_info: n_rot            = 128
print_info: n_swa            = 0
print_info: is_swa_any       = 0
print_info: n_embd_head_k    = 128
print_info: n_embd_head_v    = 128
print_info: n_gqa            = 4
print_info: n_embd_k_gqa     = 1024
print_info: n_embd_v_gqa     = 1024
print_info: f_norm_eps       = 0.0e+00
print_info: f_norm_rms_eps   = 1.0e-06
print_info: f_clamp_kqv      = 0.0e+00
print_info: f_max_alibi_bias = 0.0e+00
print_info: f_logit_scale    = 0.0e+00
print_info: f_attn_scale     = 0.0e+00
print_info: n_ff             = 9728
print_info: n_expert         = 0
print_info: n_expert_used    = 0
print_info: causal attn      = 1
print_info: pooling type     = -1
print_info: rope type        = 2
print_info: rope scaling     = linear
print_info: freq_base_train  = 5000000.0
print_info: freq_scale_train = 1
print_info: n_ctx_orig_yarn  = 262144
print_info: rope_finetuned   = unknown
print_info: model type       = 4B
print_info: model params     = 4.02 B
print_info: general.name     = Qwen3 4B Thinking 2507
print_info: vocab type       = BPE
print_info: n_vocab          = 151936
print_info: n_merges         = 151387
print_info: BOS token        = 151643 '<|endoftext|>'
print_info: EOS token        = 151645 '<|im_end|>'
print_info: EOT token        = 151645 '<|im_end|>'
print_info: PAD token        = 151643 '<|endoftext|>'
print_info: LF token         = 198 'Ċ'
print_info: FIM PRE token    = 151659 '<|fim_prefix|>'
print_info: FIM SUF token    = 151661 '<|fim_suffix|>'
print_info: FIM MID token    = 151660 '<|fim_middle|>'
print_info: FIM PAD token    = 151662 '<|fim_pad|>'
print_info: FIM REP token    = 151663 '<|repo_name|>'
print_info: FIM SEP token    = 151664 '<|file_sep|>'
print_info: EOG token        = 151643 '<|endoftext|>'
print_info: EOG token        = 151645 '<|im_end|>'
print_info: EOG token        = 151662 '<|fim_pad|>'
print_info: EOG token        = 151663 '<|repo_name|>'
print_info: EOG token        = 151664 '<|file_sep|>'
print_info: max token length = 256
load_tensors: loading model tensors, this can take a while... (mmap = true)
load_tensors: offloading 36 repeating layers to GPU
load_tensors: offloading output layer to GPU
load_tensors: offloaded 37/37 layers to GPU
load_tensors:        ROCm1 model buffer size =  2375.91 MiB
load_tensors:   CPU_Mapped model buffer size =   304.28 MiB
llama_context: constructing llama_context
llama_context: n_seq_max     = 1
llama_context: n_ctx         = 4096
llama_context: n_ctx_per_seq = 4096
llama_context: n_batch       = 512
llama_context: n_ubatch      = 512
llama_context: causal_attn   = 1
llama_context: flash_attn    = 0
llama_context: kv_unified    = false
llama_context: freq_base     = 5000000.0
llama_context: freq_scale    = 1
llama_context: n_ctx_per_seq (4096) < n_ctx_train (262144) -- the full capacity of the model will not be utilized
llama_context:  ROCm_Host  output buffer size =     0.59 MiB
llama_kv_cache_unified:      ROCm1 KV buffer size =   576.00 MiB
llama_kv_cache_unified: size =  576.00 MiB (  4096 cells,  36 layers,  1/1 seqs), K (f16):  288.00 MiB, V (f16):  288.00 MiB
llama_context:      ROCm1 compute buffer size =   301.75 MiB
llama_context:  ROCm_Host compute buffer size =    17.01 MiB
llama_context: graph nodes  = 1410
llama_context: graph splits = 2
time=2025-08-20T10:42:03.908+05:00 level=INFO source=server.go:1272 msg="llama runner started in 3.18 seconds"
time=2025-08-20T10:42:03.908+05:00 level=INFO source=sched.go:473 msg="loaded runners" count=1
time=2025-08-20T10:42:03.908+05:00 level=INFO source=server.go:1234 msg="waiting for llama runner to start responding"
time=2025-08-20T10:42:03.908+05:00 level=INFO source=server.go:1272 msg="llama runner started in 3.18 seconds"
ROCm error: invalid device function
  current device: 1, in function ggml_cuda_mul_mat_q at C:/a/ollama/ollama/ml/backend/ggml/ggml/src/ggml-cuda/mmq.cu:129
  hipGetLastError()
C:/a/ollama/ollama/ml/backend/ggml/ggml/src/ggml-cuda/ggml-cuda.cu:84: ROCm error
time=2025-08-20T10:42:04.001+05:00 level=ERROR source=server.go:1442 msg="post predict" error="Post \"http://127.0.0.1:59471/completion\": read tcp 127.0.0.1:59472->127.0.0.1:59471: wsarecv: An existing connection was forcibly closed by the remote host."
[GIN] 2025/08/20 - 10:42:04 | 200 |    4.0831461s |       127.0.0.1 | POST     "/api/chat"
time=2025-08-20T10:42:04.182+05:00 level=ERROR source=server.go:409 msg="llama runner terminated" error="exit status 0xc0000409"
```

### OS

Windows

### GPU

AMD

### CPU

AMD

### Ollama version

0.11.5

**Comment by atomskz** [comment]
**Update: Clean OS Test Results**

To further isolate the issue, I performed a clean installation of Windows 11 on the same hardware. The results confirm that the problem is consistent and not related to any prior software conflicts on my main system.

**Steps taken on the fresh OS:**
1.  Installed the latest AMD Adrenalin drivers (version 25.8.1).
2.  Installed the latest version of Ollama (0.11.5) from the official website.
3.  Attempted to run a model immediately after installation (`ollama run qwen:4b`).

**Result:**
The model downloads successfully, but the runner crashes with the same `ROCm error: invalid device function` during initialization. The models never start.

This confirms that the issue is 100% reproducible on a clean system with an AMD RX 7900 XTX (gfx1100) and is not caused by third-party software, previous Ollama installations, or OS corruption. The problem appears to be a fundamental incompatibility between the current Ollama build for Windows and this specific GPU architecture.

**Comment by necpa** [comment]
**Additional Confirmation with AMD Radeon RX 7900 XT (gfx1100)**

I can confirm a similar issue on a system using an **AMD Radeon RX 7900 XT (gfx1100)**:

* **Ollama version**: 0.11.5
* **Driver version**: 25.8.1
* **OS**: Windows 11 (clean install)
* **GPU**: AMD Radeon RX 7900 XT (gfx1100)
* **Symptoms**:

  * Clean installation of Ollama
  * Pulled the `mistral` model successfully
  * On first attempt to run the model, it crashes immediately
  * Model still appears in `ollama list`
  * Logs show the following error:

    ```
    ROCm error: invalid device function
      current device: 1, in function ggml_cuda_op_mul_mat at C:/a/ollama/ollama/ml/backend/ggml/ggml/src/ggml-cuda/ggml-cuda.cu:1758
      hipGetLastError()
    C:/a/ollama/ollama/ml/backend/ggml/ggml/src/ggml-cuda/ggml-cuda.cu:84: ROCm error
    ```

This confirms that the issue affects **other gfx1100 GPUs** beyond the RX 7900 XTX, and happens **immediately after pulling a model**, even before any extended use or API integration. Likely a low-level compatibility issue with ROCm and Ollama’s current CUDA backend on Windows for this GPU architecture.

**Comment by dhiltgen** [comment]
It's possible this may be an interaction between ROCm v6.2 and the latest driver 25.8.1.  You might want to try downgrading to 24.8.1 to see if that gets your system back to a working state while we investigate...

https://drivers.amd.com/drivers/whql-amd-software-adrenalin-edition-24.8.1-win10-win11-aug-rdna.exe

**Comment by atomskz** [comment]
Thank you for the suggestion. I have performed a clean uninstallation of the previous driver (25.8.1) and installed version **24.8.1** as recommended.

**Result:** Unfortunately, the issue persists. The model still fails to load with the same type of `ROCm error: invalid device function`.

**System Info with downgraded driver:**
*   **Driver Version:** 24.8.1 (as shown by `driver=6.1` in the log)
*   **GPU:** AMD Radeon RX 7900 XTX (gfx1100)
*   **Ollama Version:** 0.11.5

Thank you for your continued investigation. Please let me know if there is any other information I can provide from my system to help diagnose this compatibility issue.

<details>

<summary>Screenshot</summary>

<img width="1163" height="708" alt="Image" src="https://github.com/user-attachments/assets/e26fb373-bc0d-4e6e-9361-635e9166f2cb" />

</details>



<details>

<summary>server.log after downgrade</summary>

```log
time=2025-08-20T22:27:38.218+03:00 level=INFO source=routes.go:1318 msg="server config" env="map[CUDA_VISIBLE_DEVICES: GPU_DEVICE_ORDINAL: HIP_VISIBLE_DEVICES: HSA_OVERRIDE_GFX_VERSION: HTTPS_PROXY: HTTP_PROXY: NO_PROXY: OLLAMA_CONTEXT_LENGTH:4096 OLLAMA_DEBUG:INFO OLLAMA_FLASH_ATTENTION:false OLLAMA_GPU_OVERHEAD:0 OLLAMA_HOST:http://127.0.0.1:11434 OLLAMA_INTEL_GPU:false OLLAMA_KEEP_ALIVE:5m0s OLLAMA_KV_CACHE_TYPE: OLLAMA_LLM_LIBRARY: OLLAMA_LOAD_TIMEOUT:5m0s OLLAMA_MAX_LOADED_MODELS:0 OLLAMA_MAX_QUEUE:512 OLLAMA_MODELS:D:\\ollama-models OLLAMA_MULTIUSER_CACHE:false OLLAMA_NEW_ENGINE:false OLLAMA_NEW_ESTIMATES:false OLLAMA_NOHISTORY:false OLLAMA_NOPRUNE:false OLLAMA_NUM_PARALLEL:1 OLLAMA_ORIGINS:[http://localhost https://localhost http://localhost:* https://localhost:* http://127.0.0.1 https://127.0.0.1 http://127.0.0.1:* https://127.0.0.1:* http://0.0.0.0 https://0.0.0.0 http://0.0.0.0:* https://0.0.0.0:* app://* file://* tauri://* vscode-webview://* vscode-file://*] OLLAMA_SCHED_SPREAD:false ROCR_VISIBLE_DEVICES:]"
time=2025-08-20T22:27:38.241+03:00 level=INFO source=images.go:477 msg="total blobs: 5"
time=2025-08-20T22:27:38.241+03:00 level=INFO source=images.go:484 msg="total unused blobs removed: 0"
time=2025-08-20T22:27:38.243+03:00 level=INFO source=routes.go:1371 msg="Listening on 127.0.0.1:11434 (version 0.11.5)"
time=2025-08-20T22:27:38.243+03:00 level=INFO source=gpu.go:217 msg="looking for compatible GPUs"
time=2025-08-20T22:27:38.244+03:00 level=INFO source=gpu_windows.go:167 msg=packages count=1
time=2025-08-20T22:27:38.244+03:00 level=INFO source=gpu_windows.go:214 msg="" package=0 cores=12 efficiency=0 threads=24
time=2025-08-20T22:27:38.789+03:00 level=INFO source=amd_windows.go:127 msg="unsupported Radeon iGPU detected skipping" id=0 total="24.0 GiB"
time=2025-08-20T22:27:39.145+03:00 level=INFO source=types.go:130 msg="inference compute" id=1 library=rocm variant="" compute=gfx1100 driver=6.1 name="AMD Radeon RX 7900 XTX" total="24.0 GiB" available="23.8 GiB"
[GIN] 2025/08/20 - 22:27:39 | 200 |       509.3µs |       127.0.0.1 | GET      "/"
[GIN] 2025/08/20 - 22:27:39 | 200 |      4.6628ms |       127.0.0.1 | GET      "/api/tags"
[GIN] 2025/08/20 - 22:27:39 | 200 |    104.7624ms |       127.0.0.1 | POST     "/api/show"
[GIN] 2025/08/20 - 22:27:56 | 200 |       523.7µs |       127.0.0.1 | GET      "/api/tags"
[GIN] 2025/08/20 - 22:27:56 | 200 |     70.8627ms |       127.0.0.1 | POST     "/api/show"
[GIN] 2025/08/20 - 22:27:56 | 200 |      62.653ms |       127.0.0.1 | POST     "/api/show"
time=2025-08-20T22:27:56.903+03:00 level=INFO source=sched.go:192 msg="one or more GPUs detected that are unable to accurately report free memory - disabling default concurrency"
time=2025-08-20T22:27:57.361+03:00 level=INFO source=server.go:383 msg="starting runner" cmd="C:\\Users\\fedorovn\\AppData\\Local\\Programs\\Ollama\\ollama.exe runner --ollama-engine --model D:\\ollama-models\\blobs\\sha256-b112e727c6f18875636c56a779790a590d705aec9e1c0eb5a97d51fc2a778583 --port 49786"
time=2025-08-20T22:27:57.387+03:00 level=INFO source=runner.go:1006 msg="starting ollama engine"
time=2025-08-20T22:27:57.400+03:00 level=INFO source=runner.go:1043 msg="Server listening on 127.0.0.1:49786"
time=2025-08-20T22:27:57.703+03:00 level=INFO source=server.go:488 msg="system memory" total="63.2 GiB" free="57.3 GiB" free_swap="63.3 GiB"
time=2025-08-20T22:27:57.704+03:00 level=INFO source=memory.go:36 msg="new model will fit in available VRAM across minimum required GPUs, loading" model=D:\ollama-models\blobs\sha256-b112e727c6f18875636c56a779790a590d705aec9e1c0eb5a97d51fc2a778583 library=rocm parallel=1 required="13.9 GiB" gpus=1
time=2025-08-20T22:27:57.704+03:00 level=INFO source=server.go:531 msg=offload library=rocm layers.requested=-1 layers.model=25 layers.offload=25 layers.split=[25] memory.available="[23.8 GiB]" memory.gpu_overhead="0 B" memory.required.full="13.9 GiB" memory.required.partial="13.9 GiB" memory.required.kv="300.0 MiB" memory.required.allocations="[13.9 GiB]" memory.weights.total="11.7 GiB" memory.weights.repeating="10.7 GiB" memory.weights.nonrepeating="1.1 GiB" memory.graph.full="1.0 GiB" memory.graph.partial="1.0 GiB"
time=2025-08-20T22:27:57.706+03:00 level=INFO source=runner.go:925 msg=load request="{Operation:commit LoraPath:[] Parallel:1 BatchSize:512 FlashAttention:false KvSize:8192 KvCacheType: NumThreads:12 GPULayers:25[ID:1 Layers:25(0..24)] MultiUserCache:false ProjectorPath: MainGPU:0 UseMmap:false}"
time=2025-08-20T22:27:57.744+03:00 level=INFO source=ggml.go:130 msg="" architecture=gptoss file_type=MXFP4 name="" description="" num_tensors=315 num_key_values=30
ggml_cuda_init: GGML_CUDA_FORCE_MMQ:    no
ggml_cuda_init: GGML_CUDA_FORCE_CUBLAS: no
ggml_cuda_init: found 2 ROCm devices:
  Device 0: AMD Radeon(TM) Graphics, gfx1036 (0x1036), VMM: no, Wave Size: 32, ID: 0
  Device 1: AMD Radeon RX 7900 XTX, gfx1100 (0x1100), VMM: no, Wave Size: 32, ID: 1
load_backend: loaded ROCm backend from C:\Users\fedorovn\AppData\Local\Programs\Ollama\lib\ollama\ggml-hip.dll
load_backend: loaded CPU backend from C:\Users\fedorovn\AppData\Local\Programs\Ollama\lib\ollama\ggml-cpu-icelake.dll
time=2025-08-20T22:27:59.267+03:00 level=INFO source=ggml.go:104 msg=system CPU.0.SSE3=1 CPU.0.SSSE3=1 CPU.0.AVX=1 CPU.0.AVX2=1 CPU.0.F16C=1 CPU.0.FMA=1 CPU.0.BMI2=1 CPU.0.AVX512=1 CPU.0.AVX512_VBMI=1 CPU.0.AVX512_VNNI=1 CPU.0.LLAMAFILE=1 CPU.1.LLAMAFILE=1 ROCm.0.NO_VMM=1 ROCm.0.NO_PEER_COPY=1 ROCm.0.PEER_MAX_BATCH_SIZE=128 ROCm.1.NO_VMM=1 ROCm.1.NO_PEER_COPY=1 ROCm.1.PEER_MAX_BATCH_SIZE=128 compiler=cgo(clang)
time=2025-08-20T22:28:00.280+03:00 level=INFO source=ggml.go:486 msg="offloading 24 repeating layers to GPU"
time=2025-08-20T22:28:00.280+03:00 level=INFO source=ggml.go:492 msg="offloading output layer to GPU"
time=2025-08-20T22:28:00.280+03:00 level=INFO source=ggml.go:497 msg="offloaded 25/25 layers to GPU"
time=2025-08-20T22:28:00.280+03:00 level=INFO source=backend.go:310 msg="model weights" device=ROCm1 size="11.8 GiB"
time=2025-08-20T22:28:00.280+03:00 level=INFO source=backend.go:315 msg="model weights" device=CPU size="1.1 GiB"
time=2025-08-20T22:28:00.280+03:00 level=INFO source=backend.go:321 msg="kv cache" device=ROCm1 size="300.0 MiB"
time=2025-08-20T22:28:00.280+03:00 level=INFO source=backend.go:332 msg="compute graph" device=ROCm1 size="1.1 GiB"
time=2025-08-20T22:28:00.280+03:00 level=INFO source=backend.go:337 msg="compute graph" device=CPU size="5.6 MiB"
time=2025-08-20T22:28:00.280+03:00 level=INFO source=backend.go:342 msg="total memory" size="14.2 GiB"
time=2025-08-20T22:28:00.280+03:00 level=INFO source=sched.go:473 msg="loaded runners" count=1
time=2025-08-20T22:28:00.280+03:00 level=INFO source=server.go:1234 msg="waiting for llama runner to start responding"
time=2025-08-20T22:28:00.281+03:00 level=INFO source=server.go:1268 msg="waiting for server to become available" status="llm server loading model"
time=2025-08-20T22:28:07.797+03:00 level=INFO source=server.go:1272 msg="llama runner started in 10.44 seconds"
ROCm error: invalid device function
  current device: 1, in function ggml_cuda_op_mul_mat at C:/a/ollama/ollama/ml/backend/ggml/ggml/src/ggml-cuda/ggml-cuda.cu:1758
  hipGetLastError()
C:/a/ollama/ollama/ml/backend/ggml/ggml/src/ggml-cuda/ggml-cuda.cu:84: ROCm error
time=2025-08-20T22:28:08.185+03:00 level=ERROR source=server.go:1442 msg="post predict" error="Post \"http://127.0.0.1:49786/completion\": read tcp 127.0.0.1:49787->127.0.0.1:49786: wsarecv: An existing connection was forcibly closed by the remote host."
[GIN] 2025/08/20 - 22:28:08 | 200 |   11.7016405s |       127.0.0.1 | POST     "/api/chat"
time=2025-08-20T22:28:08.212+03:00 level=ERROR source=server.go:409 msg="llama runner terminated" error="exit status 0xc0000409"
```

</details>

**Comment by DanielKluev** [comment]
I've had exactly same problem, happened in the middle of long agentic session when ollama suddenly on its own decided it's fine to update to 0.11.5.
After that, everything stopped working on gfx1100 GPUs. 

Once I reverted ollama back to 0.11.4, everything works again. So it's certainly something in 0.11.5 that causes the error.

**Comment by atomskz** [comment]
**Update: Rollback to v0.11.4 Resolves the Issue**

I can confirm that rolling back to Ollama version **0.11.4** (with AMD driver 25.8.1) has successfully resolved the problem.

The model (`qwen:4b`) now loads and runs correctly on **Ollama v0.11.4:**. Chat functionality via the command line and API is fully operational.

To provide a complete test case, I also upgraded to the latest version, **Ollama v0.11.6**. The `ROCm error: invalid device function` crash still occurs on this version, confirming that the regression was introduced after v0.11.4 and has not yet been fixed.

**Comment by gqchen-dz** [comment]
the same error , ollama version : 0.11.5 and 0.11.6，on Tesla T4.
the ollama version 0.11.4 is well.

**Comment by MStefan99** [comment]
Similar error with a fresh Ollama 0.11.6 reinstall and AMD drivers 25.8.1 on AMD Radeon RX 7900 XTX

Relevant Ollama logs:
```
time=2025-08-21T11:02:02.130+02:00 level=INFO source=server.go:1268 msg="waiting for server to become available" status="llm server loading model"
time=2025-08-21T11:02:10.668+02:00 level=INFO source=server.go:1272 msg="llama runner started in 17.83 seconds"
ggml_cuda_compute_forward: SCALE failed
ROCm error: invalid device function
  current device: 1, in function ggml_cuda_compute_forward at C:/a/ollama/ollama/ml/backend/ggml/ggml/src/ggml-cuda/ggml-cuda.cu:2563
  err
C:/a/ollama/ollama/ml/backend/ggml/ggml/src/ggml-cuda/ggml-cuda.cu:84: ROCm error
time=2025-08-21T11:02:10.999+02:00 level=ERROR source=server.go:1442 msg="post predict" error="Post \"http://127.0.0.1:50997/completion\": read tcp 127.0.0.1:50998->127.0.0.1:50997: wsarecv: An existing connection was forcibly closed by the remote host."

```

**Comment by haraldhotzbehofsits** [comment]
Same observation from my side, 0.11.4 is fine, at least with ROCm .5 and .6 fail.

**Comment by isoscelesjones** [comment]
Same - .4 works and .5 and .6 fail. And I can't prevent .4 from automatically updating to .6

**Comment by PRSJMC** [comment]
same on 7800XT，gfx1101

**Comment by awball0** [comment]
Same on 7900XTX

**Comment by HaroldStash** [comment]
Set the environment variables ROCR_VISIBLE_DEVICES=1 and HIP_VISIBLE_DEVICES=1 for the bypass to actually skip the iGPU from being utilized with ollama/llama.cpp.   The 7900xtx works fine on 6.4 rocm.   The value is the index of the card you want to run it on(0 = igpu, 1 = dedicated on my machine). 

  Device 0: AMD Radeon(TM) Graphics, gfx1036 (0x1036), VMM: no, Wave Size: 32, ID: 0
  Device 1: AMD Radeon RX 7900 XTX, gfx1100 (0x1100), VMM: no, Wave Size: 32, ID: 1

You can confirm the iGPU being skipped by running hipinfo

**Comment by dhiltgen** [comment]
We'll get this regression fixed soon to filter out the unsupported iGPUs again - until then, using HIP_VISIBLE_DEVICES on windows or ROCR_VISIBLE_DEVICES on linux as described above will workaround the regression.

**Comment by awball0** [comment]
Thank you, the HIP_VISIBLE_DEVICES environment variable on Windows worked for me :)

**Comment by jzila** [comment]
FWIW I get this same crash on ollama 11.10 with the Ryzen AI Max 395+ which has the supported gfx1151 Strix Halo GPU. I've manually set the `HSA_OVERRIDE_GFX_VERSION` to `11.5.1` to get it to recognize the GPU, but then the logs say it doesn't offload any model layers, after which the runner crashes as soon as I submit an inference call. I'm trying to use `qwen3-coder:30b`.
