### ISSUE TITLE
After ROCm Upgrade, HSA_OVERRIDE_GFX_VERSION to 10.3.0 Causes SIGSEGV After Receiving Prompt; No Override Works, But Falls Back to CPU

### ISSUE THREAD

**Issue by reteov** [ollama/ollama#12111]
### What is the issue?

I'm using a gfx1031 GPU (Radeon RX 6750 XT), I just set the HSA_OVERRIDE_GFX_VERSION to 10.3.0 to allow ollama to work.  It's been working fine for a while now, and I've not had any problems—at least, nothing that doesn't require more hardware to solve, and therefore has nothing to do with ollama.

However, a couple days ago, I pulled the trigger on a system upgrade.  Among the upgrades were ones for ROCm (to 6.4.3).  Once these upgrades were complete, Ollama would fail with a SIGSEGV whenever I submit a prompt, regardless if it's the command-line tool or the API.  Removing the override would fix the problem, but return the LLM to CPU-only operation.  I recently discovered that downgrading ROCm back to 6.4.1 also worked.  However, obviously, while I can keep things as they are, it's not a long-term solution, and I'm not sure if this is something to approach ROCm ro you guys about, so I figured I'd place the bug report here first, in case you need to coordinate or something.

I've done some research, including with ChatGPT (itasked for some tools' output).  I've included all the logs and reports I've made, and for anyone else who's having the same issue, downgrading ROCm back to 6.4.1 (at least, that I'm aware of) should allow GPU functionality to work again.

Please let me know if there's anything else you need.

[ggml_ROCm_lib__code_objects.txt](https://github.com/user-attachments/files/22035280/ggml_ROCm_lib__code_objects.txt)
[hardinfo2_report.html](https://github.com/user-attachments/files/22035275/hardinfo2_report.html)
[installed.log](https://github.com/user-attachments/files/22035278/installed.log)
[libggml-hip_locations.txt](https://github.com/user-attachments/files/22035273/libggml-hip_locations.txt)
[loaded_libggml-hip.txt](https://github.com/user-attachments/files/22035274/loaded_libggml-hip.txt)
[ollama-default.log](https://github.com/user-attachments/files/22035272/ollama-default.log)
[ollama-gfx1030.log](https://github.com/user-attachments/files/22035276/ollama-gfx1030.log)
[ollama-symlink-addition.log](https://github.com/user-attachments/files/22035279/ollama-symlink-addition.log)
[rocminfo.log](https://github.com/user-attachments/files/22035277/rocminfo.log)

### Relevant log output

```shell

```

**Comment by vcottineau** [comment]
Hello, I am facing a similar issue since the latest Manjaro update.

### Error

```
Error: model runner has unexpectedly stopped, this may be due to resource limitations or an internal error, check ollama server logs for details

août 30 20:17:58 manjaro ollama[1948]: time=2025-08-30T20:17:58.476+02:00 level=INFO source=server.go:637 msg="llama runner started in 11.04 seconds"
août 30 20:17:58 manjaro ollama[1948]: [GIN] 2025/08/30 - 20:17:58 | 200 | 11.071629851s |       127.0.0.1 | POST     "/api/generate"
août 30 20:18:00 manjaro ollama[1948]: SIGSEGV: segmentation violation
```

### Logs

[rocminfo.log](https://github.com/user-attachments/files/22060103/rocminfo.log)
[server.log](https://github.com/user-attachments/files/22060114/server.log)

### Version

CPU = AMD Ryzen 9 8945HS
GPU = AMD Radeon 780M
ROCm = 6.4.3
Ollama = 0.11.4

**Comment by vcottineau** [comment]
Today's ROCm update to 6.4.3-3 fixed the issue for me.

**Comment by apeacock** [comment]
Where did you get the 6.4.3-3 update from, can't seem to find it.

**Comment by reteov** [comment]
If you're using Arch, you'll need to make sure you're using `sudo pacman -Syu` to update your package list.  If it is still not showing up, then you might need to refresh your mirror list.

Something to keep in mind is that it's RocBLAS that seemed to be causing the issue, and that is what's been updated to 6.4.3-3 (although rocsparse also is now at 6.4.3-3, as well)

I'm able to confirm that the issue is resolved.

**Comment by dhiltgen** [comment]
Sounds like we can close this now.
