### ISSUE TITLE
run gemma3:12b Error: 500 Internal Server Error: llama runner process has terminated

### ISSUE THREAD

**Issue by 1574802103** [ollama/ollama#12366]
### What is the issue?

C:\Users\zhang>ollama run gemma3:12b
Error: 500 Internal Server Error: llama runner process has terminated: CUDA errorC:\a\ollama\ollama\ml\backend\ggml\ggml\src\ggml-cuda\ggml-cuda.cu:84: CUDA error
C:\a\ollama\ollama\ml\backend\ggml\ggml\src\ggml-cuda\ggml-cuda.cu:84: CUDA error
C:\a\ollama\ollama\ml\backend\ggml\ggml\src\ggml-cuda\ggml-cuda.cu:84: CUDA error
C:\a\ollama\ollama\ml\backend\ggml\ggml\src\ggml-cuda\ggml-cuda.cu:84: CUDA error
C:\a\ollama\ollama\ml\backend\ggml\ggml\src\ggml-cuda\ggml-cuda.cu:84: CUDA error

### Relevant log output

```shell

```

### OS

Windows

### GPU

Nvidia

### CPU

Intel

### Ollama version

0.12.0

**Comment by 1574802103** [comment]
C:\Users\zhang>ollama run gemma3:12b
Error: 500 Internal Server Error: llama runner process has terminated: CUDA error: invalid argument

C:\Users\zhang>ollama run gemma3:12b
Error: 500 Internal Server Error: llama runner process has terminated: CUDA error: invalid argument
  current device: 0, in function ggml_backend_cuda_buffer_set_tensor at C:\a\ollama\ollama\ml\backend\ggml\ggml\src\ggml-cuda\ggml-cuda.cu:667
  current device: 0, in function ggml_backend_cuda_buffer_set_tensor at C:\a\ollama\ollama\ml\backend\ggml\ggml\src\ggml-cuda\ggml-cuda.cu:667
  cudaMemcpyAsync((char *)tensor->data + offset, data, size, cudaMemcpyHostToDevice, ((cudaStream_t)0x2))
CUDA error: invalid argument
C:\a\ollama\ollama\ml\backend\ggml\ggml\src\ggml-cuda\ggml-cuda.cu:84: CUDA error
  cudaMemcpyAsync((char *)tensor->data + offset, data, size, cudaMemcpyHostToDevice, ((cudaStream_t)0x2))
  current device: 0, in function ggml_backend_cuda_buffer_set_tensor at C:\a\ollama\ollama\ml\backend\ggml\ggml\src\ggml-cuda\ggml-cuda.cu:667
C:\a\ollama\ollama\ml\backend\ggml\ggml\src\ggml-cuda\ggml-cuda.cu:84: CUDA error
  cudaMemcpyAsync((char *)tensor->data + offset, data, size, cudaMemcpyHostToDevice, ((cudaStream_t)0x2))
CUDA error: invalid argument
C:\a\ollama\ollama\ml\backend\ggml\ggml\src\ggml-cuda\ggml-cuda.cu:84: CUDA error
  current device: 0, in function ggml_backend_cuda_buffer_set_tensor at C:\a\ollama\ollama\ml\backend\ggml\ggml\src\ggml-cuda\ggml-cuda.cu:667
  cudaMemcpyAsync((char *)tensor->data + offset, data, size, cudaMemcpyHostToDevice, ((cudaStream_t)0x2))
C:\a\ollama\ollama\ml\backend\ggml\ggml\src\ggml-cuda\ggml-cuda.cu:84: CUDA error
CUDA error: invalid argument
  current device: 0, in function ggml_backend_cuda_buffer_set_tensor at C:\a\ollama\ollama\ml\backend\ggml\ggml\src\ggml-cuda\ggml-cuda.cu:667
  cudaMemcpyAsync((char *)tensor->data + offset, data, size, cudaMemcpyHostToDevice, ((cudaStream_t)0x2))
C:\a\ollama\ollama\ml\backend\ggml\ggml\src\ggml-cuda\ggml-cuda.cu:84: CUDA error

**Comment by therealkenc** [comment]
"Same here"

Adding this env fixed it for me: `OLLAMA_LLM_LIBRARY=cuda_v13`

**Comment by jessegross** [comment]
Can you please post the full log with OLLAMA_DEBUG=1?

If setting OLLAMA_LLM_LIBRARY solves the issue then it might be the same as https://github.com/ollama/ollama/issues/11211, which is caused overlapping installations of old and new versions and can be solved by a full reinstall.

**Comment by 1574802103** [comment]
卸载ollama 重新装就好了 感谢 [jessegross](https://github.com/jessegross)
