### ISSUE TITLE
Vulkan not working on Linux (Ubuntu Server 25.10)

### ISSUE THREAD

**Issue by rladinger** [ollama/ollama#12673]
### What is the issue?

The GPU detection crashes when starting Ollama. In my opinion, it doesn't even try to access Vulkan. Or does an environment variable still need to be set for Vulkan?

### Relevant log output

```shell
2025-10-17T05:14:40.285508+00:00 ai ollama[3616]: time=2025-10-17T05:14:40.283Z level=INFO source=routes.go:1511 msg="server config" env="map[CUDA_VISIBLE_DEVICES: GGML_VK_VISIBLE_DEVICES: GPU_DEVICE_ORDINAL: HIP_VISIBLE_DEVICES: HSA_OVERRIDE_GFX_VERSION: HTTPS_PROXY: HTTP_PROXY: NO_PROXY: OLLAMA_CONTEXT_LENGTH:4096 OLLAMA_DEBUG:INFO OLLAMA_FLASH_ATTENTION:false OLLAMA_GPU_OVERHEAD:0 OLLAMA_HOST:http://0.0.0.0:11434 OLLAMA_INTEL_GPU:false OLLAMA_KEEP_ALIVE:5m0s OLLAMA_KV_CACHE_TYPE: OLLAMA_LLM_LIBRARY: OLLAMA_LOAD_TIMEOUT:5m0s OLLAMA_MAX_LOADED_MODELS:0 OLLAMA_MAX_QUEUE:512 OLLAMA_MODELS:/usr/share/ollama/.ollama/models OLLAMA_MULTIUSER_CACHE:false OLLAMA_NEW_ENGINE:false OLLAMA_NOHISTORY:false OLLAMA_NOPRUNE:false OLLAMA_NUM_PARALLEL:1 OLLAMA_ORIGINS:[http://localhost https://localhost http://localhost:* https://localhost:* http://127.0.0.1 https://127.0.0.1 http://127.0.0.1:* https://127.0.0.1:* http://0.0.0.0 https://0.0.0.0 http://0.0.0.0:* https://0.0.0.0:* app://* file://* tauri://* vscode-webview://* vscode-file://*] OLLAMA_REMOTES:[ollama.com] OLLAMA_SCHED_SPREAD:false ROCR_VISIBLE_DEVICES: http_proxy: https_proxy: no_proxy:]"
2025-10-17T05:14:40.301116+00:00 ai ollama[3616]: time=2025-10-17T05:14:40.301Z level=INFO source=images.go:522 msg="total blobs: 72"
2025-10-17T05:14:40.301759+00:00 ai ollama[3616]: time=2025-10-17T05:14:40.301Z level=INFO source=images.go:529 msg="total unused blobs removed: 0"
2025-10-17T05:14:40.303793+00:00 ai ollama[3616]: time=2025-10-17T05:14:40.303Z level=INFO source=routes.go:1564 msg="Listening on [::]:11434 (version 0.12.6)"
2025-10-17T05:14:40.307259+00:00 ai ollama[3616]: time=2025-10-17T05:14:40.306Z level=INFO source=runner.go:80 msg="discovering available GPUs..."
2025-10-17T05:14:42.312826+00:00 ai ollama[3616]: time=2025-10-17T05:14:42.312Z level=INFO source=runner.go:545 msg="failure during GPU discovery" OLLAMA_LIBRARY_PATH="[/usr/local/lib/ollama /usr/local/lib/ollama/rocm]" extra_envs="[GGML_CUDA_INIT=1 ROCR_VISIBLE_DEVICES=0]" error="runner crashed"
2025-10-17T05:14:42.312933+00:00 ai ollama[3616]: time=2025-10-17T05:14:42.312Z level=INFO source=types.go:129 msg="inference compute" id=cpu library=cpu compute="" name=cpu description=cpu libdirs=ollama driver="" pci_id="" type="" total="57.5 GiB" available="52.9 GiB"
2025-10-17T05:14:42.312962+00:00 ai ollama[3616]: time=2025-10-17T05:14:42.312Z level=INFO source=routes.go:1605 msg="entering low vram mode" "total vram"="0 B" threshold="20.0 GiB"

vulkaninfo --summary
'DISPLAY' environment variable not set... skipping surface info
error: XDG_RUNTIME_DIR is invalid or not set in the environment.
==========
VULKANINFO
==========

Vulkan Instance Version: 1.4.321


Instance Extensions: count = 24
-------------------------------
VK_EXT_acquire_drm_display             : extension revision 1
VK_EXT_acquire_xlib_display            : extension revision 1
VK_EXT_debug_report                    : extension revision 10
VK_EXT_debug_utils                     : extension revision 2
VK_EXT_direct_mode_display             : extension revision 1
VK_EXT_display_surface_counter         : extension revision 1
VK_EXT_headless_surface                : extension revision 1
VK_EXT_surface_maintenance1            : extension revision 1
VK_EXT_swapchain_colorspace            : extension revision 5
VK_KHR_device_group_creation           : extension revision 1
VK_KHR_display                         : extension revision 23
VK_KHR_external_fence_capabilities     : extension revision 1
VK_KHR_external_memory_capabilities    : extension revision 1
VK_KHR_external_semaphore_capabilities : extension revision 1
VK_KHR_get_display_properties2         : extension revision 1
VK_KHR_get_physical_device_properties2 : extension revision 2
VK_KHR_get_surface_capabilities2       : extension revision 1
VK_KHR_portability_enumeration         : extension revision 1
VK_KHR_surface                         : extension revision 25
VK_KHR_surface_protected_capabilities  : extension revision 1
VK_KHR_wayland_surface                 : extension revision 6
VK_KHR_xcb_surface                     : extension revision 6
VK_KHR_xlib_surface                    : extension revision 6
VK_LUNARG_direct_driver_loading        : extension revision 1

Instance Layers: count = 4
--------------------------
VK_LAYER_INTEL_nullhw       INTEL NULL HW                1.1.73   version 1
VK_LAYER_KHRONOS_validation Khronos Validation Layer     1.4.321  version 1
VK_LAYER_MESA_device_select Linux device selection layer 1.4.303  version 1
VK_LAYER_MESA_overlay       Mesa Overlay layer           1.4.303  version 1

Devices:
========
GPU0:
        apiVersion         = 1.4.318
        driverVersion      = 25.2.3
        vendorID           = 0x1002
        deviceID           = 0x150e
        deviceType         = PHYSICAL_DEVICE_TYPE_INTEGRATED_GPU
        deviceName         = AMD Radeon 890M Graphics (RADV GFX1150)
        driverID           = DRIVER_ID_MESA_RADV
        driverName         = radv
        driverInfo         = Mesa 25.2.3-1ubuntu1
        conformanceVersion = 1.4.0.0
        deviceUUID         = 00000000-c600-0000-0000-000000000000
        driverUUID         = 414d442d-4d45-5341-2d44-525600000000
GPU1:
        apiVersion         = 1.4.318
        driverVersion      = 25.2.3
        vendorID           = 0x10005
        deviceID           = 0x0000
        deviceType         = PHYSICAL_DEVICE_TYPE_CPU
        deviceName         = llvmpipe (LLVM 20.1.8, 256 bits)
        driverID           = DRIVER_ID_MESA_LLVMPIPE
        driverName         = llvmpipe
        driverInfo         = Mesa 25.2.3-1ubuntu1 (LLVM 20.1.8)
        conformanceVersion = 1.3.1.1
        deviceUUID         = 6d657361-3235-2e32-2e33-2d3175627500
        driverUUID         = 6c6c766d-7069-7065-5555-494400000000
```

### OS

Linux

### GPU

AMD

### CPU

AMD

### Ollama version

0.12.6

**Comment by seboss666** [comment]
It's stated [in the pull request](https://github.com/ollama/ollama/pull/5059) about experimental support that it's not enabled by default. You need to compile ollama explicitly yourself to try it. I'm also having segfault on gpu detection for now (780M here), I hope it will be better handled in the near future, not fond of having to constantly manually compile too many things for AMD related stuff, when Nvidia ecosystem is so much easier to deal with.

**Comment by rladinger** [comment]
I hope so too. I don't think NVIDIA is receiving preferential treatment, as AMD also has an increasing number of users. I am always happy to test either the new ROCm environment or VULKAN Ollama to see which ones support my GPUs or even NPUs.

**Comment by dhiltgen** [comment]
In 0.12.11 Vulkan is now included in the official binaries, but still experimental.  To enable, set OLLAMA_VULKAN=1 for the server.  https://github.com/ollama/ollama/blob/main/docs/faq.mdx#how-do-i-configure-ollama-server

**Comment by EvgenyAfanasev** [comment]
> In 0.12.11 Vulkan is now included in the official binaries, but still experimental. To enable, set OLLAMA_VULKAN=1 for the server. https://github.com/ollama/ollama/blob/main/docs/faq.mdx#how-do-i-configure-ollama-server

I added OLLAMA_VULKAN=1 to systemd service and it works, but after startup my laptop ollama runs with cpu mode and I have to restart ollama for activating vulkan mode

**Comment by EvgenyAfanasev** [comment]
IMHO, may be vulkan isn't load before ollama startup, but I dont know what ollama should wait before startup

**Comment by EvgenyAfanasev** [comment]
> IMHO, may be vulkan isn't load before ollama startup, but I dont know what ollama should wait before startup

I found solution - change Afters and Wants params:

```
After=network-online.target graphical.target
Wants=graphical.target
```
