### ISSUE TITLE
Cannot  run any model - Ollama incompatible with kernel 6.19?

### ISSUE THREAD

**Issue by ndrewpj** [ollama/ollama#14253]
### What is the issue?

I cannot load and run models in ollama in docker. I have AMD Strix halo, according to the ollama log on loading the increased VRAM size is visible to ollama:

[GIN] 2026/02/14 - 12:51:23 | 500 |  816.630011ms |       127.0.0.1 | POST     "/api/embed"

time=2026-02-14T12:53:02.765Z level=INFO source=routes.go:1636 msg="server config" env="map[CUDA_VISIBLE_DEVICES: GGML_VK_VISIBLE_DEVICES: GPU_DEVICE_ORDINAL: HIP_VISIBLE_DEVICES: HSA_OVERRIDE_GFX_VERSION: HTTPS_PROXY: HTTP_PROXY: NO_PROXY: OLLAMA_CONTEXT_LENGTH:8192 OLLAMA_DEBUG:INFO OLLAMA_EDITOR: OLLAMA_FLASH_ATTENTION:true OLLAMA_GPU_OVERHEAD:0 OLLAMA_HOST:http://0.0.0.0:11434 OLLAMA_KEEP_ALIVE:5m0s OLLAMA_KV_CACHE_TYPE:q8_0 OLLAMA_LLM_LIBRARY: OLLAMA_LOAD_TIMEOUT:5m0s OLLAMA_MAX_LOADED_MODELS:2 OLLAMA_MAX_QUEUE:512 OLLAMA_MODELS:/root/.ollama/models OLLAMA_MULTIUSER_CACHE:false OLLAMA_NEW_ENGINE:false OLLAMA_NOHISTORY:false OLLAMA_NOPRUNE:false OLLAMA_NUM_PARALLEL:1 OLLAMA_ORIGINS:[http://localhost https://localhost http://localhost:* https://localhost:* http://127.0.0.1 https://127.0.0.1 http://127.0.0.1:* https://127.0.0.1:* http://0.0.0.0 https://0.0.0.0 http://0.0.0.0:* https://0.0.0.0:* app://* file://* tauri://* vscode-webview://* vscode-file://*] OLLAMA_REMOTES:[ollama.com] OLLAMA_SCHED_SPREAD:false OLLAMA_VULKAN:false ROCR_VISIBLE_DEVICES: http_proxy: https_proxy: no_proxy:]"

time=2026-02-14T12:53:02.766Z level=INFO source=images.go:473 msg="total blobs: 30"

time=2026-02-14T12:53:02.766Z level=INFO source=images.go:480 msg="total unused blobs removed: 0"

time=2026-02-14T12:53:02.766Z level=INFO source=routes.go:1689 msg="Listening on [::]:11434 (version 0.16.1)"

time=2026-02-14T12:53:02.767Z level=INFO source=runner.go:67 msg="discovering available GPUs..."

time=2026-02-14T12:53:02.767Z level=INFO source=server.go:431 msg="starting runner" cmd="/usr/bin/ollama runner --ollama-engine --port 39845"

time=2026-02-14T12:53:03.120Z level=INFO source=server.go:431 msg="starting runner" cmd="/usr/bin/ollama runner --ollama-engine --port 38575"

time=2026-02-14T12:53:03.530Z level=INFO source=types.go:42 msg="inference compute" id=0 filter_id=0 library=ROCm compute=gfx1151 name=ROCm0 description="AMD Radeon Graphics" libdirs=ollama,rocm driver=60342.13 pci_id=0000:c5:00.0 type=iGPU total="120.4 GiB" available="118.3 GiB"

time=2026-02-14T12:53:03.530Z level=INFO source=routes.go:1739 msg="vram-based default context" total_vram="120.4 GiB" default_num_ctx=262144

### Relevant log output

```shell
runtime/mgc.go:1339 +0x105

goroutine 53 gp=0xc000120540 m=nil [GC worker (idle)]:

runtime.gopark(0x55ef24d58560?, 0x1?, 0xc1?, 0x22?, 0x0?)

	runtime/proc.go:435 +0xce fp=0xc000119f38 sp=0xc000119f18 pc=0x55ef22a89f4e

runtime.gcBgMarkWorker(0xc00003f7a0)

	runtime/mgc.go:1423 +0xe9 fp=0xc000119fc8 sp=0xc000119f38 pc=0x55ef22a37b09

runtime.gcBgMarkStartWorkers.gowrap1()

	runtime/mgc.go:1339 +0x25 fp=0xc000119fe0 sp=0xc000119fc8 pc=0x55ef22a379e5

runtime.goexit({})

	runtime/asm_amd64.s:1700 +0x1 fp=0xc000119fe8 sp=0xc000119fe0 pc=0x55ef22a91ec1

created by runtime.gcBgMarkStartWorkers in goroutine 1

	runtime/mgc.go:1339 +0x105

goroutine 13 gp=0xc00021d6c0 m=nil [GC worker (idle)]:

runtime.gopark(0x55ef24d58560?, 0x1?, 0x78?, 0x2d?, 0x0?)

	runtime/proc.go:435 +0xce fp=0xc000507f38 sp=0xc000507f18 pc=0x55ef22a89f4e

runtime.gcBgMarkWorker(0xc00003f7a0)

	runtime/mgc.go:1423 +0xe9 fp=0xc000507fc8 sp=0xc000507f38 pc=0x55ef22a37b09

runtime.gcBgMarkStartWorkers.gowrap1()

	runtime/mgc.go:1339 +0x25 fp=0xc000507fe0 sp=0xc000507fc8 pc=0x55ef22a379e5

runtime.goexit({})

	runtime/asm_amd64.s:1700 +0x1 fp=0xc000507fe8 sp=0xc000507fe0 pc=0x55ef22a91ec1

created by runtime.gcBgMarkStartWorkers in goroutine 1

	runtime/mgc.go:1339 +0x105

goroutine 14 gp=0xc000582fc0 m=nil [sync.WaitGroup.Wait]:

runtime.gopark(0x0?, 0x0?, 0x20?, 0x61?, 0x0?)

	runtime/proc.go:435 +0xce fp=0xc0000bda90 sp=0xc0000bda70 pc=0x55ef22a89f4e

runtime.goparkunlock(...)

	runtime/proc.go:441

runtime.semacquire1(0xc000269198, 0x0, 0x1, 0x0, 0x18)

	runtime/sema.go:188 +0x229 fp=0xc0000bdaf8 sp=0xc0000bda90 pc=0x55ef22a69d49

sync.runtime_SemacquireWaitGroup(0x0?)

	runtime/sema.go:110 +0x25 fp=0xc0000bdb30 sp=0xc0000bdaf8 pc=0x55ef22a8b885

sync.(*WaitGroup).Wait(0xc000269190?)

	sync/waitgroup.go:118 +0x48 fp=0xc0000bdb58 sp=0xc0000bdb30 pc=0x55ef22a9d928

github.com/ollama/ollama/runner/ollamarunner.(*Server).run(0xc0002690e0, {0x55ef24289ea0, 0xc0003b9810})

	github.com/ollama/ollama/runner/ollamarunner/runner.go:442 +0x45 fp=0xc0000bdfb8 sp=0xc0000bdb58 pc=0x55ef23088805

github.com/ollama/ollama/runner/ollamarunner.Execute.gowrap1()

	github.com/ollama/ollama/runner/ollamarunner/runner.go:1424 +0x28 fp=0xc0000bdfe0 sp=0xc0000bdfb8 pc=0x55ef23092088

runtime.goexit({})

	runtime/asm_amd64.s:1700 +0x1 fp=0xc0000bdfe8 sp=0xc0000bdfe0 pc=0x55ef22a91ec1

created by github.com/ollama/ollama/runner/ollamarunner.Execute in goroutine 1

	github.com/ollama/ollama/runner/ollamarunner/runner.go:1424 +0x4c9

goroutine 66 gp=0xc000583500 m=nil [IO wait]:

runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0xb?)

	runtime/proc.go:435 +0xce fp=0xc00050d5d8 sp=0xc00050d5b8 pc=0x55ef22a89f4e

runtime.netpollblock(0x55ef22aad7f8?, 0x22a23506?, 0xef?)

	runtime/netpoll.go:575 +0xf7 fp=0xc00050d610 sp=0xc00050d5d8 pc=0x55ef22a4f0f7

internal/poll.runtime_pollWait(0x7fdf27fc6d98, 0x72)

	runtime/netpoll.go:351 +0x85 fp=0xc00050d630 sp=0xc00050d610 pc=0x55ef22a89165

internal/poll.(*pollDesc).wait(0xc0004f6a80?, 0xc00012f4b1?, 0x0)

	internal/poll/fd_poll_runtime.go:84 +0x27 fp=0xc00050d658 sp=0xc00050d630 pc=0x55ef22b11487

internal/poll.(*pollDesc).waitRead(...)

	internal/poll/fd_poll_runtime.go:89

internal/poll.(*FD).Read(0xc0004f6a80, {0xc00012f4b1, 0x1, 0x1})

	internal/poll/fd_unix.go:165 +0x27a fp=0xc00050d6f0 sp=0xc00050d658 pc=0x55ef22b1277a

net.(*netFD).Read(0xc0004f6a80, {0xc00012f4b1?, 0x0?, 0x0?})

	net/fd_posix.go:55 +0x25 fp=0xc00050d738 sp=0xc00050d6f0 pc=0x55ef22b87cc5

net.(*conn).Read(0xc0000aea58, {0xc00012f4b1?, 0x0?, 0x0?})

	net/net.go:194 +0x45 fp=0xc00050d780 sp=0xc00050d738 pc=0x55ef22b96085

net/http.(*connReader).backgroundRead(0xc00012f4a0)

	net/http/server.go:690 +0x37 fp=0xc00050d7c8 sp=0xc00050d780 pc=0x55ef22d82bd7

net/http.(*connReader).startBackgroundRead.gowrap2()

	net/http/server.go:686 +0x25 fp=0xc00050d7e0 sp=0xc00050d7c8 pc=0x55ef22d82b05

runtime.goexit({})

	runtime/asm_amd64.s:1700 +0x1 fp=0xc00050d7e8 sp=0xc00050d7e0 pc=0x55ef22a91ec1

created by net/http.(*connReader).startBackgroundRead in goroutine 15

	net/http/server.go:686 +0xb6

rax    0x0

rbx    0xb5

rcx    0x7fdf6f373b2c

rdx    0x6

rdi    0xa9

rsi    0xb5

rbp    0x7fdf1e7fb340

rsp    0x7fdf1e7fb300

r8     0x0

r9     0x0

r10    0x8


r11    0x246

r12    0x6

r13    0x7fdec6e20890

r14    0x16

r15    0x7fdec6df6ba0

rip    0x7fdf6f373b2c


rflags 0x246

cs     0x33

fs     0x0

gs     0x0

time=2026-02-14T12:51:23.644Z level=ERROR source=server.go:304 msg="llama runner terminated" error="exit status 2"

time=2026-02-14T12:51:23.644Z level=ERROR source=server.go:1205 msg="do load request" error="Post \"http://127.0.0.1:45707/load\": EOF"

time=2026-02-14T12:51:23.644Z level=ERROR source=server.go:1205 msg="do load request" error="Post \"http://127.0.0.1:45707/load\": dial tcp 127.0.0.1:45707: connect: connection refused"

time=2026-02-14T12:51:23.644Z level=INFO source=sched.go:490 msg="Load failed" model=/root/.ollama/models/blobs/sha256-2b0cf8f17b4c723c27303015383c27ec4bf2d8314bb677d05e920dd70bb0f16b error="model failed to load, this may be due to resource limitations or an internal error, check ollama server logs for details"

[GIN] 2026/02/14 - 12:51:23 | 500 |  816.630011ms |       127.0.0.1 | POST     "/api/embed"
```

### OS

Docker

### GPU

AMD

### CPU

AMD

### Ollama version

0.16.2

**Comment by rick-github** [comment]
Include the part of the log leading up to the crash dump.

**Comment by ndrewpj** [comment]
Logs attached.

[_ollama_logs.txt](https://github.com/user-attachments/files/25315476/_ollama_logs.txt)

**Comment by pkoutsogilas** [comment]
I have the same issue, I can't run even the smallest models.

**OS:**
Fedora 43 (6.18.9-200.fc43.x86_64)

**GPU:**
AMD Radeon 8060S Graphics (allocated fixed 96GB)

**CPU:**
AMD Ryzen AI Max 300 Series

**Ollama version:**
0.16.0

[ollama-service.log](https://github.com/user-attachments/files/25325400/ollama-service.log)

**Comment by rick-github** [comment]
I'm unable to duplicate on an AMD Ryzen Max+ 395.  What's the output of `rocm-smi -a` and `radeontop`?

**Comment by pkoutsogilas** [comment]
@rick-github:

I don't have rocm installed only ollama, this is the output, LM Studio works fine.

Output of rocm-smi -a:

```
============================ ROCm System Management Interface ============================
============================== Version of System Component ===============================
Driver version: 6.18.9-200.fc43.x86_64
==========================================================================================
=========================================== ID ===========================================
Fail to open libdrm_amdgpu.so: libdrm_amdgpu.so: cannot open shared object file: No such file or directory
GPU[0]          : get_name, Failed to load a library
GPU[0]          : Device Name:          N/A
GPU[0]          : Device ID:            0x1586
GPU[0]          : Device Rev:           0xc1
GPU[0]          : Subsystem ID:         0x000a
GPU[0]          : GUID:                 40551
==========================================================================================
======================================= Unique ID ========================================
GPU[0]          : Unique ID: 0x0
==========================================================================================
========================================= VBIOS ==========================================
GPU[0]          : VBIOS version: 113-STRXLGEN-001
==========================================================================================
====================================== Temperature =======================================
GPU[0]          : Temperature (Sensor edge) (C): 40.0
==========================================================================================
=============================== Current clock frequencies ================================
Exception caught: map::at
GPU[0]          : sclk clock level: 1: (881Mhz)
==========================================================================================
=================================== Current Fan Metric ===================================
GPU[0]          : Not supported
==========================================================================================
================================= Show Performance Level =================================
GPU[0]          : Performance Level: auto
==========================================================================================
==================================== OverDrive Level =====================================
GPU[0]          : get_overdrive_level_sclk, Not supported on the given system
==========================================================================================
==================================== OverDrive Level =====================================
GPU[0]          : get_mem_overdrive_level_mclk, Not supported on the given system
==========================================================================================
======================================= Power Cap ========================================
GPU[0]          : get_power_cap, Not supported on the given system
GPU[0]          : Max Graphics Package Power Unsupported
==========================================================================================
================================== Show Power Profiles ===================================
GPU[0]          : get_power_profiles, Not supported on the given system
==========================================================================================
=================================== Power Consumption ====================================
GPU[0]          : Current Socket Graphics Package Power (W): 13.041
==========================================================================================
============================== Supported clock frequencies ===============================
GPU[0]          : Clock [dcefclk] on device [0] exists but EMPTY! Likely driver error!
GPU[0]          : Clock [fclk] on device [0] exists but EMPTY! Likely driver error!
GPU[0]          : Clock [mclk] on device [0] exists but EMPTY! Likely driver error!
GPU[0]          : Supported sclk frequencies on GPU0
GPU[0]          : 0: 600Mhz
GPU[0]          : 1: 881Mhz *
GPU[0]          : 2: 2900Mhz
GPU[0]          : 
GPU[0]          : Clock [socclk] on device [0] exists but EMPTY! Likely driver error!
------------------------------------------------------------------------------------------
==========================================================================================
=================================== % time GPU is busy ===================================
GPU[0]          : GPU use (%): 2
==========================================================================================
=================================== Current Memory Use ===================================
GPU[0]          : GPU Memory Allocated (VRAM%): 1
GPU[0]          : Memory Activity: N/A
GPU[0]          : Not supported on the given system
==========================================================================================
===================================== Memory Vendor ======================================
GPU[0]          : get_vram_vendor, Not supported on the given system
==========================================================================================
================================== PCIe Replay Counter ===================================
GPU[0]          : PCIe Replay Count, Not supported on the given system
==========================================================================================
===================================== Serial Number ======================================
GPU[0]          : get_serial_number, Not supported on the given system
GPU[0]          : Serial Number: N/A
==========================================================================================
===================================== KFD Processes ======================================
No KFD PIDs currently running
==========================================================================================
================================== GPUs Indexed by PID ===================================
No KFD PIDs currently running
==========================================================================================
======================= GPU Memory clock frequencies and voltages ========================
GPU[0]          : OD_SCLK:
GPU[0]          : 0: 600Mhz
GPU[0]          : 1: 2900Mhz
GPU[0]          : OD_MCLK:
GPU[0]          : 0: 0Mhz
GPU[0]          : 1: 0Mhz
==========================================================================================
==================================== Current voltage =====================================
GPU[0]          : Voltage (mV): 0
==========================================================================================
======================================= PCI Bus ID =======================================
GPU[0]          : PCI Bus: 0000:C3:00.0
==========================================================================================
================================== Firmware Information ==================================
GPU[0]          : ASD firmware version:         0x21000104
GPU[0]          : ME firmware version:          32
GPU[0]          : MEC firmware version:         32
GPU[0]          : MES firmware version:         0x00000080
GPU[0]          : MES KIQ firmware version:     0x0000006f
GPU[0]          : PFP firmware version:         46
GPU[0]          : RLC firmware version:         290653446
GPU[0]          : SDMA firmware version:        17
GPU[0]          : SMC firmware version:         10.100.02.00
GPU[0]          : VCN firmware version:         0x0911801b
==========================================================================================
====================================== Product Info ======================================
Fail to open libdrm_amdgpu.so: libdrm_amdgpu.so: cannot open shared object file: No such file or directory
GPU[0]          : get_name, Failed to load a library
GPU[0]          : Card Series:          N/A
GPU[0]          : Card Model:           0x1586
GPU[0]          : Card Vendor:          Advanced Micro Devices, Inc. [AMD/ATI]
GPU[0]          : Card SKU:             STRXLGEN
GPU[0]          : Subsystem ID:         0x000a
GPU[0]          : Device Rev:           0xc1
GPU[0]          : Node ID:              1
GPU[0]          : GUID:                 40551
GPU[0]          : GFX Version:          gfx1151
==========================================================================================
======================================= Pages Info =======================================
GPU[0]          : ras, Not supported on the given system
================================= Show Valid sclk Range ==================================
GPU[0]          : Valid sclk range: 600Mhz - 2900Mhz
==========================================================================================
================================= Show Valid mclk Range ==================================
GPU[0]          : Valid mclk range: 0Mhz - 0Mhz
==========================================================================================
================================ Show Valid voltage Range ================================
WARNING: GPU[0] : Voltage curve regions unsupported.
==========================================================================================
================================== Voltage Curve Points ==================================
WARNING: GPU[0] : Voltage curve Points unsupported.
==========================================================================================
==================================== Consumed Energy =====================================
GPU[0]          : % Energy Counter, Unexpected data received
==========================================================================================
=============================== Current Compute Partition ================================
GPU[0]          : Not supported on the given system
==========================================================================================
================================ Current Memory Partition ================================
GPU[0]          : Not supported on the given system
==========================================================================================
====================================== GPU Metrics =======================================
GPU[0]          : get_gpu_metrics, Unexpected data received
ERROR: GPU[0]   : Failed to retrieve GPU metrics, metric version may not be supported for this device.
==========================================================================================
================================== End of ROCm SMI Log ===================================
```

**Comment by rick-github** [comment]
```
GPU[0]          : Clock [dcefclk] on device [0] exists but EMPTY! Likely driver error!
```
Given the number of driver errors, missing library and unexpected data messages, I suspect a mismatch between driver and device.

**Comment by rick-github** [comment]
Try `sudo dnf install libdrm` or `sudo dnf install libdrm-amdgpu` to install the missing library.

**Comment by pkoutsogilas** [comment]
Here are the responses:

```
sudo dnf install libdrm
Updating and loading repositories:
Repositories loaded.
Package "libdrm-2.4.131-1.fc43.x86_64" is already installed.
Package "libdrm-2.4.131-1.fc43.i686" is already installed.
```

```
sudo dnf install libdrm-amdgpu
Updating and loading repositories:
Repositories loaded.
Failed to resolve the transaction:
No match for argument: libdrm-amdgpu
You can try to add to command line:
  --skip-unavailable to skip unavailable packages

```

After installing libdrm-devel package rocm-smi -a give a lot more info an no warning about missing library, but still cannot run olllama :(

Maybe time to try using a different distro to see if Fedora is problem.

**Comment by rick-github** [comment]
My AMD is running Linux Mint, an Ubuntu variant.  I've had very few issues with it, other than installing kernel 6.11.0 for an infrequent AMD GPU hang issue.

**Comment by pkoutsogilas** [comment]
Thanks for the help, going to see if switching to another distro will solve my issue, I will keep you posted.

**Comment by ndrewpj** [comment]
> I'm unable to duplicate on an AMD Ryzen Max+ 395. What's the output of `rocm-smi -a` and `radeontop`?

 ```
rocm-smi -a


============================ ROCm System Management Interface ============================
WARNING: AMD GPU device(s) is/are in a low-power state. Check power control/runtime_status

============================== Version of System Component ===============================
Driver version: 6.19.0-2-cachyos
==========================================================================================
=========================================== ID ===========================================
GPU[0]          : Device Name:          Radeon 8060S Graphics
GPU[0]          : Device ID:            0x1586
GPU[0]          : Device Rev:           0xc1
GPU[0]          : Subsystem ID:         -0x7fe3
GPU[0]          : GUID:                 4538
==========================================================================================
======================================= Unique ID ========================================
GPU[0]          : Unique ID: 0x0
==========================================================================================
========================================= VBIOS ==========================================
GPU[0]          : VBIOS version: 113-STRXLGEN-001
==========================================================================================
====================================== Temperature =======================================
GPU[0]          : Temperature (Sensor edge) (C): 38.0
==========================================================================================
=============================== Current clock frequencies ================================
Exception caught: map::at
GPU[0]          : mclk clock level: 2: (1000Mhz)
GPU[0]          : sclk clock level: 1: (698Mhz)
==========================================================================================
=================================== Current Fan Metric ===================================
GPU[0]          : Not supported
==========================================================================================
================================= Show Performance Level =================================
GPU[0]          : Performance Level: auto
==========================================================================================
==================================== OverDrive Level =====================================
GPU[0]          : get_overdrive_level_sclk, Not supported on the given system
==========================================================================================
==================================== OverDrive Level =====================================
GPU[0]          : get_mem_overdrive_level_mclk, Not supported on the given system
==========================================================================================
======================================= Power Cap ========================================
GPU[0]          : get_power_cap, Not supported on the given system
GPU[0]          : Max Graphics Package Power Unsupported
==========================================================================================
================================== Show Power Profiles ===================================
GPU[0]          : get_power_profiles, Not supported on the given system
==========================================================================================
=================================== Power Consumption ====================================
GPU[0]          : Current Socket Graphics Package Power (W): 22.085
==========================================================================================
============================== Supported clock frequencies ===============================
GPU[0]          : Clock [dcefclk] on device [0] exists but EMPTY! Likely driver error!
GPU[0]          : Clock [fclk] on device [0] exists but EMPTY! Likely driver error!
GPU[0]          : Supported mclk frequencies on GPU0
GPU[0]          : 0: 400Mhz
GPU[0]          : 1: 800Mhz
GPU[0]          : 2: 1000Mhz *
GPU[0]          : 
GPU[0]          : Supported sclk frequencies on GPU0
GPU[0]          : 0: 600Mhz
GPU[0]          : 1: 698Mhz *
GPU[0]          : 2: 2900Mhz
GPU[0]          : 
GPU[0]          : Clock [socclk] on device [0] exists but EMPTY! Likely driver error!
------------------------------------------------------------------------------------------
==========================================================================================
=================================== % time GPU is busy ===================================
GPU[0]          : GPU use (%): 1
==========================================================================================
=================================== Current Memory Use ===================================
GPU[0]          : GPU Memory Allocated (VRAM%): 94
GPU[0]          : Memory Activity: N/A
GPU[0]          : Not supported on the given system
==========================================================================================
===================================== Memory Vendor ======================================
GPU[0]          : get_vram_vendor, Not supported on the given system
==========================================================================================
================================== PCIe Replay Counter ===================================
GPU[0]          : PCIe Replay Count, Not supported on the given system
==========================================================================================
===================================== Serial Number ======================================
GPU[0]          : get_serial_number, Not supported on the given system
GPU[0]          : Serial Number: N/A
==========================================================================================
===================================== KFD Processes ======================================
No KFD PIDs currently running
==========================================================================================
================================== GPUs Indexed by PID ===================================
No KFD PIDs currently running
==========================================================================================
======================= GPU Memory clock frequencies and voltages ========================
GPU[0]          : OD_SCLK:
GPU[0]          : 0: 600Mhz
GPU[0]          : 1: 2900Mhz
GPU[0]          : OD_MCLK:
GPU[0]          : 0: 18446744073709Mhz
GPU[0]          : 1: 18446744073709Mhz
GPU[0]          : OD_RANGE:
GPU[0]          : SCLK:     600Mhz        2900Mhz
==========================================================================================
==================================== Current voltage =====================================
GPU[0]          : Voltage (mV): 0
==========================================================================================
======================================= PCI Bus ID =======================================
GPU[0]          : PCI Bus: 0000:C5:00.0
==========================================================================================
================================== Firmware Information ==================================
GPU[0]          : ASD firmware version:         0x21000104
GPU[0]          : ME firmware version:          32
GPU[0]          : MEC firmware version:         32
GPU[0]          : MES firmware version:         0x00000080
GPU[0]          : MES KIQ firmware version:     0x0000006f
GPU[0]          : PFP firmware version:         46
GPU[0]          : RLC firmware version:         290653446
GPU[0]          : SDMA firmware version:        17
GPU[0]          : SMC firmware version:         10.100.01.00
GPU[0]          : VCN firmware version:         0x0911801b
==========================================================================================
====================================== Product Info ======================================
GPU[0]          : Card Series:          Radeon 8060S Graphics
GPU[0]          : Card Model:           0x1586
GPU[0]          : Card Vendor:          Advanced Micro Devices, Inc. [AMD/ATI]
GPU[0]          : Card SKU:             STRXLGEN
GPU[0]          : Subsystem ID:         -0x7fe3
GPU[0]          : Device Rev:           0xc1
GPU[0]          : Node ID:              1
GPU[0]          : GUID:                 4538
GPU[0]          : GFX Version:          gfx1151
==========================================================================================
======================================= Pages Info =======================================
GPU[0]          : ras, Not supported on the given system
================================= Show Valid sclk Range ==================================
GPU[0]          : Valid sclk range: 600Mhz - 2900Mhz
==========================================================================================
================================= Show Valid mclk Range ==================================
GPU[0]          : Unable to display mclk range
==========================================================================================
================================ Show Valid voltage Range ================================
WARNING: GPU[0] : Voltage curve regions unsupported.
==========================================================================================
================================== Voltage Curve Points ==================================
==========================================================================================
==================================== Consumed Energy =====================================
GPU[0]          : % Energy Counter, Unexpected data received
==========================================================================================
=============================== Current Compute Partition ================================
GPU[0]          : Not supported on the given system
==========================================================================================
================================ Current Memory Partition ================================
GPU[0]          : Not supported on the given system
==========================================================================================
====================================== GPU Metrics =======================================
GPU[0]          : Failed to retrieve GPU metrics, metric version may not be supported for this device.
==========================================================================================
================================== End of ROCm SMI Log ===================================
```

**Comment by ndrewpj** [comment]
I also tried to download ollama to v.0.14.0 - same issue. So it looks like an incompatibility issue of some kind

**Comment by pkoutsogilas** [comment]
So I tried to following:

* CachyOS, with kernet 6.19, ollama failed to load a model.
* Kubuntu 25.10, with kernetl 6,17, ollama sucessfully was able to load models.

It guess it's an issue with kernels > 6.17 and/or Linux firmware version.

**Comment by ndrewpj** [comment]
> So I tried to following:
> 
> * CachyOS, with kernet 6.19, ollama failed to load a model.
> * Kubuntu 25.10, with kernetl 6,17, ollama sucessfully was able to load models.
> 
> It guess it's an issue with kernels > 6.17 and/or Linux firmware version.

Meanwhile llama.cpp is working fine with 6.19 kernel and ROCm 7.2 

```
❯ ./llama-bench -m ~/models/Apriel-1.5-15b-Thinker-Q6_K.gguf
ggml_cuda_init: found 1 ROCm devices:
  Device 0: Radeon 8060S Graphics, gfx1151 (0x1151), VMM: no, Wave Size: 32
| model                          |       size |     params | backend    | ngl |            test |                  t/s |
| ------------------------------ | ---------: | ---------: | ---------- | --: | --------------: | -------------------: |
| llama 34B Q6_K                 |  11.02 GiB |    14.43 B | ROCm       |  99 |           pp512 |        506.83 ± 1.50 |
| llama 34B Q6_K                 |  11.02 GiB |    14.43 B | ROCm       |  99 |           tg128 |         16.63 ± 0.03 |

build: d5dfc3302 (8069)
❯ uname -a
Linux halo 6.19.0-2-cachyos #1 SMP PREEMPT_DYNAMIC Fri, 13 Feb 2026 16:07:19 +0000 x86_64 GNU/Linux
```

**Comment by pkoutsogilas** [comment]
@rick-github : Is the kernel / linux-firmware something that could be further investigated? You could try to reproduce it with a newer kernel.

**Comment by dougmaitelli** [comment]
I have a similar problem, but not sure if it is related or not.
On Ubuntu 24.04, Ollama runs out-of-the-box (but on CPU only, not able to detect the Strix Halo GPU).

But as soon as I install `linux-oem-24.04c` and boot with kernel `6.17` Ollama breaks and fails to load any model. GPU is then detected but I can't run any models. Booting back to previous kernels works.

Important to note I have rocm installed (`7.2`) and I assume the problem is because Ollama is currently built with `rocm-6`

**Comment by ndrewpj** [comment]
> I have a similar problem, but not sure if it is related or not. On Ubuntu 24.04, Ollama runs out-of-the-box (but on CPU only, not able to detect the Strix Halo GPU).
> 
> But as soon as I install `linux-oem-24.04c` and boot with kernel `6.17` Ollama breaks and fails to load any model. GPU is then detected but I can't run any models. Booting back to previous kernels works.
> 
> Important to note I have rocm installed (`7.2`) and I assume the problem is because Ollama is currently built with `rocm-6`

Your error is most probably caused by buggy linux-firmware package.

**Comment by pkoutsogilas** [comment]
I currently just use llama using a toolbox from https://strix-halo-toolboxes.com/ and that works perfectly. Hopefully in the future ollama will work again.

**Comment by ndrewpj** [comment]
> I currently just use llama using a toolbox from https://strix-halo-toolboxes.com/ and that works perfectly. Hopefully in the future ollama will work again.

I often cannot get llama.cpp engaging LLM tools, Ollama usually works better.... although I like llama.cpp very much, llama-swap too

**Comment by fischerdr** [comment]
I also current have this issue on fedora43 using the docker ollama-rocm
Linux flyyn 6.18.12-200.fc43.x86_64 #1 SMP PREEMPT_DYNAMIC Mon Feb 16 18:58:26 UTC 2026 x86_64 GNU/Linux
amd-gpu-firmware-20260110-1.fc43.noarch
amd-ucode-firmware-20260110-1.fc43.noarch
rocm-core-6.4.4-1.fc43.x86_64 <- in OS but I use dockers with 7.2
I use https://github.com/kyuz0/amd-strix-halo-toolboxes with 2 different X2-evo (1 64gig, 1 128gig)
I have no issues using llama-server/cli and get ~35-48tps
[flyyn-rocminfo.txt](https://github.com/user-attachments/files/25448680/flyyn-rocminfo.txt)
[flyyn-rocm-smi.txt](https://github.com/user-attachments/files/25448738/flyyn-rocm-smi.txt)

edit:
added libdrm-devel.x86_64 and the library error went away but still no luck 

edit 2: downgraded to kernel 6.17.1-300.fc43.x86_64 
and able to run 
podman run -d --replace  --name ollama-rocm  --device=/dev/kfd  --device=/dev/dri  --group-add video  -e HSA_OVERRIDE_GFX_VERSION=11.0.0  -e HIP_VISIBLE_DEVICES=0  -e OLLAMA_FLASH_ATTENTION=true  -v ollama:/root/.ollama  -p 11434:11434   ollama/ollama:rocm

**Comment by ndrewpj** [comment]
yep, on CachyOS kernels 6.18.* and 6.19.* ollama gives the error, tried 6.17 - and it is working. So kernel incompatibility

**Comment by ulope** [comment]
We seem to have the same issue. It also behaves weirdly inconsistent (which suggests maybe user / config error as well).

On nearly identical hardware (Ryzen AI Max 395, but from different manufacturers) on one system only Kernel `6.14.0-1019-oem` works while on another only `6.14.0-1013-oem` does.

**Comment by rick-github** [comment]
AMD [recommends](https://rocm.docs.amd.com/en/latest/how-to/system-optimization/strixhalo.html#required-kernel-version) linux kernel 6.18.4 or newer for AMD Ryzen AI Max series APUs.

**Comment by ndrewpj** [comment]
Ollama runs on kernel 7.x so closing this one.
