### ISSUE TITLE
`CUDA out of memory` when using long prompts and context sizes

### ISSUE THREAD

**Issue by jmorganca** [ollama/ollama#1952]
When using a large context window (via `num_ctx`) and providing a large prompt, Ollama may run out of memory.

**Comment by peperunas** [comment]
To add on this, based on my observation, it looks like Ollama calculates how many layers to offload to the GPU on the model alone - ignoring the overhead that is induced by the custom context size defined in the Modelfile.

In my experience, I can run Mistral by offloading all layers to the GPU. Specifying a bigger context size leads to CUDA being out of memory.

**Comment by coder543** [comment]
@jmorganca I tested the latest pre-release of 0.1.21 using one of my test cases that could consistently cause an OOM, and it seems like this issue is fixed for me. The q3_K_S model still offloads all 33 layers with a 2048 context, so that's great too. (although the q3_K_M only offloads 32 layers, even though they're virtually the same size? I guess the very slight difference is the tipping point.)

I haven't been pushing Mixtral with large contexts as much for the past week or so, but I also haven't seen any OOMs with the latest pre-release. So, I'm optimistic that this issue is fixed.

**Comment by basillicus** [comment]
I've tried the new 0.1.22 version and seems that in my case the OOM is also fixed. It offloads less layers to the GPU. However, I tried (out of curiosity) yarn-mistral:7b-128k, and maybe because of the context window is so large, it does not offload any layer to the GPU, even when I provide exactly the same prompt.

As a reference, I have a 32 GB of RAM laptop with a  crappy GPU (NVIDIA RTX A1000 Laptop) with 4GB of VRAM.

**Comment by medivh-jay** [comment]
I am using olama/ollama: 0.01.27, and CUDA: out of memory will also appear.
The model I am using is gemma:latest
The graphics card is Tesla P4.
The dialogue content is: `我现在需要你来扮演这样的角色, 比如当我对你说 "在下午3点打开客厅空调", 你返回给我一个json文本, 内容是一个类似 AST 逻辑的结构`
No need to try multiple times, directly requesting this conversation after startup will crash

**Comment by 909254** [comment]
me to

**Comment by kennethwork101** [comment]
Is there anyway to recover from this issue other than reboot the computer? 
Restarting the ollama server does not work for me.
I am hoping to find an workaround until this issue is fixed. 
I run into this issue on windows 11 with wsl2 ubuntu and also on  ubuntu 22.04.
The only way for me to recover is to reboot my computer.
Also is there an estimate of when this issue will be fixed?
22.04.1-Ubuntu
Mar 05 07:39:26 kenneth-MS-7E06 ollama[85037]: CUDA error: out of memory
Mar 05 11:34:14 kenneth-MS-7E06 ollama[556803]: CUDA error: out of memory

**Comment by coder543** [comment]
@kennethwork101 rebooting should make no difference as far as ollama is concerned. It sounds like you have other apps that are using VRAM on your GPU, causing ollama's calculations to be incorrect. (I'm not a developer on ollama, just someone who uses it.)

**Comment by thomasWos** [comment]
I experience the same issue.

**Comment by kennethwork101** [comment]
Able to reproduce the issue on:  0.1.28

grep "CPU only" outollama_11.txt 
Mar 06 10:26:15 kenneth-MS-7E06 ollama[2968]: time=2024-03-06T10:26:15.445-08:00 level=INFO source=llm.go:111 msg="not enough vram available, falling back to CPU only"
Mar 06 10:30:19 kenneth-MS-7E06 ollama[2968]: time=2024-03-06T10:30:19.651-08:00 level=INFO source=llm.go:111 msg="not enough vram available, falling back to CPU only"
kenneth@kenneth-MS-7E06:~/ollamalogs$ ollama --version
ollama version is 0.1.28

Wed Mar  6 10:26:12 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.161.07             Driver Version: 535.161.07   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA GeForce RTX 4070 Ti     Off | 00000000:01:00.0  On |                  N/A |
| 30%   51C    P2              58W / 285W |  10989MiB / 12282MiB |     62%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+
                                                                                         
+---------------------------------------------------------------------------------------+
| Processes:                                                                            |
|  GPU   GI   CI        PID   Type   Process name                            GPU Memory |
|        ID   ID                                                             Usage      |
|=======================================================================================|
|    0   N/A  N/A      2968      C   /usr/local/bin/ollama                     10322MiB |
|    0   N/A  N/A      4837      G   /usr/lib/xorg/Xorg                          421MiB |
|    0   N/A  N/A      4988      G   /usr/bin/gnome-shell                         92MiB |
|    0   N/A  N/A    104107      G   ...seed-version=20240305-180126.934000      140MiB |
+---------------------------------------------------------------------------------------+

**Comment by vrubzov1957** [comment]
Some notes about merged #3060 - server becomes unavailable not only with "long promts", but also after some time when normally working with Ollama, with some small promts. After 1 hour or 20-30 newly-topic promts. 
Logs about this issue attached in topic #3060

**Comment by jmorganca** [comment]
This should be much improved as of recent versions of Ollama. Will close for now but please do let me know if this isn't fixed and I can re-open

**Comment by thomasWos** [comment]
Not crashing on my side since couple of versions. Thanks

**Comment by ProjectMoon** [comment]
I'm adding a comment to this, based on advice in #4354. I am still experiencing lots of out of memory errors when it comes to ROCm with higher contexts and default batch size (usually 512). This seems to happen mostly on models that fill the entire VRAM, or would spill a bit over. The crashes often happen without using up the full system RAM (16 GB), so I'd expect things to work, even if they move slowly compared to when the model's in full VRAM.

Comparatively, my laptop that has 48 GB of RAM but no discrete GPU, can run Mixtral 8x7b at ~2 tokens per second fully on CPU and using up 30GB of RAM. But if I load, say, Deepseek Lite 16b at 32k context size, the runner crashes with an out of memory error before even starting to generate text. And it doesn't use up the system RAM either.

Should I post logs? Create a new issue?

**Comment by ProjectMoon** [comment]
Would like to prod this issue again, as I am still seeing this with GLM4 at 65k context size. Loads fine without much context, but has issues loading larger contexts. I even set the context size to 8k o_O. 

Important bits:
* It looks like GPU VRAM hits 100% but then can't spill over into memory for larger contexts. `rocm-smi` shows VRAM going 98%... 99%.. 100%, then crash.
* Forcing GPU layers down to 15 out of 41 and disabling mmap and setting num_batch to 256 for GLM 4 makes VRAM hover around 35%, with 8k context size.
*  Leaving mmap disabled and num_batch at 256, and letting it load all 41 GPU layers into memory uses 69% VRAM.
* Setting num_ctx to 60,000 will still make it try to load all layers into the GPU, and then it crashes because it runs out of VRAM.
* Moving num_gpu down to 30 or even 20 allows it to load more context. But this is only delaying the inevitable. Long enough context will = crash.

Shouldn't ollama be calculating that it needs to load less layers into the GPU in this situation? Like I can adjust it manually, but if ollama receives num_ctx that'll make the model crash, shouldn't it start using system RAM instead?

**Comment by coniuc2d** [comment]
> Would like to prod this issue again, as I am still seeing this with GLM4 at 65k context size. Loads fine without much context, but has issues loading larger contexts. I even set the context size to 8k o_O.
> 
> Important bits:
> 
> * It looks like GPU VRAM hits 100% but then can't spill over into memory for larger contexts. `rocm-smi` shows VRAM going 98%... 99%.. 100%, then crash.
> * Forcing GPU layers down to 15 out of 41 and disabling mmap and setting num_batch to 256 for GLM 4 makes VRAM hover around 35%, with 8k context size.
> * Leaving mmap disabled and num_batch at 256, and letting it load all 41 GPU layers into memory uses 69% VRAM.
> * Setting num_ctx to 60,000 will still make it try to load all layers into the GPU, and then it crashes because it runs out of VRAM.
> * Moving num_gpu down to 30 or even 20 allows it to load more context. But this is only delaying the inevitable. Long enough context will = crash.
> 
> Shouldn't ollama be calculating that it needs to load less layers into the GPU in this situation? Like I can adjust it manually, but if ollama receives num_ctx that'll make the model crash, shouldn't it start using system RAM instead?

If i may add to this, on windows it is working as intended. 
1)Windows rx7800GRE(16GB) 100%GPU: llama3.1q8 loaded with num_ctx 16000, ollama swallowed vram and expanded to ram.
2)Ubuntu 22.04 rx5700xt (8GB)  13%CPU/87%GPU: llama3.1q8 gives oom when setting up context bigger than remaining 13% of gpu vram.

**Comment by svalaskevicius** [comment]
still very much happening...

using `ollama-rocm-git 0.4.5.git+940e6277-1`, on arch linux, via aur
see the log here: https://pastebin.com/YaUnz5Sg

setting n_ctx to 8k works fine

**Comment by VasiliyMooduckovich** [comment]
> setting n_ctx to 8k works fine

how do you set it btw? i tried [this](https://github.com/ollama/ollama/issues/5902) but when the model loads i can still see that this string `llm_load_print_meta: n_ctx_train = 32768` is still has 32k context instead of 8192

**Comment by coniuc2d** [comment]
> > setting n_ctx to 8k works fine
> 
> how do you set it btw? i tried [this](https://github.com/ollama/ollama/issues/5902) but when the model loads i can still see that this string `llm_load_print_meta: n_ctx_train = 32768` is still has 32k context instead of 8192 and it still crashes, but if i set up 32k context length in sillytavern it works but i guess it starting to offload to ram and becomes unresponsive

When i set context to 32k tokens, llama 7b q4 crashes on 32Gb vram system. Pagefault. All done in cli debian 12. I have two radeon 7600xt  cards 16gb each. One would think extra 20+gb is enough.
