### ISSUE TITLE
ggml-cuda.cu: "8792: !" CUDA error

### ISSUE THREAD

**Issue by hsiehgeorge** [ollama/ollama#2029]
Hi,

We have a Dell XE8545 server with 4 * A100 GPU cards. When we are running "ollama run mixtral", it was fine but few minutes later, it's halt. I got multiple errors from the log:

1. ggml-cuda.cu: "8792: !" CUDA error
2. ollama.service: State 'stop-sigterm' timed out. Killing.

I tried to kill ollama process but can't (ollama.service: Processes still around after SIGKILL. Ignoring.), the only solution is reboot it but the same situation happens again.

Please advise how to make it works smoothly.

Thank you.

**Comment by dhiltgen** [comment]
@hsiehgeorge can you share the server log?

https://github.com/ollama/ollama/blob/main/docs/troubleshooting.md#how-to-troubleshoot-issues

**Comment by pdevine** [comment]
@hsiehgeorge and @Ca-ressemble-a-du-fake are you still encountering the issue?

**Comment by hsiehgeorge** [comment]
@dhiltgen @pdevine the problem resolved but it's due to NVLink board hardware issue, after we replace NVLink board then it's fine. Thanks for following up.

**Comment by Ca-ressemble-a-du-fake** [comment]
@pdevine thanks for your following up.  I was about to write that the problem persists but I tried and it seems that it works without requiring a reboot. That's great news ! I'll check again to confirm! I am currently using 0.1.28 version.

**Comment by Ca-ressemble-a-du-fake** [comment]
@pdevine Sadly I still have to reboot when the computer wakes up from suspended state.  That behaviour is OK for me for now (this is not my main computer). When I have time to dig deeper into that behaviour I'll give more details.

**Comment by pdevine** [comment]
@Ca-ressemble-a-du-fake I think this is almost certainly a different issue than the original one. Would you be able to create a new issue and include the logs? Preferably w/ the `OLLAMA_DEBUG=1` flag set.
