### ISSUE TITLE
[Documentation] CUDA toolkit install is REQUIRED for AMD GPUs

### ISSUE THREAD

**Issue by scabros** [ollama/ollama#2503]
Hi! Congrats for the great project!

We were trying to test ollama with AMD GPU support and we struggled a bit because in the install guides are not clear that CUDA libraries are required for ollama (or llama.cpp) to work properly even with team red GPUs.

The error when running ollama run llama2 was (leaving here for reference):
...
llama_new_context_with_model: n_ctx      = 2048
llama_new_context_with_model: freq_base  = 10000.0
llama_new_context_with_model: freq_scale = 1
llama_kv_cache_init:      ROCm0 KV buffer size =  1024.00 MiB
llama_new_context_with_model: KV self size  = 1024.00 MiB, K (f16):  512.00 MiB, V (f16):  512.00 MiB
llama_new_context_with_model:  ROCm_Host input buffer size   =    13.01 MiB
llama_new_context_with_model:      ROCm0 compute buffer size =   164.00 MiB
llama_new_context_with_model:  ROCm_Host compute buffer size =     8.00 MiB
llama_new_context_with_model: graph splits (measure): 3
**CUDA error: shared object initialization failed
  current device: 0, in function ggml_cuda_op_flatten at /home/devel/ollama/llm/llama.cpp/ggml-cuda.cu:9208
  hipGetLastError()
loading library /tmp/ollama3700311510/rocm_v6/libext_server.so
GGML_ASSERT: /home/devel/ollama/llm/llama.cpp/ggml-cuda.cu:241: !"CUDA error"**
[New LWP 4411]
[New LWP 4412]
[New LWP 4413]
[New LWP 4414]
[New LWP 4415]
...

after we installed the cuda libraries as per the instructions [HERE](https://developer.nvidia.com/cuda-downloads) the problem went away.

we also faced problems with ROCm 6.0.2 support for different gpu models (in our case it is a RX 5700 XT, arch gfx1010), the current binary packages doesn't contain TensileLibrary.dat (that somehow "maps" the kernels objects to use with different GPUs).

We had this error:

time=2024-02-09T17:05:38.481Z level=INFO source=dyn_ext_server.go:90 msg="Loading Dynamic llm server: /tmp/ollama3752973675/rocm_v6/libext_server.so"
time=2024-02-09T17:05:38.481Z level=INFO source=dyn_ext_server.go:145 msg="Initializing llama server"
**rocBLAS error: Cannot read /opt/rocm/lib/rocblas/library/TensileLibrary.dat: Illegal seek for GPU arch : gfx1010**
free(): invalid pointer
SIGABRT: abort
PC=0x7f4bb13739fc m=3 sigcode=18446744073709551610

so I downloaded full rocm source and tried to build again, just to get the right command for compiling TensileLibrary.dat :

this was the command that cmake uses: 
'/home/devel/rocBLAS/build/virtualenv/lib/python3.10/site-packages/Tensile/bin/TensileCreateLibrary' '--merge-files' '--separate-architectures' '--lazy-library-loading' '--no-short-file-names' '--library-print-debug' '--code-object-version=default' '--cxx-compiler=hipcc' '--jobs=14' '--library-format=msgpack' '--architecture=gfx1012' '/home/devel/rocBLAS/library/src/blas3/Tensile/Logic/asm_full' '/home/devel/rocBLAS/build/Tensile' 'HIP'

this is the command I used to generate a new TensileLibrary.dat:
'/home/devel/rocBLAS/build/virtualenv/lib/python3.10/site-packages/Tensile/bin/TensileCreateLibrary' '--merge-files' '--no-short-file-names' '--library-print-debug' '--code-object-version=default' '--cxx-compiler=hipcc' '--jobs=14' '--library-format=msgpack' '/home/devel/rocBLAS/library/src/blas3/Tensile/Logic/asm_full' '/home/devel/rocBLAS/build/Tensile' 'HIP'

(i removed '--separate-architectures' '--lazy-library-loading'  as per instructions [in this bug](https://github.com/ROCm/Tensile/issues/1757) )

Hope this helps to others! Thanks again!

**Comment by dhiltgen** [comment]
Unfortunately, the official ROCm builds from AMD don't currently support the RX 5700 XT.

With the new release 0.1.29, we'll now detect this incompatibility, and gracefully fall back to CPU mode and log some information in the server log about what happened.   There is a facility to override this manually with `HSA_OVERRIDE_GFX_VERSION` however, I'm not sure what supported gfx target will work for this GPU.

**Comment by jpmcb** [comment]
It may be a good idea to keep an eye on `ROCm/Tensile` now that `gfx1010` support has merged: https://github.com/ROCm/Tensile/pull/1897 which, from my understanding, once they cut a new version of that driver, it should flow into the main `ROCm/ROCm` build.

So, depending on how ollama detects GPU support, it may just start working.

---

I also ran into this and would love support of slightly older Radeon RX 5600:

```
❯ sudo ollama serve

...

time=2024-03-15T14:15:29.915-06:00 level=INFO source=gpu.go:77 msg="Detecting GPU type"
time=2024-03-15T14:15:29.915-06:00 level=INFO source=gpu.go:191 msg="Searching for GPU management library libnvidia-ml.so"
time=2024-03-15T14:15:29.927-06:00 level=INFO source=gpu.go:237 msg="Discovered GPU libraries: []"
time=2024-03-15T14:15:29.927-06:00 level=INFO source=cpu_common.go:11 msg="CPU has AVX2"
time=2024-03-15T14:15:29.927-06:00 level=WARN source=amd_linux.go:53 msg="ollama recommends running the https://www.amd.com/en/support/linux-drivers: amdgpu version file missing: /sys/module/amdgpu/version stat /sys/module/amdgpu/version: no such file or directory"
time=2024-03-15T14:15:29.928-06:00 level=INFO source=amd_linux.go:88 msg="detected amdgpu versions [gfx1010]"
time=2024-03-15T14:15:29.943-06:00 level=WARN source=amd_linux.go:114 msg="amdgpu [0] gfx1010 is not supported by /tmp/ollama402405963/rocm [gfx1030 gfx1100 gfx1101 gfx1102 gfx900 gfx906 gfx908 gfx90a gfx940 gfx941 gfx942]"
time=2024-03-15T14:15:29.943-06:00 level=WARN source=amd_linux.go:116 msg="See https://github.com/ollama/ollama/blob/main/docs/troubleshooting.md for HSA_OVERRIDE_GFX_VERSION usage"
time=2024-03-15T14:15:29.943-06:00 level=INFO source=amd_linux.go:127 msg="all detected amdgpus are skipped, falling back to CPU"
time=2024-03-15T14:15:29.943-06:00 level=INFO source=routes.go:1133 msg="no GPU detected"
```

but thanks for building in detection of AMD gpu families that aren't supported: saved me lots of useless debugging time 👀 happy to help validate any patches: feel free to @ me

**Comment by aionik-me** [comment]
The gfx1010 should work, but you'll need to manually override what's allowed and in some cases map it to closest supported type. I suggest you try nixos flake of ollama here: [https://github.com/abysssol/ollama-flake]

Only modifications that you may need for your "unsupported" gpu on nixos:
- You may need to map rocblas to support your gpu: `sudo ln -s /nix/store/nwij51jpnczrf8qc0zhdnd4rhxdwsgsj-rocblas-5.7.1/lib/rocblas/library/TensileLibrary_lazy_gfx1030.dat /nix/store/nwij51jpnczrf8qc0zhdnd4rhxdwsgsj-rocblas-5.7.1/lib/rocblas/library/TensileLibrary.dat`
- You may also need to  pass or export this type of env variable: HSA_OVERRIDE_GFX_VERSION: "10.3.0"
- Match these to your closest GPU capabilities. 

netdata is a good way to monitor remote, dig into specific periods of time, isolate when GPU is being used, or balanced, etc.

Please let me know if you have questions or feedkback.

**Comment by skidunion** [comment]
> Please let me know if you have questions or feedkback

@aionik-me could you provide some more insight on what that means? I followed the previous steps on Windows, but I just get gibberish when I try to prompt the model with anything. With CPU compute it works fine.

![image](https://github.com/ollama/ollama/assets/34306421/9cb24345-9d23-4ed6-8c1e-df7e752f2599)

```
2024/05/25 16:52:11 routes.go:1008: INFO server config env="map[OLLAMA_DEBUG:false OLLAMA_LLM_LIBRARY: OLLAMA_MAX_LOADED_MODELS:1 OLLAMA_MAX_QUEUE:512 OLLAMA_MAX_VRAM:0 OLLAMA_NOPRUNE:false OLLAMA_NUM_PARALLEL:1 OLLAMA_ORIGINS:[http://localhost https://localhost http://localhost:* https://localhost:* http://127.0.0.1 https://127.0.0.1 http://127.0.0.1:* https://127.0.0.1:* http://0.0.0.0 https://0.0.0.0 http://0.0.0.0:* https://0.0.0.0:*] OLLAMA_RUNNERS_DIR:C:\\Users\\<user>\\AppData\\Local\\Programs\\Ollama\\ollama_runners OLLAMA_TMPDIR:]"
time=2024-05-25T16:52:11.474+03:00 level=INFO source=images.go:704 msg="total blobs: 20"
time=2024-05-25T16:52:11.475+03:00 level=INFO source=images.go:711 msg="total unused blobs removed: 0"
time=2024-05-25T16:52:11.476+03:00 level=INFO source=routes.go:1054 msg="Listening on 192.168.0.100:11434 (version 0.1.38)"
time=2024-05-25T16:52:11.476+03:00 level=INFO source=payload.go:44 msg="Dynamic LLM libraries [rocm_v5.7 cpu cpu_avx cpu_avx2 cuda_v11.3]"
time=2024-05-25T16:52:11.510+03:00 level=INFO source=amd_windows.go:63 msg="skipping rocm gfx compatibility check" HSA_OVERRIDE_GFX_VERSION=10.3.0
time=2024-05-25T16:52:11.861+03:00 level=INFO source=types.go:71 msg="inference compute" id=0 library=rocm compute=gfx1010:xnack- driver=0.0 name="AMD Radeon RX 5700 XT" total="8.0 GiB" available="7.9 GiB"
time=2024-05-25T16:52:18.161+03:00 level=INFO source=amd_windows.go:63 msg="skipping rocm gfx compatibility check" HSA_OVERRIDE_GFX_VERSION=10.3.0
time=2024-05-25T16:52:20.404+03:00 level=INFO source=memory.go:133 msg="offload to gpu" layers.requested=-1 layers.real=33 memory.available="7.9 GiB" memory.required.full="5.4 GiB" memory.required.partial="5.4 GiB" memory.required.kv="512.0 MiB" memory.weights.total="4.1 GiB" memory.weights.repeating="3.7 GiB" memory.weights.nonrepeating="411.0 MiB" memory.graph.full="296.0 MiB" memory.graph.partial="677.5 MiB"
time=2024-05-25T16:52:20.404+03:00 level=INFO source=memory.go:133 msg="offload to gpu" layers.requested=-1 layers.real=33 memory.available="7.9 GiB" memory.required.full="5.4 GiB" memory.required.partial="5.4 GiB" memory.required.kv="512.0 MiB" memory.weights.total="4.1 GiB" memory.weights.repeating="3.7 GiB" memory.weights.nonrepeating="411.0 MiB" memory.graph.full="296.0 MiB" memory.graph.partial="677.5 MiB"
time=2024-05-25T16:52:20.409+03:00 level=INFO source=server.go:320 msg="starting llama server" cmd="C:\\Users\\<user>\\AppData\\Local\\Programs\\Ollama\\ollama_runners\\rocm_v5.7\\ollama_llama_server.exe --model C:\\Users\\<user>\\.ollama\\models\\blobs\\sha256-6a0746a1ec1aef3e7ec53868f220ff6e389f6f8ef87a01d77c96807de94ca2aa --ctx-size 4096 --batch-size 512 --embedding --log-disable --n-gpu-layers 33 --parallel 1 --port 49782"
time=2024-05-25T16:52:20.412+03:00 level=INFO source=sched.go:338 msg="loaded runners" count=1
time=2024-05-25T16:52:20.412+03:00 level=INFO source=server.go:504 msg="waiting for llama runner to start responding"
time=2024-05-25T16:52:20.412+03:00 level=INFO source=server.go:540 msg="waiting for server to become available" status="llm server error"
INFO [wmain] build info | build=2770 commit="952d03d" tid="9456" timestamp=1716645140
INFO [wmain] system info | n_threads=8 n_threads_batch=-1 system_info="AVX = 1 | AVX_VNNI = 0 | AVX2 = 0 | AVX512 = 0 | AVX512_VBMI = 0 | AVX512_VNNI = 0 | FMA = 1 | NEON = 0 | ARM_FMA = 0 | F16C = 1 | FP16_VA = 0 | WASM_SIMD = 0 | BLAS = 1 | SSE3 = 1 | SSSE3 = 1 | VSX = 0 | MATMUL_INT8 = 0 | LLAMAFILE = 1 | " tid="9456" timestamp=1716645140 total_threads=16
INFO [wmain] HTTP server listening | hostname="127.0.0.1" n_threads_http="15" port="49782" tid="9456" timestamp=1716645140
llama_model_loader: loaded meta data with 22 key-value pairs and 291 tensors from C:\Users\<user>\.ollama\models\blobs\sha256-6a0746a1ec1aef3e7ec53868f220ff6e389f6f8ef87a01d77c96807de94ca2aa (version GGUF V3 (latest))
llama_model_loader: Dumping metadata keys/values. Note: KV overrides do not apply in this output.
llama_model_loader: - kv   0:                       general.architecture str              = llama
llama_model_loader: - kv   1:                               general.name str              = Meta-Llama-3-8B-Instruct
llama_model_loader: - kv   2:                          llama.block_count u32              = 32
llama_model_loader: - kv   3:                       llama.context_length u32              = 8192
llama_model_loader: - kv   4:                     llama.embedding_length u32              = 4096
llama_model_loader: - kv   5:                  llama.feed_forward_length u32              = 14336
llama_model_loader: - kv   6:                 llama.attention.head_count u32              = 32
llama_model_loader: - kv   7:              llama.attention.head_count_kv u32              = 8
llama_model_loader: - kv   8:                       llama.rope.freq_base f32              = 500000.000000
llama_model_loader: - kv   9:     llama.attention.layer_norm_rms_epsilon f32              = 0.000010
llama_model_loader: - kv  10:                          general.file_type u32              = 2
llama_model_loader: - kv  11:                           llama.vocab_size u32              = 128256
llama_model_loader: - kv  12:                 llama.rope.dimension_count u32              = 128
llama_model_loader: - kv  13:                       tokenizer.ggml.model str              = gpt2
llama_model_loader: - kv  14:                         tokenizer.ggml.pre str              = llama-bpe
llama_model_loader: - kv  15:                      tokenizer.ggml.tokens arr[str,128256]  = ["!", "\"", "#", "$", "%", "&", "'", ...
llama_model_loader: - kv  16:                  tokenizer.ggml.token_type arr[i32,128256]  = [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...
llama_model_loader: - kv  17:                      tokenizer.ggml.merges arr[str,280147]  = ["Ġ Ġ", "Ġ ĠĠĠ", "ĠĠ ĠĠ", "...
llama_model_loader: - kv  18:                tokenizer.ggml.bos_token_id u32              = 128000
llama_model_loader: - kv  19:                tokenizer.ggml.eos_token_id u32              = 128009
llama_model_loader: - kv  20:                    tokenizer.chat_template str              = {% set loop_messages = messages %}{% ...
llama_model_loader: - kv  21:               general.quantization_version u32              = 2
llama_model_loader: - type  f32:   65 tensors
llama_model_loader: - type q4_0:  225 tensors
llama_model_loader: - type q6_K:    1 tensors
time=2024-05-25T16:52:20.663+03:00 level=INFO source=server.go:540 msg="waiting for server to become available" status="llm server loading model"
llm_load_vocab: special tokens definition check successful ( 256/128256 ).
llm_load_print_meta: format           = GGUF V3 (latest)
llm_load_print_meta: arch             = llama
llm_load_print_meta: vocab type       = BPE
llm_load_print_meta: n_vocab          = 128256
llm_load_print_meta: n_merges         = 280147
llm_load_print_meta: n_ctx_train      = 8192
llm_load_print_meta: n_embd           = 4096
llm_load_print_meta: n_head           = 32
llm_load_print_meta: n_head_kv        = 8
llm_load_print_meta: n_layer          = 32
llm_load_print_meta: n_rot            = 128
llm_load_print_meta: n_embd_head_k    = 128
llm_load_print_meta: n_embd_head_v    = 128
llm_load_print_meta: n_gqa            = 4
llm_load_print_meta: n_embd_k_gqa     = 1024
llm_load_print_meta: n_embd_v_gqa     = 1024
llm_load_print_meta: f_norm_eps       = 0.0e+00
llm_load_print_meta: f_norm_rms_eps   = 1.0e-05
llm_load_print_meta: f_clamp_kqv      = 0.0e+00
llm_load_print_meta: f_max_alibi_bias = 0.0e+00
llm_load_print_meta: f_logit_scale    = 0.0e+00
llm_load_print_meta: n_ff             = 14336
llm_load_print_meta: n_expert         = 0
llm_load_print_meta: n_expert_used    = 0
llm_load_print_meta: causal attn      = 1
llm_load_print_meta: pooling type     = 0
llm_load_print_meta: rope type        = 0
llm_load_print_meta: rope scaling     = linear
llm_load_print_meta: freq_base_train  = 500000.0
llm_load_print_meta: freq_scale_train = 1
llm_load_print_meta: n_yarn_orig_ctx  = 8192
llm_load_print_meta: rope_finetuned   = unknown
llm_load_print_meta: ssm_d_conv       = 0
llm_load_print_meta: ssm_d_inner      = 0
llm_load_print_meta: ssm_d_state      = 0
llm_load_print_meta: ssm_dt_rank      = 0
llm_load_print_meta: model type       = 8B
llm_load_print_meta: model ftype      = Q4_0
llm_load_print_meta: model params     = 8.03 B
llm_load_print_meta: model size       = 4.33 GiB (4.64 BPW)
llm_load_print_meta: general.name     = Meta-Llama-3-8B-Instruct
llm_load_print_meta: BOS token        = 128000 '<|begin_of_text|>'
llm_load_print_meta: EOS token        = 128009 '<|eot_id|>'
llm_load_print_meta: LF token         = 128 'Ä'
llm_load_print_meta: EOT token        = 128009 '<|eot_id|>'

rocBLAS warning: No paths matched C:\Users\<user>\AppData\Local\Programs\Ollama\rocm\\rocblas\library\*gfx1010*co. Make sure that ROCBLAS_TENSILE_LIBPATH is set correctly.
ggml_cuda_init: GGML_CUDA_FORCE_MMQ:   no
ggml_cuda_init: CUDA_USE_TENSOR_CORES: yes
ggml_cuda_init: found 1 ROCm devices:
  Device 0: AMD Radeon RX 5700 XT, compute capability 10.1, VMM: no
llm_load_tensors: ggml ctx size =    0.30 MiB
llm_load_tensors: offloading 32 repeating layers to GPU
llm_load_tensors: offloading non-repeating layers to GPU
llm_load_tensors: offloaded 33/33 layers to GPU
llm_load_tensors:      ROCm0 buffer size =  4155.99 MiB
llm_load_tensors:        CPU buffer size =   281.81 MiB
......................................................................................
llama_new_context_with_model: n_ctx      = 4096
llama_new_context_with_model: n_batch    = 512
llama_new_context_with_model: n_ubatch   = 512
llama_new_context_with_model: freq_base  = 500000.0
llama_new_context_with_model: freq_scale = 1
llama_kv_cache_init:      ROCm0 KV buffer size =   512.00 MiB
llama_new_context_with_model: KV self size  =  512.00 MiB, K (f16):  256.00 MiB, V (f16):  256.00 MiB
llama_new_context_with_model:  ROCm_Host  output buffer size =     0.50 MiB
llama_new_context_with_model:      ROCm0 compute buffer size =   296.00 MiB
llama_new_context_with_model:  ROCm_Host compute buffer size =    16.01 MiB
llama_new_context_with_model: graph nodes  = 1030
llama_new_context_with_model: graph splits = 2
INFO [wmain] model loaded | tid="9456" timestamp=1716645143
time=2024-05-25T16:52:23.676+03:00 level=INFO source=server.go:545 msg="llama runner started in 3.26 seconds"
[GIN] 2024/05/25 - 16:52:31 | 200 |   13.7334707s |   192.168.0.106 | POST     "/api/chat"
```

**Comment by Zippy-boy** [comment]
Iv been trying to do the same with my RX5700. 
I noticed this when trying to serve:
`time=2024-06-08T13:06:06.875Z` level=WARN source=amd_linux.go:296 msg="amdgpu is not supported" gpu=0 gpu_type=gfx1010 library=/opt/rocm/lib supported_types="[gfx1030 gfx1100 gfx1101 gfx1102 gfx900 gfx906 gfx908 gfx90a gfx940 gfx941 `gfx942]"`

Im pretty sure that the GFX1010 is supported my ROCm now, so is there an amdgpu supported_type file that i can add the gfx1010 to. And then see if it works with it? Im not very knowledgeable in this so this may be stupid :/

**Comment by b0o** [comment]
I was trying to run `HSA_OVERRIDE_GFX_VERSION="10.1.0" ollama serve` and getting `Error: llama runner process has terminated: signal: aborted (core dumped) error:Cannot read /opt/rocm/lib/rocblas/library/TensileLibrary.dat: Illegal seek for GPU arch : gfx1010`.

I saw a lot of suggestions to use `HSA_OVERRIDE_GFX_VERSION="10.3.0"` but that caused my GPU to crash.

However, I tried symlinking `TensileLibrary_lazy_gfx1010.dat` to `TensileLibrary_lazy_gfx1030.dat`: `sudo ln -s /opt/rocm/lib/rocblas/library/TensileLibrary_lazy_gfx{1030,1010}.dat`, and now it seems to be working!

Running `HSA_OVERRIDE_GFX_VERSION="10.1.0" ollama serve` and then running a model like `ollama run mistral` successfully loads and runs the model on my GPU.

**Comment by thednp** [comment]
Any news on this?

**Comment by kdta91** [comment]
> I was trying to run `HSA_OVERRIDE_GFX_VERSION="10.1.0" ollama serve` and getting `Error: llama runner process has terminated: signal: aborted (core dumped) error:Cannot read /opt/rocm/lib/rocblas/library/TensileLibrary.dat: Illegal seek for GPU arch : gfx1010`.
> 
> I saw a lot of suggestions to use `HSA_OVERRIDE_GFX_VERSION="10.3.0"` but that caused my GPU to crash.
> 
> However, I tried symlinking `TensileLibrary_lazy_gfx1010.dat` to `TensileLibrary_lazy_gfx1030.dat`: `sudo ln -s /opt/rocm/lib/rocblas/library/TensileLibrary_lazy_gfx{1030,1010}.dat`, and now it seems to be working!
> 
> Running `HSA_OVERRIDE_GFX_VERSION="10.1.0" ollama serve` and then running a model like `ollama run mistral` successfully loads and runs the model on my GPU.

This works for me in my case. Using RX 5600 XT, however, the VRAM usage is at constant >=5GB.

**Comment by murlakatamenka** [comment]
> I was trying to run `HSA_OVERRIDE_GFX_VERSION="10.1.0" ollama serve` and getting `Error: llama runner process has terminated: signal: aborted (core dumped) error:Cannot read /opt/rocm/lib/rocblas/library/TensileLibrary.dat: Illegal seek for GPU arch : gfx1010`.
> 
> I saw a lot of suggestions to use `HSA_OVERRIDE_GFX_VERSION="10.3.0"` but that caused my GPU to crash.
> 
> However, I tried symlinking `TensileLibrary_lazy_gfx1010.dat` to `TensileLibrary_lazy_gfx1030.dat`: `sudo ln -s /opt/rocm/lib/rocblas/library/TensileLibrary_lazy_gfx{1030,1010}.dat`, and now it seems to be working!
> 
> Running `HSA_OVERRIDE_GFX_VERSION="10.1.0" ollama serve` and then running a model like `ollama run mistral` successfully loads and runs the model on my GPU.

Do you run Arch with `ollama-rocm` package?

**Comment by b0o** [comment]
Yes, I'm on Arch, and I'm using `ollama-rocm-git` but IIRC `ollama-rocm` worked as well.

**Comment by d8rt8v** [comment]
Yep, confirming this on win 11. 

> guy has it working here [#2453 (comment)](https://github.com/ollama/ollama/issues/2453#issuecomment-2236193832)


1.  Install ollama prebuild binary installer from here https://github.com/likelovewant/ollama-for-amd/releases 
2.  Download  `rocblas.for.gfx1010-.xnack-.with.building.guide.7z` from https://github.com/likelovewant/ROCmLibs-for-gfx1103-AMD780M-APU/releases/tag/v0.5.7.
3.  Go to `C:\Users\User\AppData\Local\Programs\Ollama\rocm` and copy-replace `rocblas.dll` alongside `library` folder from downloaded zip.

**Comment by thednp** [comment]
> Yep, confirming this on win 11.
> 
> > guy has it working here [#2453 (comment)](https://github.com/ollama/ollama/issues/2453#issuecomment-2236193832)
> 
> 1. Install ollama prebuild binary installer from here https://github.com/likelovewant/ollama-for-amd/releases
> 2. Download  `rocblas.for.gfx1010-.xnack-.with.building.guide.7z` from https://github.com/likelovewant/ROCmLibs-for-gfx1103-AMD780M-APU/releases/tag/v0.5.7.
> 3. Go to `C:\Users\User\AppData\Local\Programs\Ollama\rocm` and copy-replace `rocblas.dll` alongside `library` folder from downloaded zip.

Have anyone recreated this in Linux by any chance?

**Comment by Elektroney** [comment]
> 3\.

Can't confirm this on win 10.

**Comment by JeremyLG** [comment]
I can confirm it works on Win10 for gfx1010 on my side.
Very very cool, thanks a lot

**Comment by d8rt8v** [comment]
Have you installed [AMD HIP 5.7.1](https://www.amd.com/en/developer/resources/rocm-hub/hip-sdk.html) previously? 


> Doesn't work on win 10 with gfx1010.
> 
> > Yep, confirming this on win 11.
> > > guy has it working here [#2453 (comment)](https://github.com/ollama/ollama/issues/2453#issuecomment-2236193832)
> > 
> > 
> > 
> > 1. Install ollama prebuild binary installer from here https://github.com/likelovewant/ollama-for-amd/releases
> > 2. Download  `rocblas.for.gfx1010-.xnack-.with.building.guide.7z` from https://github.com/likelovewant/ROCmLibs-for-gfx1103-AMD780M-APU/releases/tag/v0.5.7.
> > 3. Go to `C:\Users\User\AppData\Local\Programs\Ollama\rocm` and copy-replace `rocblas.dll` alongside `library` folder from downloaded zip.

**Comment by Elektroney** [comment]
Yes, i did fully follow the instructions
the logs still tell me 'amdgpu unsupported'
AMD HIP seems to have installed succesfully

**Comment by ptitjes** [comment]
Did someone try this on Linux?

**Comment by justinlovinger** [comment]
Note, this works out of the box on the latest NixOS:

```nix
services.ollama = {
  enable = true;
  acceleration = "rocm";
  rocmOverrideGfx = "10.1.0";
};
```

**Comment by thednp** [comment]
Anyone have RX 5700XT running on a debian based distro?

**Comment by tecnomanu** [comment]
> > Yep, confirming this on win 11.
> > > guy has it working here [#2453 (comment)](https://github.com/ollama/ollama/issues/2453#issuecomment-2236193832)
> > 
> > 
> > 
> > 1. Install ollama prebuild binary installer from here https://github.com/likelovewant/ollama-for-amd/releases
> > 2. Download  `rocblas.for.gfx1010-.xnack-.with.building.guide.7z` from https://github.com/likelovewant/ROCmLibs-for-gfx1103-AMD780M-APU/releases/tag/v0.5.7.
> > 3. Go to `C:\Users\User\AppData\Local\Programs\Ollama\rocm` and copy-replace `rocblas.dll` alongside `library` folder from downloaded zip.
> 
> Have anyone recreated this in Linux by any chance?
> rocblas

Hi! i can reply in ubuntu v24. 

The difference here is that you need to create the symlinking with the library inside the ollama directory instead of the rocm opt folder. 
For be clare:
Instead of ```sudo ln -s /opt/rocm/lib/rocblas/library/TensileLibrary_lazy_gfx{1030,1010}.dat``` i do this here: ```sudo ln -s /usr/local/lib/ollama/rocblas/library/TensileLibrary_lazy_gfx{1030,1010}.dat```

Check the error return by Ollama when you are running the server and fail, there is the correct folder where is the TensileLibrary.dat file.

See you and thanks @b0o !!!! ❤️🙌

**Comment by b0o** [comment]
No problem. By the way, it seems this workaround is unnecessary as of opencl-amd-dev 6.2.1.

**Comment by tecnomanu** [comment]
@b0o i need to do this with the last version installed, because in Ubuntu, Ollama use the own libraries, maybe ollama need to update the libraries. I hope they will be careful because with this hack already works.

**Comment by arg0x** [comment]
I'm using RX 5600M 6GB which seems to have the same arch `gfx1010`
```shell
$amdgpu-arch
gfx1010
gfx90c
```
I've installed ollama-rocm using aur, set `sudo ln -s /opt/rocm/lib/rocblas/library/TensileLibrary_lazy_gfx{1030,1010}.dat`, tried to run with both `HSA_OVERRIDE_GFX_VERSION="10.1.0" ollama serve` and `HSA_OVERRIDE_GFX_VERSION="10.3.0" ollama serve`

I'm getting this error:
```shell
$ ollama run phi3.5
Error: llama runner process has terminated: CUDA error: shared object initialization failed
  current device: 0, in function ggml_cuda_compute_forward at /build/ollama-rocm/src/ollama/llm/llama.cpp/ggml/src/ggml-cuda.cu:2326
  err
/build/ollama-rocm/src/ollama/llm/llama.cpp/ggml/src/ggml-cuda.cu:102: CUDA error
```

ollama serve output: https://pastebin.com/b6nSbHUa

**Comment by fabdacab** [comment]
> > > Yep, confirming this on win 11.
> > > > guy has it working here [#2453 (comment)](https://github.com/ollama/ollama/issues/2453#issuecomment-2236193832)
> > > 
> > > 
> > > 
> > > 1. Install ollama prebuild binary installer from here https://github.com/likelovewant/ollama-for-amd/releases
> > > 2. Download  `rocblas.for.gfx1010-.xnack-.with.building.guide.7z` from https://github.com/likelovewant/ROCmLibs-for-gfx1103-AMD780M-APU/releases/tag/v0.5.7.
> > > 3. Go to `C:\Users\User\AppData\Local\Programs\Ollama\rocm` and copy-replace `rocblas.dll` alongside `library` folder from downloaded zip.
> > 
> > 
> > Have anyone recreated this in Linux by any chance?
> > rocblas
> 
> Hi! i can reply in ubuntu v24.
> 
> The difference here is that you need to create the symlinking with the library inside the ollama directory instead of the rocm opt folder. For be clare: Instead of `sudo ln -s /opt/rocm/lib/rocblas/library/TensileLibrary_lazy_gfx{1030,1010}.dat` i do this here: `sudo ln -s /usr/local/lib/ollama/rocblas/library/TensileLibrary_lazy_gfx{1030,1010}.dat`
> 
> Check the error return by Ollama when you are running the server and fail, there is the correct folder where is the TensileLibrary.dat file.
> 
> See you and thanks @b0o !!!! ❤️🙌

I also have a Radeon 5700XT and a spare pc to experiment then I tried this:

Using a fresh Ubuntu 24.04,  I followed the steps to have ROCm installed from the official page. Latest version (6.2 at the time of this post). I am not near my test pc right now so I don't remember exaclty the steps I followed but was probably one of the steps below. Pretty sure I used the 1st link:
1) **https://rocm.docs.amd.com/projects/amdsmi/en/latest/install/install.html#install-amdgpu-driver-and-amd-smi-with-rocm**  
or
2) **https://rocm.docs.amd.com/projects/install-on-linux/en/latest/install/native-install/ubuntu.html**

GPU was detected so everything was looking fine so far.

Then installed Ollama with the default command line command:
**curl -fsSL https://ollama.com/install.sh | sh**

Kept a couple of terminal instances to monitor CPU (with htop) and GPU (with 'watch' and 'rocm-smi').

Installed and executed llama3.2 model:
**ollama run --verbose llama3.2**

Just to see if all was working, I tried like this and it was still CPU bounded.

Then applied what @tecnomanu did. 
Noticed the folder was empty before I created the symlink there:
**sudo ln -s /usr/local/lib/ollama/rocblas/library/TensileLibrary_lazy_gfx{1030,1010}.dat**

Applied also the environment below:
**export HSA_OVERRIDE_GFX_VERSION="10.1.0"**

Started the model again and it worked!
Only the GPU got the load this time!
This GPU is not the fastest for this kind of workload maybe is being choked by the rest of the PC I am using an X79 with an old Xeon E5 2650 V2 cpu. Still a lot faster than depending on the tired threads from my old CPU!

**Comment by thednp** [comment]
@fabdacab I can confirm your steps worked for me too. THANK YOU!

**Comment by Split7fire** [comment]
For me this workaround (@fabdacab)  just dont work. After all, then I type "ollama run gemma2", I got
`Error: llama runner process has terminated: signal: segmentation fault (core dumped)`
while "ollama serve" output 
`time=2024-12-11T12:55:29.556+07:00 level=INFO source=server.go:610 msg="waiting for server to become available" status="llm server not responding"
time=2024-12-11T12:55:30.312+07:00 level=INFO source=server.go:610 msg="waiting for server to become available" status="llm server error"
time=2024-12-11T12:55:30.563+07:00 level=ERROR source=sched.go:455 msg="error loading llama server" error="llama runner process has terminated: signal: segmentation fault (core dumped)"
`

I'm using Bluefin-gts 40 and install it into distrobox container (also fedora 40).

P.S. ollama also complain about amdgpu:
`
/opt/amdgpu/share/libdrm/amdgpu.ids: No such file or directory
`
but rocminfo displays all fine:


Agent 2                  
             
  Name:                    gfx1010                            
  Uuid:                    GPU-XX                             
  Marketing Name:          AMD Radeon RX 5700 XT              
  Vendor Name:             AMD                                
  Feature:                 KERNEL_DISPATCH                    
  Profile:                 BASE_PROFILE                       
  Float Round Mode:        NEAR                               
  Max Queue Number:        128(0x80)                          
  Queue Min Size:          64(0x40)                           
  Queue Max Size:          131072(0x20000)                    
  Queue Type:              MULTI                              
  Node:                    1                                  
  Device Type:             GPU                                
  Cache Info:              
    L1:                      16(0x10) KB                        
    L2:                      4096(0x1000) KB                    
  Chip ID:                 29471(0x731f)                      
  ASIC Revision:           2(0x2)                             
  Cacheline Size:          128(0x80)                          
  Max Clock Freq. (MHz):   2100                               
  BDFID:                   9728                               
  Internal Node ID:        1                                  
  Compute Unit:            40                                 
  SIMDs per CU:            2                                  
  Shader Engines:          2                                  
  Shader Arrs. per Eng.:   2                                  
  WatchPts on Addr. Ranges:4                                  
  Coherent Host Access:    FALSE                              
  Features:                KERNEL_DISPATCH 
  Fast F16 Operation:      TRUE                               
  Wavefront Size:          32(0x20)                           
  Workgroup Max Size:      1024(0x400)                        
  Workgroup Max Size per Dimension:
    x                        1024(0x400)                        
    y                        1024(0x400)                        
    z                        1024(0x400)                        
  Max Waves Per CU:        40(0x28)                           
  Max Work-item Per CU:    1280(0x500)                        
  Grid Max Size:           4294967295(0xffffffff)             
  Grid Max Size per Dimension:
    x                        4294967295(0xffffffff)             
    y                        4294967295(0xffffffff)             
    z                        4294967295(0xffffffff)             
  Max fbarriers/Workgrp:   32                                 
  Packet Processor uCode:: 149                                
  SDMA engine uCode::      35                                 
  IOMMU Support::          None                               
  Pool Info:               
    Pool 1                   
      Segment:                 GLOBAL; FLAGS: COARSE GRAINED      
      Size:                    8372224(0x7fc000) KB               
      Allocatable:             TRUE                               
      Alloc Granule:           4KB                                
      Alloc Recommended Granule:2048KB                             
      Alloc Alignment:         4KB                                
      Accessible by all:       FALSE                              
    Pool 2                   
      Segment:                 GLOBAL; FLAGS: EXTENDED FINE GRAINED
      Size:                    8372224(0x7fc000) KB               
      Allocatable:             TRUE                               
      Alloc Granule:           4KB                                
      Alloc Recommended Granule:2048KB                             
      Alloc Alignment:         4KB                                
      Accessible by all:       FALSE                              
    Pool 3                   
      Segment:                 GROUP                              
      Size:                    64(0x40) KB                        
      Allocatable:             FALSE                              
      Alloc Granule:           0KB                                
      Alloc Recommended Granule:0KB                                
      Alloc Alignment:         0KB                                
      Accessible by all:       FALSE                              
  ISA Info:                
    ISA 1                    
      Name:                    amdgcn-amd-amdhsa--gfx1010:xnack-  
      Machine Models:          HSA_MACHINE_MODEL_LARGE            
      Profiles:                HSA_PROFILE_BASE                   
      Default Rounding Mode:   NEAR                               
      Default Rounding Mode:   NEAR                               
      Fast f16:                TRUE                               
      Workgroup Max Size:      1024(0x400)                        
      Workgroup Max Size per Dimension:
        x                        1024(0x400)                        
        y                        1024(0x400)                        
        z                        1024(0x400)                        
      Grid Max Size:           4294967295(0xffffffff)             
      Grid Max Size per Dimension:
        x                        4294967295(0xffffffff)             
        y                        4294967295(0xffffffff)             
        z                        4294967295(0xffffffff)             
      FBarrier Max Size:       32

**Comment by RealVishy** [comment]
If anyone's looking for a simpler solution, I installed [https://github.com/containers/ramalama](https://github.com/containers/ramalamal).

Then it'll automatically use rocm for you.

`ramalama run llama3.2`

Here's the results when i bench it using rocm.

```
❯ ramalama bench llama3.2
ggml_cuda_init: GGML_CUDA_FORCE_MMQ:    no
ggml_cuda_init: GGML_CUDA_FORCE_CUBLAS: no
ggml_cuda_init: found 1 ROCm devices:
  Device 0: AMD Radeon RX 5700 XT, gfx1010:xnack- (0x1010), VMM: no, Wave Size: 32
| model                          |       size |     params | backend    | ngl |          test |                  t/s |
| ------------------------------ | ---------: | ---------: | ---------- | --: | ------------: | -------------------: |
| llama 3B Q4_K - Medium         |   1.87 GiB |     3.21 B | ROCm       | 999 |         pp512 |        690.26 ± 2.30 |
| llama 3B Q4_K - Medium         |   1.87 GiB |     3.21 B | ROCm       | 999 |         tg128 |         77.14 ± 0.09 |

build: aa6fb132 (4607)
```

**Comment by Split7fire** [comment]
> If anyone's looking for a simpler solution, I installed [ramalama](https://github.com/containers/ramalamal).
> 
> Then it'll automatically use rocm for you.
> 
> `ramalama run llama3.2`
> 
> Here's the results when i bench it using rocm.
> 
> ```
> ❯ ramalama bench llama3.2
> ggml_cuda_init: GGML_CUDA_FORCE_MMQ:    no
> ggml_cuda_init: GGML_CUDA_FORCE_CUBLAS: no
> ggml_cuda_init: found 1 ROCm devices:
>   Device 0: AMD Radeon RX 5700 XT, gfx1010:xnack- (0x1010), VMM: no, Wave Size: 32
> | model                          |       size |     params | backend    | ngl |          test |                  t/s |
> | ------------------------------ | ---------: | ---------: | ---------- | --: | ------------: | -------------------: |
> | llama 3B Q4_K - Medium         |   1.87 GiB |     3.21 B | ROCm       | 999 |         pp512 |        690.26 ± 2.30 |
> | llama 3B Q4_K - Medium         |   1.87 GiB |     3.21 B | ROCm       | 999 |         tg128 |         77.14 ± 0.09 |
> 
> build: aa6fb132 (4607)
> ```

Tried on my setup but get
```
ramalama bench llama3.2
100% |████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████|    1.88 GB/   1.88 GB  10.80 MB/s        0s

ggml_cuda_init: GGML_CUDA_FORCE_MMQ:    no
ggml_cuda_init: GGML_CUDA_FORCE_CUBLAS: no
ggml_cuda_init: found 1 ROCm devices:
  Device 0: AMD Radeon RX 5700 XT, gfx1010:xnack- (0x1010), VMM: no, Wave Size: 32
```
and that’s all

**Comment by RealVishy** [comment]
I think you need podman installed for it to work, it runs inside a container.

**Comment by Split7fire** [comment]
> I think you need podman installed for it to work, it runs inside a container.

I already have docker. And I saw that ramalama successfully download all required ROCm.

**Comment by RealVishy** [comment]
> > I think you need podman installed for it to work, it runs inside a container.
> 
> I already have docker. And I saw that ramalama successfully download all required ROCm.

You have to export this environment variable to use it with docker.

`export RAMALAMA_CONTAINER_ENGINE=docker`

**Comment by RealVishy** [comment]
> > > > I think you need podman installed for it to work, it runs inside a container.
> > > 
> > > 
> > > I already have docker. And I saw that ramalama successfully download all required ROCm.
> > 
> > 
> > You have to export this environment variable to use it with docker.
> > `export RAMALAMA_CONTAINER_ENGINE=docker`
> 
> I checked: my system has podman. I'm using Bluefin-dx (Fedora) and it may be connected with atomic nature of OS.

😭 I'm on aurora-dx and it's fine for me. Can you try running it on your cpu to see if it'll work on your cpu at least?

`ramalama --ngl 0  bench llama3.2`

**Comment by Split7fire** [comment]
> > > > > I think you need podman installed for it to work, it runs inside a container.
> > > > 
> > > > 
> > > > I already have docker. And I saw that ramalama successfully download all required ROCm.
> > > 
> > > 
> > > You have to export this environment variable to use it with docker.
> > > `export RAMALAMA_CONTAINER_ENGINE=docker`
> > 
> > 
> > I checked: my system has podman. I'm using Bluefin-dx (Fedora) and it may be connected with atomic nature of OS.
> 
> 😭 I'm on aurora-dx and it's fine for me. Can you try running it on your cpu to see if it'll work on your cpu at least?
> 
> `ramalama --ngl 0 bench llama3.2`

How did you install ramalama? pip? containers?

**Comment by Split7fire** [comment]
> > > > > I think you need podman installed for it to work, it runs inside a container.
> > > > 
> > > > 
> > > > I already have docker. And I saw that ramalama successfully download all required ROCm.
> > > 
> > > 
> > > You have to export this environment variable to use it with docker.
> > > `export RAMALAMA_CONTAINER_ENGINE=docker`
> > 
> > 
> > I checked: my system has podman. I'm using Bluefin-dx (Fedora) and it may be connected with atomic nature of OS.
> 
> 😭 I'm on aurora-dx and it's fine for me. Can you try running it on your cpu to see if it'll work on your cpu at least?
> 
> `ramalama --ngl 0 bench llama3.2`

strange. Your command output this:
```
usage: ramalama [-h] [--container] [--debug] [--dryrun] [--engine ENGINE] [--gpu] [--image IMAGE] [--nocontainer] [--runtime {llama.cpp,vllm}] [--store STORE] [-v]
                {help,bench,benchmark,containers,ps,convert,info,list,ls,login,logout,perplexity,pull,push,rm,run,serve,stop,version} ...
ramalama: error: argument subcommand: invalid choice: '0' (choose from help, bench, benchmark, containers, ps, convert, info, list, ls, login, logout, perplexity, pull, push, rm, run, serve, stop, version)
```

**Comment by RealVishy** [comment]
@Split7fire Can you open an issue on the bluefin github (or send a message on the ublue discord) for this, might be worth doing it there. I don't want to pollute this issue. Just tag this issue in it so i know where it is.

**Comment by mon-jai** [comment]
This issue could be resolved if #9650 is merged. 

Ollama with Vulkan runs perfectly on my Radeon RX 5700, even though it isn't supported by ROCm. Just run the installer and you are good to go, no manual file swapping required.

For now, we can use the binaries compiled by @McBane87: https://github.com/whyvl/ollama-vulkan/issues/7#issue-2828064858

**Comment by Split7fire** [comment]
@mon-jai Great news, but can you elaborate what installer is mentioned? Official one, or forked one?

**Comment by mon-jai** [comment]
@Split7fire The "Newest build (v0.6.1)" from the first comment.

**Comment by zero-thermo** [comment]
Any updates to getting this working with Ollama set up via Docker Compose with the official `ollama/ollama:rocm` image?  

I've added the following to `docker-compose.yml`:
```
    environment:
      - HSA_OVERRIDE_GFX_VERSION=10.3.0
      - HSA_ENABLE_SDMA=0
      - OLLAMA_NEW_ENGINE=false
```

However, I can't figure out how to permanently add the `TensileLibrary_lazy_gfx1010.dat` symlink since it resets after every Docker container restart.

Everything starts fine, and I see the 5700 XT recognized in the Ollama logs, but when I try to run a query I see the following errors:
```
GPU coredump: execvp failed: No such file or directory

level=ERROR
source=server.go:1240
msg=do load request
error=Post \"http://127.0.0.1:42405/load\": EOF

level=ERROR
source=server.go:1240
msg=do load request
error=Post \"http://127.0.0.1:42405/load\": dial tcp 127.0.0.1:42405: connect: connection refused

level=INFO
source=sched.go:511
msg=Load failed
model=/root/.ollama/models/blobs/sha256-4e30e2665218745ef463f722c0bf86be0cab6ee676320f1cfadf91e989107448
error=model failed to load, this may be due to resource limitations or an internal error, check ollama server logs for details
```

**Comment by tecnomanu** [comment]
I thinks this thread is finish, I test ollama with my Radeon 5700 xt and is working fine without setting any special attribute, as defaults settings.

**Comment by dhiltgen** [comment]
Closing this since ROCm support for this GPU target is not planned. Current Ollama builds include Vulkan support, and Vulkan is enabled by default when the backend/driver is available. Please update to the latest Ollama release and use the Vulkan path for this hardware.

For Docker, use the standard `ollama/ollama` image with GPU devices exposed. If Vulkan still fails on a current release, please open a new issue with `OLLAMA_DEBUG=1` logs showing Vulkan discovery.
