### ISSUE TITLE
Ollama is not using my GPU (Windows)

### ISSUE THREAD

**Issue by nethriis** [ollama/ollama#3201]
### What is the issue?

I have restart my PC and I have launched Ollama in the terminal using mistral:7b and a viewer of GPU usage (task manager). I have asked a question, and it replies to me quickly, I see the GPU usage increase around 25%, ok that's seems good. But then I have asked another question and now it take long time and I see the GPU usage oscillate between 0 and 1 percent.

### What did you expect to see?

A higher GPU usage with a fast response.

### Steps to reproduce

```bash
$ ollama run mistral:7b --verbose
```

### OS

Windows

### Architecture

x86

### Ollama version

0.1.29

### GPU

Nvidia

### GPU info

|   0  NVIDIA GeForce RTX 3050 ...  WDDM  |   00000000:01:00.0 Off |                  N/A |
| N/A   49C    P8              5W /   38W |    2998MiB /   4096MiB |     12%      Default |

### CPU

Intel

### Other software

32GB of RAM

**Comment by nethriis** [comment]
I found something that can provide precision. In fact, for the entire loading time, I see the GPU usage increase around 29%, but when I start to generate the text, the GPU usage drops to 0% and it takes a long time

**Comment by igorschlum** [comment]
@nethriis can you please share the prompt if it's a special one. Easier to try to reproduce. Did you try with another LLM like

ollama run tinydolphin

It will help see if it's a memory issue. Have you a way to see CPU usage?

**Comment by nethriis** [comment]
My prompt was
```plaintext
Why is the sky blue?
```
I tried running with `tinyllama` and it works fine.
I have Windows Task Manager which allows me to see CPU usage as well.

**Comment by jerryola1** [comment]
have you try used it directly as one of the requred parameter expected by the model, eg device="cuda"

**Comment by dhiltgen** [comment]
We're working on improvements to the memory prediction algorithm which should allow us to more fully utilize the GPUs VRAM without hitting an out-of-memory error.  It looks like you're trying to load a 4G model into a 4G GPU which given some overhead, should mostly fit.  Any layers we can't fit into VRAM are processed by the CPU.  Since the GPU is much faster than CPU, the GPU winds up being idle waiting for the CPU to keep up.  If you look in the server log, you'll be able to see a log line that looks something like this:
```
llm_load_tensors: offloaded 22/33 layers to GPU
```

**Comment by dhiltgen** [comment]
Check out https://github.com/ollama/ollama/blob/main/docs/troubleshooting.md

**Comment by dhiltgen** [comment]
The closer you get to 33/33 layers, the faster it will be.   I'm going to close this issue now, but if you're still having problems, let us know.

**Comment by cr1cr1** [comment]
https://github.com/ollama/ollama/issues/4008#issuecomment-2096623526

**Comment by ACodingfreak** [comment]
Well in case of Windows11 is there a way I can set ollama to use 100%GPU on my laptop ?

**Comment by GITHUBWJTANG** [comment]
Check out your context window size and try from smaller context window.
Looks like ollama falls back to using CPU while the context window saturated the VRAM (i.e. over 90%) and it's obviously visible in perfMon.

Test case:   RTX4060/8GVRAM, i7g14/32GRAM, llama | granite
Context window > 8k, 100% CPU observed. Otherwise, GPU is being used.

**Comment by lynrayy** [comment]
Just tried gpt-oss 20b, it is not using my GPU at all. All the model loaded in RAM, no VRAM affected

**Comment by lynrayy** [comment]
Solution?

**Comment by Drommedhar** [comment]
I can confirm that gpt-oss 20b is running purely on CPU under windows. Not using a single bit of my 5090 over here

**Comment by Drommedhar** [comment]
Just got it to work on GPU. Dont know why but closing down ollama completly (right click in notification bar and exit) and restarting the cmd (and cleaning log directory, so this should not matter) did load it into GPU

<img width="768" height="48" alt="Image" src="https://github.com/user-attachments/assets/78c6b6d0-89b7-456b-b629-267eed17672d" />

**Comment by lynrayy** [comment]
Not helped for me, it is refusing to use GPU

**Comment by lynrayy** [comment]
Oh it is appears in tray. Will try later

**Comment by moeelbadri** [comment]
> I can confirm that gpt-oss 20b is running purely on CPU under windows. Not using a single bit of my 5090 over here

same, also i tried ur solution didnt work , rtx 3060 12 gb windows 11 ollama windows


in the logs

layers.model=25
layers.offload=13
memory.required.full = 16.9 GiB
memory.required.partial = 10.8 GiB

**Comment by JoseDv1** [comment]
It's happening to me too. I discovered that if you lower the context window, part of the model loads on the GPU. I have an RTX 4070 Laptop 8GB. Ollama on windows 11

**Comment by janhlavsa** [comment]
Same here - Windows 10, RTX 3090, GPT OSS-20B purely on CPU. Any thoughts how to solve that? 

Update:  

The context length is a problem:
4K/8K - used VRAM 14,2GB - very fast
16K - used VRAM 16,5GB - very fast
32K - used VRAM 14,1GB - slow (GPU used only partially?)
64K/128K - used VRAM 0GB - very slow (CPU only obviously)

However, it never utilizes all available VRAM. That seems to be an issue. 


Update 2: 
Just updated to a new version 0.11.3 and the issue seems to be resolved. With 32K context it seems to be purely on GPU (21GB of VRAM used).

**Comment by juniormayhe** [comment]
32K context uses zero GPU, 
while 4K uses 22% GPU. 

So increasing the context length in settings will likely cause a fallback to CPU without the user realizing it.
I would expect this to be bit faster and use 90% of GPU. 

Setup:
RAM 128GB
Nvidia 4080 SUPER
Storage SSD nvme

Currently the tool is too slow to be practical—even when using the smallest context window. 
This significantly impacts its usefulness.

**Comment by lynrayy** [comment]
Mine context is 4k by default, i can't get lower. I have 6gb VRAM

**Comment by JoseDv1** [comment]
> Mine context is 4k by default, i can't get lower. I have 6gb VRAM

Maybe you can set less through environment variables

**Comment by JoseDv1** [comment]
> Mine context is 4k by default, i can't get lower. I have 6gb VRAM

Maybe you can set less through environment variables

**Comment by disarticulate** [comment]
Can we get a comman like rocminfo or nvtop that shows/verifies what GPU is accessible? Seems like a simple abstract. Just listing all the compatibilities doesn't help verify it's picking up the correct GPU.

**Comment by JoewAlabel** [comment]
still broken. ollama don'tg run on nvidia gpus so its totally sh1t

**Comment by PatParslow** [comment]
Having had some significant issues with the same behaviour (GTX5070ti) and spending half a day installing different versions (it used to work... so let's try old ones...), including building from source, I discovered it was failing silently because something on WSL2 was occupying the standard port 11434.  Might help other people resolve the issue (if they haven't tried checking that).  A nice loud error message would be nice...

**Comment by irtiq7** [comment]
Is this issue being resolved? I agree with everyone above that ollama is not using GPU.

**Comment by geomorillo** [comment]
it is not resolved yet

**Comment by athuljayaram** [comment]
not working...same issue

**Comment by thatfrozenfrog** [comment]
Not working
