### ISSUE TITLE
ollama not using AMD GPU on linux

### ISSUE THREAD

**Issue by jab416171** [ollama/ollama#3446]
### What is the issue?

ollama is only using my CPU. I've tried running it with `ROCR_VISIBLE_DEVICES=0 ollama serve` but that doesn't seem to change anything.

```
time=2024-04-01T22:37:03.207-06:00 level=INFO source=routes.go:1118 msg="Listening on 127.0.0.1:11434 (version 0.1.30)"
time=2024-04-01T22:37:03.207-06:00 level=INFO source=payload_common.go:113 msg="Extracting dynamic libraries to /tmp/ollama2592388870/runners ..."
time=2024-04-01T22:37:03.358-06:00 level=INFO source=payload_common.go:140 msg="Dynamic LLM libraries [cpu_avx2 cpu cpu_avx]"
time=2024-04-01T22:37:03.358-06:00 level=INFO source=gpu.go:115 msg="Detecting GPU type"
time=2024-04-01T22:37:03.358-06:00 level=INFO source=gpu.go:265 msg="Searching for GPU management library libcudart.so*"
time=2024-04-01T22:37:03.385-06:00 level=INFO source=gpu.go:311 msg="Discovered GPU libraries: []"
time=2024-04-01T22:37:03.385-06:00 level=INFO source=gpu.go:265 msg="Searching for GPU management library libnvidia-ml.so"
time=2024-04-01T22:37:03.397-06:00 level=INFO source=gpu.go:311 msg="Discovered GPU libraries: []"
time=2024-04-01T22:37:03.397-06:00 level=INFO source=cpu_common.go:11 msg="CPU has AVX2"
time=2024-04-01T22:37:03.397-06:00 level=WARN source=amd_linux.go:53 msg="ollama recommends running the https://www.amd.com/en/support/linux-drivers: amdgpu version file missing: /sys/module/amdgpu/version stat /sys/module/amdgpu/version: no such file or directory"
time=2024-04-01T22:37:03.397-06:00 level=INFO source=amd_linux.go:88 msg="detected amdgpu versions [gfx1030]"
time=2024-04-01T22:37:03.404-06:00 level=INFO source=amd_linux.go:119 msg="amdgpu [0] gfx1030 is supported"
time=2024-04-01T22:37:03.404-06:00 level=INFO source=amd_linux.go:246 msg="[0] amdgpu totalMemory 16368M"
time=2024-04-01T22:37:03.404-06:00 level=INFO source=amd_linux.go:247 msg="[0] amdgpu freeMemory  16368M"
[GIN] 2024/04/01 - 22:42:28 | 200 |       30.06µs |       127.0.0.1 | HEAD     "/"
[GIN] 2024/04/01 - 22:42:28 | 200 |   16.663531ms |       127.0.0.1 | POST     "/api/show"
[GIN] 2024/04/01 - 22:42:28 | 200 |     402.998µs |       127.0.0.1 | POST     "/api/show"
time=2024-04-01T22:42:28.514-06:00 level=INFO source=cpu_common.go:11 msg="CPU has AVX2"
time=2024-04-01T22:42:28.514-06:00 level=WARN source=amd_linux.go:53 msg="ollama recommends running the https://www.amd.com/en/support/linux-drivers: amdgpu version file missing: /sys/module/amdgpu/version stat /sys/module/amdgpu/version: no such file or directory"
time=2024-04-01T22:42:28.514-06:00 level=INFO source=amd_linux.go:88 msg="detected amdgpu versions [gfx1030]"
time=2024-04-01T22:42:28.517-06:00 level=INFO source=amd_linux.go:119 msg="amdgpu [0] gfx1030 is supported"
time=2024-04-01T22:42:28.517-06:00 level=INFO source=amd_linux.go:246 msg="[0] amdgpu totalMemory 16368M"
time=2024-04-01T22:42:28.517-06:00 level=INFO source=amd_linux.go:247 msg="[0] amdgpu freeMemory  16368M"
time=2024-04-01T22:42:28.517-06:00 level=INFO source=cpu_common.go:11 msg="CPU has AVX2"
time=2024-04-01T22:42:28.517-06:00 level=WARN source=amd_linux.go:53 msg="ollama recommends running the https://www.amd.com/en/support/linux-drivers: amdgpu version file missing: /sys/module/amdgpu/version stat /sys/module/amdgpu/version: no such file or directory"
time=2024-04-01T22:42:28.517-06:00 level=INFO source=amd_linux.go:88 msg="detected amdgpu versions [gfx1030]"
time=2024-04-01T22:42:28.520-06:00 level=INFO source=amd_linux.go:119 msg="amdgpu [0] gfx1030 is supported"
time=2024-04-01T22:42:28.520-06:00 level=INFO source=amd_linux.go:246 msg="[0] amdgpu totalMemory 16368M"
time=2024-04-01T22:42:28.520-06:00 level=INFO source=amd_linux.go:247 msg="[0] amdgpu freeMemory  16368M"
time=2024-04-01T22:42:28.521-06:00 level=INFO source=cpu_common.go:11 msg="CPU has AVX2"
loading library /tmp/ollama2592388870/runners/cpu_avx2/libext_server.so
time=2024-04-01T22:42:28.523-06:00 level=INFO source=dyn_ext_server.go:87 msg="Loading Dynamic llm server: /tmp/ollama2592388870/runners/cpu_avx2/libext_server.so"
time=2024-04-01T22:42:28.523-06:00 level=INFO source=dyn_ext_server.go:147 msg="Initializing llama server"
```

### OS

Linux

### Architecture

arm64

### Ollama version

0.1.30

### GPU

AMD

### GPU info

```
  Name:                    gfx1030
  Marketing Name:          AMD Radeon RX 6900 XT
  Vendor Name:             AMD
  Feature:                 KERNEL_DISPATCH
  Profile:                 BASE_PROFILE
  Float Round Mode:        NEAR
  Max Queue Number:        128(0x80)
  Queue Min Size:          64(0x40)
  Queue Max Size:          131072(0x20000)
  Queue Type:              MULTI
  Node:                    1
  Device Type:             GPU
  ```

### CPU

AMD

**Comment by stephensrmmartin** [comment]
Did you compile this yourself, or is this a release?

I just pulled and compiled 0.1.30 on Arch, with a 6700xt, and it works.

**Comment by jab416171** [comment]
I'm using the arch package https://archlinux.org/packages/extra/x86_64/ollama/

**Comment by stephensrmmartin** [comment]
Ok then yes - the Arch release does not have rocm support. I think it's CPU only.

Just git pull the ollama repo. Cd into it. Run:

go generate ./...
go build ./

Then manually cp ollama (the binary) to replace the arch version. You could rebuild the arch PKG too, but honestly it's easy.
Make sure you have all the rocm deps and such. Also make sure you have any env variables you need. I have to use the hsa_override_gfx_version due my 6700xt, not sure if you do.

**Comment by kode54** [comment]
Yes, specifying the HSA_OVERRIDE_GFX_VERSION variable was all I needed. I stuck that into the systemd service file.

**Comment by jab416171** [comment]
Thank you, that worked! So why doesn't the arch release have rocm support?

**Comment by Soliprem** [comment]
I think there's an AUR version with rocm support (ollama-rocm-git). I would guess the "base" version uses less space (some mb, compared to the AUR package which takes up 11gb) which might make sense if disk space is a concern?

**Comment by ProjectMoon** [comment]
> Thank you, that worked! So why doesn't the arch release have rocm support?

What did you put as the value for the environment variable?

**Comment by dhiltgen** [comment]
As others have pointed out, you're running a distro specific package which did not include the rocm build
```
time=2024-04-01T22:37:03.358-06:00 level=INFO source=payload_common.go:140 msg="Dynamic LLM libraries [cpu_avx2 cpu cpu_avx]"
```
That is CPU only - no cuda or rocm runners were compiled in.

Please use the package from your distro that contains the GPU components, or use our [official binary distribution and install](https://github.com/ollama/ollama/blob/main/docs/linux.md#install), or you can [build from source](https://github.com/ollama/ollama/blob/main/docs/development.md#linux-rocm-amd) if you prefer.
