### ISSUE TITLE
ollama crashed  at 0.1.31 - CUDA out of memory

### ISSUE THREAD

**Issue by abnormalboy** [ollama/ollama#3568]
### What is the issue?

When i use langchain in python , the ollama crashed . What model i use is "gemma:7b". when i use "llama2:7b" ollama is normal work. Is my memory is not support? My computer GPU memory is 8GB. 
```pyhon
from langchain.llms.ollama import Ollama
from langchain_core.prompts import ChatPromptTemplate
from langchain_core.output_parsers import StrOutputParser
from langchain_community.vectorstores import DocArrayInMemorySearch
from langchain_core.runnables import RunnableParallel, RunnablePassthrough
from langchain_community.embeddings import OllamaEmbeddings
import asyncio
async def main():

    vectorstore = DocArrayInMemorySearch.from_texts(
        ["以可解析的json格式返回", "如{\"hello\":\"world\"}"],
        embedding=OllamaEmbeddings(),
    )

    retriever = vectorstore.as_retriever()

    template = """Answer the question based only on the following context:
    {context}

    Question: {question}
    """
    prompt = ChatPromptTemplate.from_template(template)
    model = Ollama(model="gemma")
    output_parser = StrOutputParser()

    setup_and_retrieval = RunnableParallel(
        {"context": retriever, "question": RunnablePassthrough()}
    )
    chain = setup_and_retrieval | prompt | model | output_parser

    print(chain.input_schema.schema())
    chunks = []
    async for chunk in chain.astream("返回一个苹果"):
        chunks.append(chunk)
        print(chunk, end="", flush=True)
asyncio.run(main())
```
```ollama log
time=2024-04-10T08:55:13.247+08:00 level=WARN source=server.go:113 msg="server crash 59 - exit code 3221226505 - respawning"
```

### OS

Windows

### Architecture

amd64

### Ollama version

0.1.31

### GPU

Nvidia

### GPU info

<img width="635" alt="Snipaste_2024-04-10_08-50-17" src="https://github.com/ollama/ollama/assets/77949946/0d6a607e-c8ab-4db8-8b01-1c0e9738647b">

### CPU

Intel

**Comment by LukeMauldin** [comment]
I can confirm on Windows on Ollama version 0.1.31 I am seeing the same behavior with the gemma-7b models.  Attaching my app and server log.  GPU is an Nvidia RTX 4050 with driver version 546.09.
[app.log](https://github.com/ollama/ollama/files/14932411/app.log)
[server.log](https://github.com/ollama/ollama/files/14932412/server.log)

```
                   ollama list
NAME                            ID              SIZE    MODIFIED
codegemma:7b-code               8dd7a5cc56a5    5.0 GB  50 minutes ago
codegemma:7b-instruct           ca966f70c13f    5.0 GB  50 minutes ago
deepseek-coder:6.7b-instruct    ce298d984115    3.8 GB  44 hours ago
gemma:7b-instruct-v1.1-q4_0     a72c7f4d0a15    5.0 GB  49 minutes ago
mistral:7b-instruct             61e88e884507    4.1 GB  44 hours ago
openchat:7b                     537a4e03b649    4.1 GB  44 hours ago
starling-lm:7b                  39153f619be6    4.1 GB  19 hours ago
```

**Comment by qua1121** [comment]
Same here.

**Comment by IHaBiS02** [comment]
Same here too.

**Comment by ycyy** [comment]
#3232 Update to version 0.1.32 for testing.

**Comment by qua1121** [comment]
> #3232 Update to version 0.1.32 for testing.

It works like a charm! Thanks:-)

**Comment by dhiltgen** [comment]
We've fixed a number of bugs in the memory prediction logic recently, so it sounds like we can close this one as fixed.  If you're still seeing OOM crashes with 0.1.33, please share your server log so we can see where the prediction logic went wrong.
