### ISSUE TITLE
llama runner process no longer running: -1 CUDA error: CUBLAS_STATUS_EXECUTION_FAILED

### ISSUE THREAD

**Issue by holycrypto** [ollama/ollama#3701]
### What is the issue?

Follow the manual: https://github.com/ollama/ollama/blob/9df6c85c3a51ce00d6a65be9dd8a06af07b24af5/docs/tutorials/nvidia-jetson.md
But run error:

```bash
ollama run mistral-jetson
```

Errors
```bash
Error: llama runner process no longer running: -1 CUDA error: CUBLAS_STATUS_EXECUTION_FAILED
  current device: 0, in function ggml_cuda_mul_mat_batched_cublas at /go/src/github.com/ollama/ollama/llm/llama.cpp/ggml-cuda.cu:1848
  cublasGemmBatchedEx(ctx.cublas_handle(), CUBLAS_OP_T, CUBLAS_OP_N, ne01, ne11, ne10, alpha, (const void **) (ptrs_src.get() + 0*ne23), CUDA_R_16F, nb01/nb00, (const void **) (ptrs_src.get() + 1*ne23), CUDA_R_16F, nb11/nb10, beta, ( void **) (ptrs_dst.get() + 0*ne23), cu_data_type, ne01, ne23, cu_compute_type, CUBLAS_GEMM_DEFAULT_TENSOR_OP)
GGML_ASSERT: /go/src/github.com/ollama/ollama/llm/llama.cpp/ggml-cuda.cu:60: !"CUDA error"
```

### OS

Linux

### Architecture

arm64

### Ollama version

0.1.32

### GPU

Nvidia

### GPU info

+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 540.2.0                Driver Version: N/A          CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Orin (nvgpu)                  N/A  | N/A              N/A |                  N/A |
| N/A   N/A  N/A               N/A /  N/A | Not Supported        |     N/A          N/A |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+
                                                                                         
+---------------------------------------------------------------------------------------+
| Processes:                                                                            |
|  GPU   GI   CI        PID   Type   Process name                            GPU Memory |
|        ID   ID                                                             Usage      |
|=======================================================================================|
|  No running processes found                                                           |
+---------------------------------------------------------------------------------------+

**Comment by holycrypto** [comment]
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2023 NVIDIA Corporation
Built on Tue_Aug_15_22:08:11_PDT_2023
Cuda compilation tools, release 12.2, V12.2.140
Build cuda_12.2.r12.2/compiler.33191640_0

**Comment by Aayog** [comment]
Getting the same issue with the llama3:70b

ollama run llama3:70b
Error: llama runner process no longer running: 1

 It works fine with other models, so I think this issue is that my GPU only has 24GB and this requires 40GB. The other issues might be due to the same.

**Comment by holycrypto** [comment]
jetson-containers docker env parameters:

```
CMAKE_CUDA_COMPILER	/usr/local/cuda/bin/nvcc
CUDA_ARCHITECTURES	87
CUDA_BIN_PATH	/usr/local/cuda/bin
CUDA_HOME	/usr/local/cuda
CUDA_NVCC_EXECUTABLE	/usr/local/cuda/bin/nvcc
CUDA_TOOLKIT_ROOT_DIR	/usr/local/cuda
CUDAARCHS	87
CUDACXX	/usr/local/cuda/bin/nvcc
CUDNN_LIB_INCLUDE_PATH	/usr/include
CUDNN_LIB_PATH	/usr/lib/aarch64-linux-gnu
DEBIAN_FRONTEND	noninteractive
JETSON_JETPACK	6.0
LANG	en_US.UTF-8
LANGUAGE	en_US:en
LC_ALL	en_US.UTF-8
LD_LIBRARY_PATH	/usr/local/cuda/lib:/usr/local/cuda/lib64:/usr/local/cuda/include:/usr/local/cuda/compat:/usr/local/cuda/lib64:
NVCC_PATH	/usr/local/cuda/bin/nvcc
NVIDIA_DRIVER_CAPABILITIES	all
NVIDIA_VISIBLE_DEVICES	all
OLLAMA_HOST	0.0.0.0
OLLAMA_MODELS	/ollama
PATH	/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
PIP_INDEX_URL	http://jetson.webredirect.org/jp6/cu122
PIP_TRUSTED_HOST	jetson.webredirect.org
SCP_UPLOAD_PASS	nvidia
SCP_UPLOAD_URL	jao-51:/dist/jp6/cu122
SCP_UPLOAD_USER	nvidia
TAR_INDEX_URL	http://jetson.webredirect.org:8000/jp6/cu122
TORCH_NVCC_FLAGS	-Xfatbin -compress-all
TWINE_PASSWORD	NvidiaJetson24
TWINE_REPOSITORY_URL	http://jao-51/jp6/cu122
TWINE_USERNAME	jp6
```

**Comment by holycrypto** [comment]
> Getting the same issue with the llama3:70b
> 
> ollama run llama3:70b Error: llama runner process no longer running: 1
> 
> It works fine with other models, so I think this issue is that my GPU only has 24GB and this requires 40GB. The other issues might be due to the same.

I have tries all models with Jetson AGX Orin 64GB,  but output same errors, can you share which version of your jetson device is?

**Comment by Aspirinkb** [comment]
same error on AGX Orin 64GB, Jetpack 6.0 DP [L4T 36.2.0]

**Comment by Aspirinkb** [comment]
I have resolved the issue because I made a silly mistake. In simple terms, I had already started the Ollama service in the system before launching the container. So when I executed `ollama run phi3` inside the container, it was actually being processed by the Ollama service outside the container, not the one inside.

Therefore, when I shut down the Ollama service outside the container, started it inside the container, and tried running the model again, it worked successfully.

**Comment by holycrypto** [comment]
#

> I have resolved the issue because I made a silly mistake. In simple terms, I had already started the Ollama service in the system before launching the container. So when I executed `ollama run phi3` inside the container, it was actually being processed by the Ollama service outside the container, not the one inside.
> 
> Therefore, when I shut down the Ollama service outside the container, started it inside the container, and tried running the model again, it worked successfully.

Wow, bro thats right! I resolved it too, I also have ollama server outside container.
