### ISSUE TITLE
Ollama is not using GPU to run model on Windows 11

### ISSUE THREAD

**Issue by maxithub** [ollama/ollama#3771]
### What is the issue?

**version:** 0.1.31
**gpu:** nvidia qradro p2000 (5GB GPU memory)
**os:** win 11
**cuda:**
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2023 NVIDIA Corporation
Built on Fri_Nov__3_17:51:05_Pacific_Daylight_Time_2023
Cuda compilation tools, release 12.3, V12.3.103
Build cuda_12.3.r12.3/compiler.33492891_0
**Command:** ollama run tinydolphin
![Screenshot 2024-04-20 121734](https://github.com/ollama/ollama/assets/11460496/4e0853e7-14c9-4138-a031-003553dd1c7f)
the 2nd column is CPU (20%), the 3rd one is GPU (0%)

### OS

Windows

### GPU

Nvidia

### CPU

Intel

### Ollama version

0.1.31

**Comment by igorschlum** [comment]
Hi @maxithub can you update to version 0.1.32 of Ollama ans tell us if you reproduce the same issue?

**Comment by maxithub** [comment]
@igorschlum thank you very much for the swift response. I just upgraded to 0.1.32, and noticed there is a new process named ollama_llama_server created to run the model. Unfortunately, the problem still persists.
![image](https://github.com/ollama/ollama/assets/11460496/7e98af68-7e9e-412e-8a4a-7bb5c8282145)

And i can't find any log in the %userprofile%/.ollama folder, like it was mentioned in other issues.

**Comment by TuziwochatGPT** [comment]
我也出现了同样的问题，它只占用我的cup算力，显卡无法使用

**Comment by maxithub** [comment]
Ohh, finally got it working now after install the latest CUDA version [cuda_12.4.1_551.78_windows.exe](https://developer.download.nvidia.com/compute/cuda/12.4.1/local_installers/cuda_12.4.1_551.78_windows.exe)
![image](https://github.com/ollama/ollama/assets/11460496/3166158c-c886-41c9-8f5d-0376c50ffe08)

Really love the simplicity offered by Ollama! One command and things just work! Thank you so much for the brilliant work!

**Comment by TuziwochatGPT** [comment]
谢谢，已通知富健，他会及时查看。
