### ISSUE TITLE
ollama doesn't seem to use my GPU after update

### ISSUE THREAD

**Issue by miguelmarco** [ollama/ollama#7622]
### What is the issue?

I had ollama compiled from source and it worked fine. Recently I rebuild it to the last version, and it seems to not use my GPU anymore (it uses a lot of CPU processes, and it runs much slower).

Here is the output of the server:

```
2024/11/11 21:50:18 routes.go:1189: INFO server config env="map[CUDA_VISIBLE_DEVICES: GPU_DEVICE_ORDINAL: HIP_VISIBLE_DEVICES: HSA_OVERRIDE_GFX_VERSION: HTTPS_PROXY: HTTP_PROXY: NO_PROXY: OLLAMA_DEBUG:false OLLAMA_FLASH_ATTENTION:false OLLAMA_GPU_OVERHEAD:0 OLLAMA_HOST:http://127.0.0.1:11434 OLLAMA_INTEL_GPU:false OLLAMA_KEEP_ALIVE:5m0s OLLAMA_LLM_LIBRARY: OLLAMA_LOAD_TIMEOUT:5m0s OLLAMA_MAX_LOADED_MODELS:0 OLLAMA_MAX_QUEUE:512 OLLAMA_MODELS:/home/mmarco/.ollama/models OLLAMA_MULTIUSER_CACHE:false OLLAMA_NOHISTORY:false OLLAMA_NOPRUNE:false OLLAMA_NUM_PARALLEL:0 OLLAMA_ORIGINS:[http://localhost https://localhost http://localhost:* https://localhost:* http://127.0.0.1 https://127.0.0.1 http://127.0.0.1:* https://127.0.0.1:* http://0.0.0.0 https://0.0.0.0 http://0.0.0.0:* https://0.0.0.0:* app://* file://* tauri://* vscode-webview://*] OLLAMA_SCHED_SPREAD:false OLLAMA_TMPDIR: ROCR_VISIBLE_DEVICES: http_proxy: https_proxy: no_proxy:]"
time=2024-11-11T21:50:18.708+01:00 level=INFO source=images.go:755 msg="total blobs: 39"
time=2024-11-11T21:50:18.709+01:00 level=INFO source=images.go:762 msg="total unused blobs removed: 0"
[GIN-debug] [WARNING] Creating an Engine instance with the Logger and Recovery middleware already attached.

[GIN-debug] [WARNING] Running in "debug" mode. Switch to "release" mode in production.
 - using env:   export GIN_MODE=release
 - using code:  gin.SetMode(gin.ReleaseMode)

[GIN-debug] POST   /api/pull                 --> github.com/ollama/ollama/server.(*Server).PullHandler-fm (5 handlers)
[GIN-debug] POST   /api/generate             --> github.com/ollama/ollama/server.(*Server).GenerateHandler-fm (5 handlers)
[GIN-debug] POST   /api/chat                 --> github.com/ollama/ollama/server.(*Server).ChatHandler-fm (5 handlers)
[GIN-debug] POST   /api/embed                --> github.com/ollama/ollama/server.(*Server).EmbedHandler-fm (5 handlers)
[GIN-debug] POST   /api/embeddings           --> github.com/ollama/ollama/server.(*Server).EmbeddingsHandler-fm (5 handlers)
[GIN-debug] POST   /api/create               --> github.com/ollama/ollama/server.(*Server).CreateHandler-fm (5 handlers)
[GIN-debug] POST   /api/push                 --> github.com/ollama/ollama/server.(*Server).PushHandler-fm (5 handlers)
[GIN-debug] POST   /api/copy                 --> github.com/ollama/ollama/server.(*Server).CopyHandler-fm (5 handlers)
[GIN-debug] DELETE /api/delete               --> github.com/ollama/ollama/server.(*Server).DeleteHandler-fm (5 handlers)
[GIN-debug] POST   /api/show                 --> github.com/ollama/ollama/server.(*Server).ShowHandler-fm (5 handlers)
[GIN-debug] POST   /api/blobs/:digest        --> github.com/ollama/ollama/server.(*Server).CreateBlobHandler-fm (5 handlers)
[GIN-debug] HEAD   /api/blobs/:digest        --> github.com/ollama/ollama/server.(*Server).HeadBlobHandler-fm (5 handlers)
[GIN-debug] GET    /api/ps                   --> github.com/ollama/ollama/server.(*Server).PsHandler-fm (5 handlers)
[GIN-debug] POST   /v1/chat/completions      --> github.com/ollama/ollama/server.(*Server).ChatHandler-fm (6 handlers)
[GIN-debug] POST   /v1/completions           --> github.com/ollama/ollama/server.(*Server).GenerateHandler-fm (6 handlers)
[GIN-debug] POST   /v1/embeddings            --> github.com/ollama/ollama/server.(*Server).EmbedHandler-fm (6 handlers)
[GIN-debug] GET    /v1/models                --> github.com/ollama/ollama/server.(*Server).ListHandler-fm (6 handlers)
[GIN-debug] GET    /v1/models/:model         --> github.com/ollama/ollama/server.(*Server).ShowHandler-fm (6 handlers)
[GIN-debug] GET    /                         --> github.com/ollama/ollama/server.(*Server).GenerateRoutes.func1 (5 handlers)
[GIN-debug] GET    /api/tags                 --> github.com/ollama/ollama/server.(*Server).ListHandler-fm (5 handlers)
[GIN-debug] GET    /api/version              --> github.com/ollama/ollama/server.(*Server).GenerateRoutes.func2 (5 handlers)
[GIN-debug] HEAD   /                         --> github.com/ollama/ollama/server.(*Server).GenerateRoutes.func1 (5 handlers)
[GIN-debug] HEAD   /api/tags                 --> github.com/ollama/ollama/server.(*Server).ListHandler-fm (5 handlers)
[GIN-debug] HEAD   /api/version              --> github.com/ollama/ollama/server.(*Server).GenerateRoutes.func2 (5 handlers)
time=2024-11-11T21:50:18.710+01:00 level=INFO source=routes.go:1240 msg="Listening on 127.0.0.1:11434 (version 0.0.0)"
time=2024-11-11T21:50:18.711+01:00 level=INFO source=common.go:135 msg="extracting embedded files" dir=/tmp/ollama3024011950/runners
time=2024-11-11T21:50:18.837+01:00 level=INFO source=common.go:49 msg="Dynamic LLM libraries" runners="[cpu_avx cpu_avx2 cpu]"
time=2024-11-11T21:50:18.837+01:00 level=INFO source=gpu.go:221 msg="looking for compatible GPUs"
time=2024-11-11T21:50:19.018+01:00 level=INFO source=types.go:123 msg="inference compute" id=GPU-d421266e-e17b-d0ef-24f5-88a6f702d374 library=cuda variant=v12 compute=8.6 driver=12.4 name="NVIDIA GeForce RTX 3090" total="23.7 GiB" available="20.0 GiB"
[GIN] 2024/11/11 - 21:51:17 | 200 |      68.061µs |       127.0.0.1 | HEAD     "/"
[GIN] 2024/11/11 - 21:51:17 | 200 |   34.186091ms |       127.0.0.1 | POST     "/api/show"
time=2024-11-11T21:51:17.462+01:00 level=INFO source=sched.go:714 msg="new model will fit in available VRAM in single GPU, loading" model=/home/mmarco/.ollama/models/blobs/sha256-87048bcd55216712ef14c11c2c303728463207b165bf18440b9b84b07ec00f87 gpu=GPU-d421266e-e17b-d0ef-24f5-88a6f702d374 parallel=4 available=21468807168 required="6.2 GiB"
time=2024-11-11T21:51:17.604+01:00 level=INFO source=server.go:105 msg="system memory" total="62.7 GiB" free="50.0 GiB" free_swap="0 B"
time=2024-11-11T21:51:17.605+01:00 level=INFO source=memory.go:343 msg="offload to cuda" layers.requested=-1 layers.model=33 layers.offload=33 layers.split="" memory.available="[20.0 GiB]" memory.gpu_overhead="0 B" memory.required.full="6.2 GiB" memory.required.partial="6.2 GiB" memory.required.kv="1.0 GiB" memory.required.allocations="[6.2 GiB]" memory.weights.total="4.7 GiB" memory.weights.repeating="4.3 GiB" memory.weights.nonrepeating="411.0 MiB" memory.graph.full="560.0 MiB" memory.graph.partial="677.5 MiB"
time=2024-11-11T21:51:17.606+01:00 level=INFO source=server.go:383 msg="starting llama server" cmd="/tmp/ollama3024011950/runners/cpu_avx2/ollama_llama_server --model /home/mmarco/.ollama/models/blobs/sha256-87048bcd55216712ef14c11c2c303728463207b165bf18440b9b84b07ec00f87 --ctx-size 8192 --batch-size 512 --n-gpu-layers 33 --threads 12 --parallel 4 --port 38059"
time=2024-11-11T21:51:17.607+01:00 level=INFO source=sched.go:449 msg="loaded runners" count=1
time=2024-11-11T21:51:17.607+01:00 level=INFO source=server.go:562 msg="waiting for llama runner to start responding"
time=2024-11-11T21:51:17.607+01:00 level=INFO source=server.go:596 msg="waiting for server to become available" status="llm server error"
time=2024-11-11T21:51:17.613+01:00 level=INFO source=runner.go:863 msg="starting go runner"
time=2024-11-11T21:51:17.613+01:00 level=INFO source=runner.go:864 msg=system info="AVX = 1 | AVX_VNNI = 0 | AVX2 = 1 | AVX512 = 0 | AVX512_VBMI = 0 | AVX512_VNNI = 0 | AVX512_BF16 = 0 | FMA = 1 | NEON = 0 | SVE = 0 | ARM_FMA = 0 | F16C = 1 | FP16_VA = 0 | RISCV_VECT = 0 | WASM_SIMD = 0 | BLAS = 0 | SSE3 = 1 | SSSE3 = 1 | VSX = 0 | MATMUL_INT8 = 0 | LLAMAFILE = 1 | cgo(gcc)" threads=12
time=2024-11-11T21:51:17.613+01:00 level=INFO source=.:0 msg="Server listening on 127.0.0.1:38059"
llama_model_loader: loaded meta data with 29 key-value pairs and 291 tensors from /home/mmarco/.ollama/models/blobs/sha256-87048bcd55216712ef14c11c2c303728463207b165bf18440b9b84b07ec00f87 (version GGUF V3 (latest))
llama_model_loader: Dumping metadata keys/values. Note: KV overrides do not apply in this output.
llama_model_loader: - kv   0:                       general.architecture str              = llama
llama_model_loader: - kv   1:                               general.type str              = model
llama_model_loader: - kv   2:                               general.name str              = Meta Llama 3.1 8B Instruct
llama_model_loader: - kv   3:                           general.finetune str              = Instruct
llama_model_loader: - kv   4:                           general.basename str              = Meta-Llama-3.1
llama_model_loader: - kv   5:                         general.size_label str              = 8B
llama_model_loader: - kv   6:                            general.license str              = llama3.1
llama_model_loader: - kv   7:                               general.tags arr[str,6]       = ["facebook", "meta", "pytorch", "llam...
llama_model_loader: - kv   8:                          general.languages arr[str,8]       = ["en", "de", "fr", "it", "pt", "hi", ...
llama_model_loader: - kv   9:                          llama.block_count u32              = 32
llama_model_loader: - kv  10:                       llama.context_length u32              = 131072
llama_model_loader: - kv  11:                     llama.embedding_length u32              = 4096
llama_model_loader: - kv  12:                  llama.feed_forward_length u32              = 14336
llama_model_loader: - kv  13:                 llama.attention.head_count u32              = 32
llama_model_loader: - kv  14:              llama.attention.head_count_kv u32              = 8
llama_model_loader: - kv  15:                       llama.rope.freq_base f32              = 500000.000000
llama_model_loader: - kv  16:     llama.attention.layer_norm_rms_epsilon f32              = 0.000010
llama_model_loader: - kv  17:                          general.file_type u32              = 2
llama_model_loader: - kv  18:                           llama.vocab_size u32              = 128256
llama_model_loader: - kv  19:                 llama.rope.dimension_count u32              = 128
llama_model_loader: - kv  20:                       tokenizer.ggml.model str              = gpt2
llama_model_loader: - kv  21:                         tokenizer.ggml.pre str              = llama-bpe
llama_model_loader: - kv  22:                      tokenizer.ggml.tokens arr[str,128256]  = ["!", "\"", "#", "$", "%", "&", "'", ...
llama_model_loader: - kv  23:                  tokenizer.ggml.token_type arr[i32,128256]  = [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...
llama_model_loader: - kv  24:                      tokenizer.ggml.merges arr[str,280147]  = ["Ġ Ġ", "Ġ ĠĠĠ", "ĠĠ ĠĠ", "...
llama_model_loader: - kv  25:                tokenizer.ggml.bos_token_id u32              = 128000
llama_model_loader: - kv  26:                tokenizer.ggml.eos_token_id u32              = 128009
llama_model_loader: - kv  27:                    tokenizer.chat_template str              = {% set loop_messages = messages %}{% ...
llama_model_loader: - kv  28:               general.quantization_version u32              = 2
llama_model_loader: - type  f32:   65 tensors
llama_model_loader: - type q4_0:  225 tensors
llama_model_loader: - type q6_K:    1 tensors
time=2024-11-11T21:51:17.858+01:00 level=INFO source=server.go:596 msg="waiting for server to become available" status="llm server loading model"
llm_load_vocab: special tokens cache size = 256
llm_load_vocab: token to piece cache size = 0.7999 MB
llm_load_print_meta: format           = GGUF V3 (latest)
llm_load_print_meta: arch             = llama
llm_load_print_meta: vocab type       = BPE
llm_load_print_meta: n_vocab          = 128256
llm_load_print_meta: n_merges         = 280147
llm_load_print_meta: vocab_only       = 0
llm_load_print_meta: n_ctx_train      = 131072
llm_load_print_meta: n_embd           = 4096
llm_load_print_meta: n_layer          = 32
llm_load_print_meta: n_head           = 32
llm_load_print_meta: n_head_kv        = 8
llm_load_print_meta: n_rot            = 128
llm_load_print_meta: n_swa            = 0
llm_load_print_meta: n_embd_head_k    = 128
llm_load_print_meta: n_embd_head_v    = 128
llm_load_print_meta: n_gqa            = 4
llm_load_print_meta: n_embd_k_gqa     = 1024
llm_load_print_meta: n_embd_v_gqa     = 1024
llm_load_print_meta: f_norm_eps       = 0.0e+00
llm_load_print_meta: f_norm_rms_eps   = 1.0e-05
llm_load_print_meta: f_clamp_kqv      = 0.0e+00
llm_load_print_meta: f_max_alibi_bias = 0.0e+00
llm_load_print_meta: f_logit_scale    = 0.0e+00
llm_load_print_meta: n_ff             = 14336
llm_load_print_meta: n_expert         = 0
llm_load_print_meta: n_expert_used    = 0
llm_load_print_meta: causal attn      = 1
llm_load_print_meta: pooling type     = 0
llm_load_print_meta: rope type        = 0
llm_load_print_meta: rope scaling     = linear
llm_load_print_meta: freq_base_train  = 500000.0
llm_load_print_meta: freq_scale_train = 1
llm_load_print_meta: n_ctx_orig_yarn  = 131072
llm_load_print_meta: rope_finetuned   = unknown
llm_load_print_meta: ssm_d_conv       = 0
llm_load_print_meta: ssm_d_inner      = 0
llm_load_print_meta: ssm_d_state      = 0
llm_load_print_meta: ssm_dt_rank      = 0
llm_load_print_meta: ssm_dt_b_c_rms   = 0
llm_load_print_meta: model type       = 8B
llm_load_print_meta: model ftype      = Q4_0
llm_load_print_meta: model params     = 8.03 B
llm_load_print_meta: model size       = 4.33 GiB (4.64 BPW) 
llm_load_print_meta: general.name     = Meta Llama 3.1 8B Instruct
llm_load_print_meta: BOS token        = 128000 '<|begin_of_text|>'
llm_load_print_meta: EOS token        = 128009 '<|eot_id|>'
llm_load_print_meta: LF token         = 128 'Ä'
llm_load_print_meta: EOT token        = 128009 '<|eot_id|>'
llm_load_print_meta: EOM token        = 128008 '<|eom_id|>'
llm_load_print_meta: EOG token        = 128008 '<|eom_id|>'
llm_load_print_meta: EOG token        = 128009 '<|eot_id|>'
llm_load_print_meta: max token length = 256
llm_load_tensors: ggml ctx size =    0.14 MiB
llm_load_tensors:        CPU buffer size =  4437.80 MiB
llama_new_context_with_model: n_ctx      = 8192
llama_new_context_with_model: n_batch    = 2048
llama_new_context_with_model: n_ubatch   = 512
llama_new_context_with_model: flash_attn = 0
llama_new_context_with_model: freq_base  = 500000.0
llama_new_context_with_model: freq_scale = 1
llama_kv_cache_init:        CPU KV buffer size =  1024.00 MiB
llama_new_context_with_model: KV self size  = 1024.00 MiB, K (f16):  512.00 MiB, V (f16):  512.00 MiB
llama_new_context_with_model:        CPU  output buffer size =     2.02 MiB
llama_new_context_with_model:        CPU compute buffer size =   560.01 MiB
llama_new_context_with_model: graph nodes  = 1030
llama_new_context_with_model: graph splits = 1
time=2024-11-11T21:51:20.115+01:00 level=INFO source=server.go:601 msg="llama runner started in 2.51 seconds"
[GIN] 2024/11/11 - 21:51:20 | 200 |  2.903863177s |       127.0.0.1 | POST     "/api/generate"

```

### OS

Linux

### GPU

Nvidia

### CPU

AMD

### Ollama version

main branch (36a8372b2884c40cc5b86f6f859b012dc8125b80)

**Comment by miguelmarco** [comment]
Apparently, it detects correctly the GPU:
```
time=2024-11-11T21:50:19.018+01:00 level=INFO source=types.go:123 msg="inference compute" id=GPU-d421266e-e17b-d0ef-24f5-88a6f702d374 library=cuda variant=v12 compute=8.6 driver=12.4 name="NVIDIA GeForce RTX 3090" total="23.7 GiB" available="20.0 GiB"
```

And claims that it loads the model in the GPU memory: 

```
time=2024-11-11T21:51:17.462+01:00 level=INFO source=sched.go:714 msg="new model will fit in available VRAM in single GPU, loading" model=/home/mmarco/.ollama/models/blobs/sha256-87048bcd55216712ef14c11c2c303728463207b165bf18440b9b84b07ec00f87 gpu=GPU-d421266e-e17b-d0ef-24f5-88a6f702d374 parallel=4 available=21468807168 required="6.2 GiB"
time=2024-11-11T21:51:17.604+01:00 level=INFO source=server.go:105 msg="system memory" total="62.7 GiB" free="50.0 GiB" free_swap="0 B"
time=2024-11-11T21:51:17.605+01:00 level=INFO source=memory.go:343 msg="offload to cuda" layers.requested=-1 layers.model=33 layers.offload=33 layers.split="" memory.available="[20.0 GiB]" memory.gpu_overhead="0 B" memory.required.full="6.2 GiB" memory.required.partial="6.2 GiB" memory.required.kv="1.0 GiB" memory.required.allocations="[6.2 GiB]" memory.weights.total="4.7 GiB" memory.weights.repeating="4.3 GiB" memory.weights.nonrepeating="411.0 MiB" memory.graph.full="560.0 MiB" memory.graph.partial="677.5 MiB"
```

but the result is that it uses the CPU.

**Comment by rick-github** [comment]
```
time=2024-11-11T21:50:18.837+01:00 level=INFO source=common.go:49 msg="Dynamic LLM libraries" runners="[cpu_avx cpu_avx2 cpu]"
```
Arch Linux user?   https://github.com/ollama/ollama/issues/7564

**Comment by miguelmarco** [comment]
gentoo

I think I found part of the problem: the build scripts don't find my cuda install (which is in `/opt/cuda`).

After editing by hand some of the makefiles in the `llama/make` directory, I could trigger the build of the corresponding cuda code, but then the compilation eventually gave me this error:

```
GOARCH=amd64 CGO_LDFLAGS="-L"/home/mmarco/ollama/llama/build/linux-amd64/runners/cuda_v12/" " go build -buildmode=pie  "-ldflags=-w -s \"-X=github.com/ollama/ollama/version.Version=0.4.1-5-g36a8372-dirty\" \"-X=github.com/ollama/ollama/llama.CpuFeatures=avx\" " -trimpath -tags avx,cuda,cuda_v12 -o /home/mmarco/ollama/llama/build/linux-amd64/runners/cuda_v12/ollama_llama_server ./runner
# github.com/ollama/ollama/llama
ggml.c: En la función ‘ggml_vec_mad_f16’:
ggml.c:2378:45: aviso: el paso del argumento 1 de ‘__avx_f32cx8_load’ descarta el calificador ‘const’ del tipo del destino del puntero [-Wdiscarded-qualifiers]
 2378 |             ax[j] = GGML_F16_VEC_LOAD(x + i + j*GGML_F16_EPR, j);
      |                                             ^
ggml.c:1458:51: nota: en definición de macro ‘GGML_F32Cx8_LOAD’
 1458 | #define GGML_F32Cx8_LOAD(x)     __avx_f32cx8_load(x)
      |                                                   ^
ggml.c:2378:21: nota: en expansión de macro ‘GGML_F16_VEC_LOAD’
 2378 |             ax[j] = GGML_F16_VEC_LOAD(x + i + j*GGML_F16_EPR, j);
      |                     ^~~~~~~~~~~~~~~~~
ggml.c:1441:53: nota: se esperaba ‘ggml_fp16_t *’ {también conocido como ‘short unsigned int *’} pero el argumento es de tipo ‘const ggml_fp16_t *’ {también conocido como ‘const short unsigned int *’}
 1441 | static inline __m256 __avx_f32cx8_load(ggml_fp16_t *x) {
      |                                        ~~~~~~~~~~~~~^
# github.com/ollama/ollama/llama/runner
/usr/lib/go/pkg/tool/linux_amd64/link: running x86_64-pc-linux-gnu-g++ failed: exit status 1
/usr/bin/x86_64-pc-linux-gnu-g++ -m64 -s -Wl,-z,relro -pie -o $WORK/b001/exe/a.out -Wl,--export-dynamic-symbol=_cgo_panic -Wl,--export-dynamic-symbol=_cgo_topofstack -Wl,--export-dynamic-symbol=crosscall2 -Wl,--export-dynamic-symbol=llamaProgressCallback -Wl,--compress-debug-sections=zlib /tmp/go-link-2973296743/go.o /tmp/go-link-2973296743/000000.o /tmp/go-link-2973296743/000001.o /tmp/go-link-2973296743/000002.o /tmp/go-link-2973296743/000003.o /tmp/go-link-2973296743/000004.o /tmp/go-link-2973296743/000005.o /tmp/go-link-2973296743/000006.o /tmp/go-link-2973296743/000007.o /tmp/go-link-2973296743/000008.o /tmp/go-link-2973296743/000009.o /tmp/go-link-2973296743/000010.o /tmp/go-link-2973296743/000011.o /tmp/go-link-2973296743/000012.o /tmp/go-link-2973296743/000013.o /tmp/go-link-2973296743/000014.o /tmp/go-link-2973296743/000015.o /tmp/go-link-2973296743/000016.o /tmp/go-link-2973296743/000017.o /tmp/go-link-2973296743/000018.o /tmp/go-link-2973296743/000019.o /tmp/go-link-2973296743/000020.o /tmp/go-link-2973296743/000021.o /tmp/go-link-2973296743/000022.o /tmp/go-link-2973296743/000023.o /tmp/go-link-2973296743/000024.o /tmp/go-link-2973296743/000025.o /tmp/go-link-2973296743/000026.o /tmp/go-link-2973296743/000027.o /tmp/go-link-2973296743/000028.o /tmp/go-link-2973296743/000029.o /tmp/go-link-2973296743/000030.o /tmp/go-link-2973296743/000031.o /tmp/go-link-2973296743/000032.o /tmp/go-link-2973296743/000033.o /tmp/go-link-2973296743/000034.o /tmp/go-link-2973296743/000035.o /tmp/go-link-2973296743/000036.o /tmp/go-link-2973296743/000037.o /tmp/go-link-2973296743/000038.o /tmp/go-link-2973296743/000039.o /tmp/go-link-2973296743/000040.o /tmp/go-link-2973296743/000041.o /tmp/go-link-2973296743/000042.o /tmp/go-link-2973296743/000043.o -L/home/mmarco/ollama/llama/build/linux-amd64/runners/cuda_v12/ -lggml_cuda_v12 -L/usr/local/cuda-12/lib64 -L/home/mmarco/ollama/llama/build/Linux/amd64 -L/home/mmarco/ollama/llama/build/Linux/amd64 -lcuda -lcudart -lcublas -lcublasLt -lpthread -ldl -lrt -lresolv -L/home/mmarco/ollama/llama/build/linux-amd64/runners/cuda_v12/ -lresolv -L/home/mmarco/ollama/llama/build/linux-amd64/runners/cuda_v12/ -lpthread
/usr/lib/gcc/x86_64-pc-linux-gnu/13/../../../../x86_64-pc-linux-gnu/bin/ld: no se puede encontrar -lcudart: No existe el fichero o el directorio
/usr/lib/gcc/x86_64-pc-linux-gnu/13/../../../../x86_64-pc-linux-gnu/bin/ld: no se puede encontrar -lcublas: No existe el fichero o el directorio
/usr/lib/gcc/x86_64-pc-linux-gnu/13/../../../../x86_64-pc-linux-gnu/bin/ld: no se puede encontrar -lcublasLt: No existe el fichero o el directorio
collect2: error: ld devolvió el estado de salida 1
```

I guess it still doesn't find some of the libraries to link to. 

Any clue on what should be the right way to make the build scripts use the cuda install in that directory?

**Comment by dhiltgen** [comment]
This should be resolved by #7499

**Comment by miguelmarco** [comment]
Thank you! I am testing it now.

It didn't automatically select my cuda install, because it seems to look for a dircetory ended in `-11`or `-12` (mine is just `/opt/cuda`, but I could trick it by creating a symlink.

**Comment by miguelmarco** [comment]
And I get the error about not finding the cudart and cublas libraries.

I guess also a matter of looking at `lib` directory instead of `lib64`?

**Comment by dhiltgen** [comment]
Yes, it does currently have a hard-coded assumption of lib64 - https://github.com/ollama/ollama/pull/7499/files#diff-9ecc9a0012aabead74d0bed0e05fa907b943a0b4a82ca6244155e31b118f03f4R14

I'll see if I can soften that to prefer `lib64` then fall back to `lib` if there isn't a `lib64` present.

**Comment by dhiltgen** [comment]
Updated.  The PR should handle this scenario now.

**Comment by miguelmarco** [comment]
Actually, libcublas libcudart and libcublaslt are in `/opt/cuda/lib64`, and still the build scripts don't seem to find them.

**Comment by dhiltgen** [comment]
On that branch `make help-runners` will report what we autodetected and guid to set `CUDA_PATH` to help locate if we didn't find it by default.  If you set `CUDA_PATH=/opt/cuda` I believe that should work.

**Comment by miguelmarco** [comment]
This is the content of my `/opt`directory:

```
Signal  bin  brave  cuda  dropbox  firefox  openjdk-bin-17  openjdk-bin-17.0.13_p11  rust-bin-1.81.0  vscode
```

and of `/opt/cuda/`

```
/opt/cuda/
├── bin
│   └── crt
├── include -> targets/x86_64-linux/include
├── include.backup.0000 -> targets/x86_64-linux/include
├── lib64 -> targets/x86_64-linux/lib
├── lib64.backup.0000 -> targets/x86_64-linux/lib
├── nvml
│   └── example
├── nvvm
│   ├── bin
│   ├── include
│   ├── lib64
│   └── libdevice
└── targets
    └── x86_64-linux
        ├── include
        │   ├── CL
        │   ├── cooperative_groups
        │   ├── crt
        │   ├── cub
        │   ├── cuda
        │   ├── nv
        │   ├── nvtx3
        │   └── thrust
        └── lib
            ├── cmake
            └── stubs
```


This is what i get :

```
mmarco@neumann ~/ollama $ export CUDA_PATH=/opt/cuda/
mmarco@neumann ~/ollama $ make help-runners
The following runners will be built based on discovered GPU libraries: 'default'
(On MacOS arm64 'default' is the metal runner.  For all other platforms 'default' is one or more CPU runners)

GPU Runner CPU Flags: 'avx'  (Override with CUSTOM_CPU_FLAGS)

# CUDA_PATH sets the location where CUDA toolkits are present
CUDA_PATH=/opt/cuda/
        CUDA_11=
        CUDA_11_COMPILER=
        CUDA_12=
        CUDA_12_COMPILER=

# HIP_PATH sets the location where the ROCm toolkit is present
HIP_PATH=/opt/rocm
        HIP_COMPILER=
```

**Comment by dhiltgen** [comment]
Interesting.  So there's no symlink to expose the version of the toolkit (e.g. /opt/cuda-11 -> /opt/cuda)

It doesn't look like there's an obvious way to know the version from the filesystem without running commands and parsing output.  You can try `make help-runners CUDA_12=/opt/cuda` (assuming it's v12) and see if that looks better, and then try building with `make cuda_v12 CUDA_12=/opt/cuda`

**Comment by dhiltgen** [comment]
@miguelmarco thanks - I see the bug.  I'll get the branch updated soon to fix that.  Until then adding `GPU_COMPILER=/opt/cuda/bin/nvcc` should override the broken variable expansion.

**Comment by miguelmarco** [comment]
Thanks, that seems to work.

However, after compiling, when I try to run it and load a model, it fails with the message : 
````
Error: llama runner process has terminated: exit status 127
```

In the servrer log, the error seems to show here:

```
[GIN] 2024/11/15 - 10:39:37 | 200 |       33.19µs |       127.0.0.1 | HEAD     "/"
[GIN] 2024/11/15 - 10:39:37 | 200 |   31.050327ms |       127.0.0.1 | POST     "/api/show"
time=2024-11-15T10:39:38.231+01:00 level=INFO source=sched.go:714 msg="new model will fit in available VRAM in single GPU, loading" model=/home/mmarco/.ollama/models/blobs/sha256-87048bcd55216712ef14c11c2c303728463207b165bf18440b9b84b07ec00f87 gpu=GPU-d421266e-e17b-d0ef-24f5-88a6f702d374 parallel=4 available=24340529152 required="6.2 GiB"
time=2024-11-15T10:39:38.375+01:00 level=INFO source=server.go:105 msg="system memory" total="62.7 GiB" free="57.2 GiB" free_swap="0 B"
time=2024-11-15T10:39:38.376+01:00 level=INFO source=memory.go:343 msg="offload to cuda" layers.requested=-1 layers.model=33 layers.offload=33 layers.split="" memory.available="[22.7 GiB]" memory.gpu_overhead="0 B" memory.required.full="6.2 GiB" memory.required.partial="6.2 GiB" memory.required.kv="1.0 GiB" memory.required.allocations="[6.2 GiB]" memory.weights.total="4.7 GiB" memory.weights.repeating="4.3 GiB" memory.weights.nonrepeating="411.0 MiB" memory.graph.full="560.0 MiB" memory.graph.partial="677.5 MiB"
time=2024-11-15T10:39:38.377+01:00 level=INFO source=server.go:383 msg="starting llama server" cmd="/home/mmarco/ollama/llama/build/linux-amd64/runners/cuda_v12_avx/ollama_llama_server --model /home/mmarco/.ollama/models/blobs/sha256-87048bcd55216712ef14c11c2c303728463207b165bf18440b9b84b07ec00f87 --ctx-size 8192 --batch-size 512 --n-gpu-layers 33 --threads 12 --parallel 4 --port 35243"
time=2024-11-15T10:39:38.377+01:00 level=INFO source=sched.go:449 msg="loaded runners" count=1
time=2024-11-15T10:39:38.378+01:00 level=INFO source=server.go:562 msg="waiting for llama runner to start responding"
/home/mmarco/ollama/llama/build/linux-amd64/runners/cuda_v12_avx/ollama_llama_server: error while loading shared libraries: libggml_cuda_v12.so: cannot open shared object file: No such file or directory
time=2024-11-15T10:39:38.378+01:00 level=INFO source=server.go:596 msg="waiting for server to become available" status="llm server error"
time=2024-11-15T10:39:38.628+01:00 level=ERROR source=sched.go:455 msg="error loading llama server" error="llama runner process has terminated: exit status 127"
[GIN] 2024/11/15 - 10:39:38 | 500 |  649.996652ms |       127.0.0.1 | POST     "/api/generate"

```

It seems it didn't build the library `libggml_cuda_v12.so`.

**Comment by dhiltgen** [comment]
@miguelmarco the paths weren't quite correct to find the locally built libraries at runtime, but should be fixed now on the branch.  Give it another try and let us know how it goes.

**Comment by miguelmarco** [comment]
Now it doesn't work even giving an explicit CUDA_12 variable:

```
mmarco@neumann ~/ollama $ make help-runners CUDA_12=/opt/cuda
The following runners will be built based on discovered GPU libraries: 'default'
(On MacOS arm64 'default' is the metal runner.  For all other platforms 'default' is one or more CPU runners)

GPU Runner CPU Flags: 'avx'  (Override with CUSTOM_CPU_FLAGS)

# CUDA_PATH sets the location where CUDA toolkits are present
CUDA_PATH=/usr/local/cuda
        CUDA_11_PATH=
        CUDA_11_COMPILER=
        CUDA_12_PATH=
        CUDA_12_COMPILER=

# HIP_PATH sets the location where the ROCm toolkit is present
HIP_PATH=
        HIP_COMPILER=
```

**Comment by miguelmarco** [comment]
setting CUDA_12_PATH I get again (after some time compiling) the same mesage about not finding libraries:

```
make -j 22 cuda_v12 CUDA_12_PATH=/opt/cuda
(...)
/usr/lib/go/pkg/tool/linux_amd64/link: running x86_64-pc-linux-gnu-g++ failed: exit status 1
/usr/bin/x86_64-pc-linux-gnu-g++ -m64 -s -Wl,-z,relro -pie -o $WORK/b001/exe/a.out -Wl,--export-dynamic-symbol=_cgo_panic -Wl,--export-dynamic-symbol=_cgo_topofstack -Wl,--export-dynamic-symbol=crosscall2 -Wl,--export-dynamic-symbol=llamaProgressCallback -Wl,--compress-debug-sections=zlib /tmp/go-link-833398932/go.o /tmp/go-link-833398932/000000.o /tmp/go-link-833398932/000001.o /tmp/go-link-833398932/000002.o /tmp/go-link-833398932/000003.o /tmp/go-link-833398932/000004.o /tmp/go-link-833398932/000005.o /tmp/go-link-833398932/000006.o /tmp/go-link-833398932/000007.o /tmp/go-link-833398932/000008.o /tmp/go-link-833398932/000009.o /tmp/go-link-833398932/000010.o /tmp/go-link-833398932/000011.o /tmp/go-link-833398932/000012.o /tmp/go-link-833398932/000013.o /tmp/go-link-833398932/000014.o /tmp/go-link-833398932/000015.o /tmp/go-link-833398932/000016.o /tmp/go-link-833398932/000017.o /tmp/go-link-833398932/000018.o /tmp/go-link-833398932/000019.o /tmp/go-link-833398932/000020.o /tmp/go-link-833398932/000021.o /tmp/go-link-833398932/000022.o /tmp/go-link-833398932/000023.o /tmp/go-link-833398932/000024.o /tmp/go-link-833398932/000025.o /tmp/go-link-833398932/000026.o /tmp/go-link-833398932/000027.o /tmp/go-link-833398932/000028.o /tmp/go-link-833398932/000029.o /tmp/go-link-833398932/000030.o /tmp/go-link-833398932/000031.o /tmp/go-link-833398932/000032.o /tmp/go-link-833398932/000033.o /tmp/go-link-833398932/000034.o /tmp/go-link-833398932/000035.o /tmp/go-link-833398932/000036.o /tmp/go-link-833398932/000037.o /tmp/go-link-833398932/000038.o /tmp/go-link-833398932/000039.o /tmp/go-link-833398932/000040.o /tmp/go-link-833398932/000041.o /tmp/go-link-833398932/000042.o /tmp/go-link-833398932/000043.o -L./build/linux-amd64/runners/cuda_v12_avx/ -lggml_cuda_v12 -L/usr/local/cuda-12/lib64 -L/home/mmarco/ollama/llama/build/linux-amd64 -lcuda -lcudart -lcublas -lcublasLt -lpthread -ldl -lrt -lresolv -L./build/linux-amd64/runners/cuda_v12_avx/ -lresolv -L./build/linux-amd64/runners/cuda_v12_avx/ -lpthread
/usr/lib/gcc/x86_64-pc-linux-gnu/12/../../../../x86_64-pc-linux-gnu/bin/ld: no se puede encontrar -lcudart: No existe el fichero o el directorio
/usr/lib/gcc/x86_64-pc-linux-gnu/12/../../../../x86_64-pc-linux-gnu/bin/ld: no se puede encontrar -lcublas: No existe el fichero o el directorio
/usr/lib/gcc/x86_64-pc-linux-gnu/12/../../../../x86_64-pc-linux-gnu/bin/ld: no se puede encontrar -lcublasLt: No existe el fichero o el directorio
collect2: error: ld devolvió el estado de salida 1

make[2]: *** [make/gpu.make:69: build/linux-amd64/runners/cuda_v12_avx/ollama_llama_server] Error 1
make[1]: *** [Makefile:51: cuda_v12] Error 2
make: *** [Makefile:4: cuda_v12] Error 2
```

**Comment by navr32** [comment]
hi all !
Working on manjaro aka Archlinux.
 I just come to upgrade my source git ollama  from v0.3.14-11-g3085c47b to main.
 And i have the same problem than @miguelmarco  .
The gpu runner cuda_v12  is not builded.
 So when start ollama serve just  runners "cpu cpu_avx cpu_avx2"  is present. 

I have try many tags..cpu def to try but nothing work.   
I have try @dhiltgen  branch "make_target" and "info_ux" but same problems. 

The make help-runners give no target .

**Comment by maxer456** [comment]
Hello, I also have the same linking issue, also on Gentoo.
It looks like the linking path doesn't come from the makefiles, but from `llama/llama.go`:
https://github.com/dhiltgen/ollama/blob/2a0716598ab7128f91012310e7ce44bda5046142/llama/llama.go#L29

As a workaround, changing that to my cuda directory (/opt/cuda/lib64) works. Then the cuda_v12 target (using `CUDA_12_PATH`) compiles, `go build .` works as well and running `OLLAMA_DEBUG=1 ./ollama serve` confirms the runner starts successfully. I also tested running the `llama3.2:1b` model and that works just fine, executing the model on the GPU.

**Comment by maxer456** [comment]
With the latest changes on @dhiltgen's `make_targets` branch, compilation works for me with just supplying `CUDA_12_PATH`, including `make cuda_v12`, `make all` and `make dist`.
Thank you!

**Comment by navr32** [comment]
### Success with the latest branch!

I wanted to thank @dhiltgen and all other contributors for their amazing work! After testing the latest branch, everything compiles and runs fine now, even without an AVX processor, with 
full GPU acceleration on my Nvidia GPUs. Thanks again!

### Environment

I'm currently running Manjaro, an Arch distribution.

### Steps to test

To test, I followed these steps:

1. **Clone the repository**: `git clone https://github.com/dhiltgen/ollama`
2. **Switch to the make_targets branch**: `cd ollama/` then `git checkout make_targets`

### Verify CUDA detection

To verify that the CUDA path is correct and detected, I ran:

```bash
make CUDA_12_PATH=/opt/cuda help-runners
```

This responded with:

```
The following runners will be built based on discovered GPU libraries: 'cpu cuda_v12 rocm'
```

This confirms that CUDA is properly detected!

### Build and run

Finally, I built with the following options:

```bash
make -j16 CUSTOM_CPU_FLAGS="" CUDA_12_PATH=/opt/cuda cuda_v12
go build .
```

And everything works fine! All GPUs are detected and models run on the GPU without AVX. Congratulations!

**Comment by kelvin-bbn** [comment]
Hello @dhiltgen. Thank you for your work on CPUs without AVX. I cloned the git repository but  I cannot get "git checkout make_targets" to work and there is no Makefile. I am new to compiling without a Makefile so I maybe doing things wrong. I am running a Ubuntu 24,04 on an old Intel machine with an RTX3050. I need some examples. 

Thank you!

**Comment by rick-github** [comment]
https://github.com/ollama/ollama/blob/main/docs/development.md#advanced-cpu-vector-settings

**Comment by Gbrothers1** [comment]
Git checkout make_targets also not working 
root@AI-SEVER ~/ollama (main)# git checkout make_targets                                                                                 (cuda_env) 
error: pathspec 'make_targets' did not match any file(s) known to git

**Comment by rick-github** [comment]
https://github.com/ollama/ollama/blob/main/docs/development.md#advanced-cpu-vector-settings

**Comment by kelvin-bbn** [comment]
@rick-github How does make work without a Makefile to guide it. I  still get the following error:

make -j16 CUSTOM_CPU_FLAGS="" CUDA_12_PATH=/usr/local/cuda-12.6/ cuda_v12
make: *** No rule to make target 'cuda_v12'.  Stop.

I have golang and cuda installed and in the path. 
Thank you!

**Comment by rick-github** [comment]
```console
make -j16 CUSTOM_CPU_FLAGS="" CUDA_12_PATH=/usr/local/cuda-12.6/ RUNNER_TARGETS=cuda_v12 runners
```

**Comment by kelvin-bbn** [comment]
@rick-github  From the ~/ollama directory, I got the following error:

make -j16 CUSTOM_CPU_FLAGS="" CUDA_12_PATH=/usr/local/cuda-12.6/ RUNNER_TARGETS=cuda_v12 runners
make: *** No rule to make target 'runners'.  Stop.

**Comment by rick-github** [comment]
Is your repo up to date?  `git log -n 1` to see where your repo is at, `git pull` to sync with remote head.

**Comment by kelvin-bbn** [comment]
It is up to date:
git pull
Already up to date.

git log -n 1
commit 608e87bf8707e377f1c195ae22330e26f67de91e (HEAD -> main, origin/main, origin/HEAD)
Author: Patrick Devine <patrick@infrahq.com>
Date:   Thu Sep 5 17:02:28 2024 -0700

    Fix gemma2 2b conversion (#6645)

**Comment by rick-github** [comment]
https://github.com/ollama/ollama.git

**Comment by kelvin-bbn** [comment]
It's compiling. Thank you @rick-github

**Comment by aaronchantrill** [comment]
I'm on https://github.com/ollama/ollama and cannot find the "make_targets" branch. Did something change in the last couple of days?

**Comment by rick-github** [comment]
There is no make_targets branch on the ollama repo, that's on dhiltgen's repo.

**Comment by iamangus** [comment]
Are there plans to provide a container image built with these flags? (or lack there of)

**Comment by rick-github** [comment]
Patch #8284 into the repo and build a docker image:
```
docker build --build-arg VERSION=noavx --build-arg CUSTOM_CPU_FLAGS= --build-arg OLLAMA_SKIP_ROCM_GENERATE=1 --build-arg OLLAMA_FAST_BUILD=1 --platform=linux/amd64 -t ollama-noavx .
```

**Comment by rick-github** [comment]
```
git clone https://github.com/ollama/ollama.git
cd ollama
make -j16 CUSTOM_CPU_FLAGS="" CUDA_12_PATH=/usr/local/cuda-12.6/ RUNNER_TARGETS=cuda_v12 runners
```

**Comment by ppereirasky** [comment]
I think in Windows environment it would be like this:
make -j16 CUSTOM_CPU_FLAGS="" CUDA_12_PATH="C:\\Progra~1\\NVIDIA~2\\CUDA\\v12.8" CUDA_12_COMPILER="C:\\Progra~1\\NVIDIA~2\\CUDA\\v12.8\\bin\\nvcc.exe"
Right?

**Comment by rick-github** [comment]
I'm not a Windows guy.  Try it and see what happens.

**Comment by ppereirasky** [comment]
OK - for me - with an RTX GPU, a Celeron G3930 (no avx support and only 2 cores 2 threads) and Windows 10 I think the best is to install the Cuda Toolkit in a folder on C: like C:\CudaToolkit (no spaces) and then compile and build like this:

`make -j2 CUSTOM_CPU_FLAGS="" CUDA_12_PATH="C:\\CudaToolkit\\CUDA\\v12.8" CUDA_12_COMPILER="C:\\CudaToolkit\\CUDA\\v12.8\\bin\\nvcc.exe" CUDA_ARCHITECTURES="89;90;90a"`

It detects 2 runners to build automatically **cpu** and **cuda_v12** and it finishes without errors - however it takes "ages" to complete. I'm also only building for CUDA_ARCHITECTURES 89;90;90a because my RTX is the 4060 Ti 16Gb, so no need for the older ones - without this it would compile for every CUDA generation which would take much longer.

**Comment by Thot-Htp** [comment]
@ppereirasky, how did you get the parameters for CUDA_ARCHITECTURES? I have an RTX 3060 Ti, but in general where can they be found?

Thanks

**Comment by rick-github** [comment]
https://developer.nvidia.com/cuda-gpus

A 3060 starts at 86 (8.6).

**Comment by Thot-Htp** [comment]
@rick-github  Ah, so "architecture" = "compute capability" x 10

Thanks
