### ISSUE TITLE
Installing bolt.new and qwen2.5-coder:7b locally (error cudaMalloc failed: out of memory)

### ISSUE THREAD

**Issue by LieLust** [ollama/ollama#7896]
#### Description:
I am trying to install **bolt.new** and **qwen2.5-coder:7b** locally, but I get the following error:  
`{"error":"llama runner process has terminated: cudaMalloc failed: out of memory"}`.

The installation of **qwen2.5-coder:7b** fails with this memory error during execution.

#### Environment:
- **Operating System**: Windows
- **Git version**: 2.47.1.windows.1
- **Node version**: v22.11.0
- **pnpm version**: 9.14.4
- **Ollama version**: 0.4.6
- **CPU**: AMD Ryzen 7 7800X3D
- **GPU**: AMD Radeon RX 7900 XTX (24GB VRAM)
- **RAM**: 32Go

#### Context and steps followed:
1. I followed the provided installation guide: [Google Document Guide](https://docs.google.com/document/d/19UNRP1c6ulDS_X7Ig7mRTI_EaT0xcvgimnfOJDKm7ig/edit?tab=t.0).
2. I attempted to install **qwen2.5-coder:7b** by following the steps, but the following error occurred: `{"error":"llama runner process has terminated: cudaMalloc failed: out of memory"}`
3. I suspect this error is related to GPU memory management, but since my **AMD Radeon RX 7900 XTX** has 24GB of VRAM, it doesn't seem to be a capacity issue.

#### Error details:
- The **cudaMalloc failed: out of memory** error seems to indicate an issue with memory allocation on the GPU.
- Despite having sufficient VRAM resources, the error persists during execution.

#### Request:
- Are there any specific steps or configurations to resolve this memory issue with **qwen2.5-coder:7b**?
- Is this a known issue for AMD graphics cards, and are there any recommended solutions or workarounds?

Thank you for your help and suggestions!

### OS

Windows

### GPU

AMD

### CPU

AMD

### Ollama version

0.4.6

**Comment by rick-github** [comment]
[Server logs](https://github.com/ollama/ollama/blob/main/docs/troubleshooting.md#how-to-troubleshoot-issues) will aid in debugging.

**Comment by rick-github** [comment]
`OLLAMA_NUM_PARALLEL` is unset so ollama is using a default of 4.  Your client is requesting a context size of 32768, so ollama is allocating a total context buffer of (4 * 32768) or 131072 tokens, which takes 7GB.  When llama.cpp tries to allocate this buffer, it finds there is not enough VRAM available.  ollama made a calculated guess at memory requirements and got it wrong.  There are several mitigation techniques.
1. Set `OLLAMA_NUM_PARALLEL=1` in the [server environment](https://github.com/ollama/ollama/blob/main/docs/faq.md#how-do-i-configure-ollama-server).
2. Configure bolt.ai to use a smaller context window.
3. Set [`OLLAMA_GPU_OVERHEAD`](https://github.com/ollama/ollama/blob/5f8051180e3b9aeafc153f6b5056e7358a939c88/envconfig/config.go#L237) to give llama.cpp a buffer to grow in to (eg, `OLLAMA_GPU_OVERHEAD=536870912` to reserve 512M)
4. Reduce the number layers that ollama thinks it can offload to the GPU, see [here](https://github.com/ollama/ollama/issues/6950#issuecomment-2373663650).  Ollama is currently offloading 29 layers, try setting `num_gpu` to 25.

**Comment by LieLust** [comment]
Hello,
After a thorough investigation, the issue wasn’t where I was looking.
It turns out that, for some unknown reason, my graphics card drivers were initially on version 24.8. At that time, everything was working correctly. Then, there was an update to version 24.10, which caused the problem. After going through GitHub issues and forums, I discovered that this update had broken everything.
I then performed another update. I’m currently on version 24.12.1, and everything is working again (even the qwen2.5-coder:32b model).

However, it seems like it’s not using the VRAM. Do you have a solution for this issue?

Here are two screenshots while qwen2.5-coder:32b is running.
![{0E760DD3-D0EF-43E0-B09E-042A34E5AE0A}](https://github.com/user-attachments/assets/41b12cc5-8388-411b-a62e-d7b6a763d488)
![{AE46F84D-413B-4AF4-8DA9-E7F90836455B}](https://github.com/user-attachments/assets/9b988c60-fb7e-4c02-91c9-e3f452c772f2)

**Comment by rick-github** [comment]
[Server logs](https://github.com/ollama/ollama/blob/main/docs/troubleshooting.md#how-to-troubleshoot-issues) will aid in debugging.
