### ISSUE TITLE
Ollama with AMD GPU Issue

### ISSUE THREAD

**Issue by kannszzz** [ollama/ollama#8263]
[Ollama.log](https://github.com/user-attachments/files/18268220/Ollama.log)
### What is the issue?

Environment: Debian 12 virtualized on proxmox with GPU passthrough
GPU: 6650 XT (Unsupported) Using Environment="HSA_OVERRIDE_GFX_VERSION=10.3.0"

Systemd log: 
`Dec 28 15:03:19 AI-ML ollama[2378]: time=2024-12-28T15:03:19.515-05:00 level=INFO source=routes.go:1310 msg="Listening on [::]:11434 (version 0.5.4)"
Dec 28 15:03:19 AI-ML ollama[2378]: time=2024-12-28T15:03:19.516-05:00 level=INFO source=common.go:131 msg="GPU runner incompatible with host system, CPU does not have AVX" runner=cuda_v11_avx
Dec 28 15:03:19 AI-ML ollama[2378]: time=2024-12-28T15:03:19.516-05:00 level=INFO source=common.go:131 msg="GPU runner incompatible with host system, CPU does not have AVX" runner=cuda_v12_avx
Dec 28 15:03:19 AI-ML ollama[2378]: time=2024-12-28T15:03:19.516-05:00 level=INFO source=routes.go:1339 msg="Dynamic LLM libraries" runners="[cpu_avx2 rocm_avx cpu cpu_avx]"
Dec 28 15:03:19 AI-ML ollama[2378]: time=2024-12-28T15:03:19.516-05:00 level=INFO source=gpu.go:226 msg="looking for compatible GPUs"
Dec 28 15:03:19 AI-ML ollama[2378]: time=2024-12-28T15:03:19.523-05:00 level=INFO source=amd_linux.go:391 msg="skipping rocm gfx compatibility check" HSA_OVERRIDE_GFX_VERSION=10.3.0
Dec 28 15:03:19 AI-ML ollama[2378]: time=2024-12-28T15:03:19.527-05:00 level=INFO source=types.go:131 msg="inference compute" id=0 library=rocm variant="" compute=gfx1032 driver=6.10 name=1002:73ef total="8.0 GiB available="7.9 GiB`

When I try running any model even the lightest one smol I get the following error,
`Error: llama runner process has terminated: signal: illegal instruction
`

Checked the journalctl log
`Dec 28 15:17:30 AI-ML ollama[788]: [GIN-debug] POST   /api/pull                 --> github.com/ollama/ollama/server.(*Server).PullHandler-fm (5 handlers)
Dec 28 15:17:30 AI-ML ollama[788]: [GIN-debug] POST   /api/generate             --> github.com/ollama/ollama/server.(*Server).GenerateHandler-fm (5 handlers)
Dec 28 15:17:30 AI-ML ollama[788]: [GIN-debug] POST   /api/chat                 --> github.com/ollama/ollama/server.(*Server).ChatHandler-fm (5 handlers)
Dec 28 15:17:30 AI-ML ollama[788]: [GIN-debug] POST   /api/embed                --> github.com/ollama/ollama/server.(*Server).EmbedHandler-fm (5 handlers)
Dec 28 15:17:30 AI-ML ollama[788]: [GIN-debug] POST   /api/embeddings           --> github.com/ollama/ollama/server.(*Server).EmbeddingsHandler-fm (5 handlers)
Dec 28 15:17:30 AI-ML ollama[788]: [GIN-debug] POST   /api/create               --> github.com/ollama/ollama/server.(*Server).CreateHandler-fm (5 handlers)
Dec 28 15:17:30 AI-ML ollama[788]: [GIN-debug] POST   /api/push                 --> github.com/ollama/ollama/server.(*Server).PushHandler-fm (5 handlers)
Dec 28 15:17:30 AI-ML ollama[788]: [GIN-debug] POST   /api/copy                 --> github.com/ollama/ollama/server.(*Server).CopyHandler-fm (5 handlers)
Dec 28 15:17:30 AI-ML ollama[788]: [GIN-debug] DELETE /api/delete               --> github.com/ollama/ollama/server.(*Server).DeleteHandler-fm (5 handlers)
Dec 28 15:17:30 AI-ML ollama[788]: [GIN-debug] POST   /api/show                 --> github.com/ollama/ollama/server.(*Server).ShowHandler-fm (5 handlers)
Dec 28 15:17:30 AI-ML ollama[788]: [GIN-debug] POST   /api/blobs/:digest        --> github.com/ollama/ollama/server.(*Server).CreateBlobHandler-fm (5 handlers)
Dec 28 15:17:30 AI-ML ollama[788]: [GIN-debug] HEAD   /api/blobs/:digest        --> github.com/ollama/ollama/server.(*Server).HeadBlobHandler-fm (5 handlers)
Dec 28 15:17:30 AI-ML ollama[788]: [GIN-debug] GET    /api/ps                   --> github.com/ollama/ollama/server.(*Server).PsHandler-fm (5 handlers)
Dec 28 15:17:30 AI-ML ollama[788]: [GIN-debug] POST   /v1/chat/completions      --> github.com/ollama/ollama/server.(*Server).ChatHandler-fm (6 handlers)
Dec 28 15:17:30 AI-ML ollama[788]: [GIN-debug] POST   /v1/completions           --> github.com/ollama/ollama/server.(*Server).GenerateHandler-fm (6 handlers)
Dec 28 15:17:30 AI-ML ollama[788]: [GIN-debug] POST   /v1/embeddings            --> github.com/ollama/ollama/server.(*Server).EmbedHandler-fm (6 handlers)
Dec 28 15:17:30 AI-ML ollama[788]: [GIN-debug] GET    /v1/models                --> github.com/ollama/ollama/server.(*Server).ListHandler-fm (6 handlers)
Dec 28 15:17:30 AI-ML ollama[788]: [GIN-debug] GET    /v1/models/:model         --> github.com/ollama/ollama/server.(*Server).ShowHandler-fm (6 handlers)
Dec 28 15:17:30 AI-ML ollama[788]: [GIN-debug] GET    /                         --> github.com/ollama/ollama/server.(*Server).GenerateRoutes.func1 (5 handlers)
Dec 28 15:17:30 AI-ML ollama[788]: [GIN-debug] GET    /api/tags                 --> github.com/ollama/ollama/server.(*Server).ListHandler-fm (5 handlers)
Dec 28 15:17:30 AI-ML ollama[788]: [GIN-debug] GET    /api/version              --> github.com/ollama/ollama/server.(*Server).GenerateRoutes.func2 (5 handlers)
Dec 28 15:17:30 AI-ML ollama[788]: [GIN-debug] HEAD   /                         --> github.com/ollama/ollama/server.(*Server).GenerateRoutes.func1 (5 handlers)
Dec 28 15:17:30 AI-ML ollama[788]: [GIN-debug] HEAD   /api/tags                 --> github.com/ollama/ollama/server.(*Server).ListHandler-fm (5 handlers)
Dec 28 15:17:30 AI-ML ollama[788]: [GIN-debug] HEAD   /api/version              --> github.com/ollama/ollama/server.(*Server).GenerateRoutes.func2 (5 handlers)
Dec 28 15:17:30 AI-ML ollama[788]: time=2024-12-28T15:17:30.915-05:00 level=INFO source=routes.go:1310 msg="Listening on [::]:11434 (version 0.5.4)"
Dec 28 15:17:30 AI-ML ollama[788]: time=2024-12-28T15:17:30.917-05:00 level=INFO source=common.go:131 msg="GPU runner incompatible with host system, CPU does not have AVX" runner=cuda_v11_avx
Dec 28 15:17:30 AI-ML ollama[788]: time=2024-12-28T15:17:30.917-05:00 level=INFO source=common.go:131 msg="GPU runner incompatible with host system, CPU does not have AVX" runner=cuda_v12_avx
Dec 28 15:17:30 AI-ML ollama[788]: time=2024-12-28T15:17:30.917-05:00 level=INFO source=routes.go:1339 msg="Dynamic LLM libraries" runners="[rocm_avx cpu cpu_avx cpu_avx2]"
Dec 28 15:17:30 AI-ML ollama[788]: time=2024-12-28T15:17:30.918-05:00 level=INFO source=gpu.go:226 msg="looking for compatible GPUs"
Dec 28 15:17:30 AI-ML ollama[788]: time=2024-12-28T15:17:30.928-05:00 level=INFO source=amd_linux.go:391 msg="skipping rocm gfx compatibility check" HSA_OVERRIDE_GFX_VERSION=10.3.0
Dec 28 15:17:30 AI-ML ollama[788]: time=2024-12-28T15:17:30.933-05:00 level=INFO source=types.go:131 msg="inference compute" id=0 library=rocm variant="" compute=gfx1032 driver=6.10 name=1002:73ef total="8.0 GiB" >
Dec 28 15:18:14 AI-ML ollama[788]: [GIN] 2024/12/28 - 15:18:14 | 200 |     811.616µs |       127.0.0.1 | HEAD     "/"
Dec 28 15:18:14 AI-ML ollama[788]: [GIN] 2024/12/28 - 15:18:14 | 200 |   23.292812ms |       127.0.0.1 | POST     "/api/show"
Dec 28 15:18:14 AI-ML ollama[788]: time=2024-12-28T15:18:14.092-05:00 level=INFO source=sched.go:714 msg="new model will fit in available VRAM in single GPU, loading" model=/usr/share/ollama/.ollama/models/blobs/s>
Dec 28 15:18:14 AI-ML ollama[788]: time=2024-12-28T15:18:14.092-05:00 level=INFO source=server.go:104 msg="system memory" total="31.3 GiB" free="29.5 GiB" free_swap="0 B"
Dec 28 15:18:14 AI-ML ollama[788]: time=2024-12-28T15:18:14.093-05:00 level=INFO source=memory.go:356 msg="offload to rocm" layers.requested=-1 layers.model=29 layers.offload=29 layers.split="" memory.available="[>
Dec 28 15:18:14 AI-ML ollama[788]: time=2024-12-28T15:18:14.093-05:00 level=INFO source=common.go:131 msg="GPU runner incompatible with host system, CPU does not have AVX" runner=cuda_v11_avx
Dec 28 15:18:14 AI-ML ollama[788]: time=2024-12-28T15:18:14.093-05:00 level=INFO source=common.go:131 msg="GPU runner incompatible with host system, CPU does not have AVX" runner=cuda_v12_avx
Dec 28 15:18:14 AI-ML ollama[788]: time=2024-12-28T15:18:14.093-05:00 level=INFO source=common.go:131 msg="GPU runner incompatible with host system, CPU does not have AVX" runner=cuda_v11_avx
Dec 28 15:18:14 AI-ML ollama[788]: time=2024-12-28T15:18:14.093-05:00 level=INFO source=common.go:131 msg="GPU runner incompatible with host system, CPU does not have AVX" runner=cuda_v12_avx
Dec 28 15:18:14 AI-ML ollama[788]: time=2024-12-28T15:18:14.093-05:00 level=INFO source=server.go:376 msg="starting llama server" cmd="/usr/local/lib/ollama/runners/rocm_avx/ollama_llama_server runner --model /usr>
Dec 28 15:18:14 AI-ML ollama[788]: time=2024-12-28T15:18:14.094-05:00 level=INFO source=sched.go:449 msg="loaded runners" count=1
Dec 28 15:18:14 AI-ML ollama[788]: time=2024-12-28T15:18:14.094-05:00 level=INFO source=server.go:555 msg="waiting for llama runner to start responding"
Dec 28 15:18:14 AI-ML ollama[788]: time=2024-12-28T15:18:14.095-05:00 level=INFO source=server.go:589 msg="waiting for server to become available" status="llm server error"
Dec 28 15:18:14 AI-ML ollama[788]: time=2024-12-28T15:18:14.346-05:00 level=ERROR source=sched.go:455 msg="error loading llama server" error="llama runner process has terminated: signal: illegal instruction"
Dec 28 15:18:14 AI-ML ollama[788]: [GIN] 2024/12/28 - 15:18:14 | 500 |  305.479625ms |       127.0.0.1 | POST     "/api/generate"
Dec 28 15:18:19 AI-ML ollama[788]: time=2024-12-28T15:18:19.347-05:00 level=WARN source=sched.go:646 msg="gpu VRAM usage didn't recover within timeout" seconds=5.000717787 model=/usr/share/ollama/.ollama/models/bl>
Dec 28 15:18:19 AI-ML ollama[788]: time=2024-12-28T15:18:19.597-05:00 level=WARN source=sched.go:646 msg="gpu VRAM usage didn't recover within timeout" seconds=5.250446487 model=/usr/share/ollama/.ollama/models/bl>
Dec 28 15:18:19 AI-ML ollama[788]: time=2024-12-28T15:18:19.846-05:00 level=WARN source=sched.go:646 msg="gpu VRAM usage didn't recover within timeout" seconds=5.500215086 model=/usr/share/ollama/.ollama/models/bl`

Not sure if I am missing any config but seems like vram is running out but model ram for llama3.2 is around 3-4 gb. 

### OS

Linux

### GPU

AMD

### CPU

Intel

### Ollama version

0.5.4

**Comment by rick-github** [comment]
Please follow [these instructions](https://github.com/ollama/ollama/blob/main/docs/troubleshooting.md#how-to-troubleshoot-issues) on how to retrieve logs, and add them as an attachment.

**Comment by kannszzz** [comment]
Attached in the original post.

**Comment by rick-github** [comment]
```
Dec 28 20:26:23 AI-ML ollama[801]: time=2024-12-28T20:26:23.083-05:00 level=INFO source=common.go:131 msg="GPU runner incompatible with host system, CPU does not have AVX" runner=cuda_v11_avx
Dec 28 20:26:23 AI-ML ollama[801]: time=2024-12-28T20:26:23.083-05:00 level=INFO source=common.go:131 msg="GPU runner incompatible with host system, CPU does not have AVX" runner=cuda_v12_avx
Dec 28 20:26:23 AI-ML ollama[801]: time=2024-12-28T20:26:23.335-05:00 level=ERROR source=sched.go:455 msg="error loading llama server" error="llama runner process has terminated: signal: illegal instruction"
```
The runners have been compiled for CPUs with AVX extensions, which apparently your CPU doesn't have, so the runner dies with SIGILL.   [Enable avx/avx2](https://pve.proxmox.com/pve-docs/cpu-models.conf.5.html#_example_file) on your VE or see [here](https://github.com/ollama/ollama/blob/main/docs/development.md#advanced-cpu-vector-settings) for instructions on building a custom ollama without AVX.

**Comment by kannszzz** [comment]
Thank you sir, that did the trick. I passed the host CPU which supported av2 and its working. Appreciate the quick reply.
