### ISSUE TITLE
AMD RX 6750 GPU not recognized by Ollama on Arch Linux despite HSA_OVERRIDE_GFX_VERSION

### ISSUE THREAD

**Issue by Guedxx** [ollama/ollama#8679]
### What is the issue?

I'm running Arch Linux with an AMD RX 6750 GPU. Ollama fails to recognize my GPU as compatible, even after setting the Environment="HSA_OVERRIDE_GFX_VERSION=10.3.0" environment variable. I've tried several steps to resolve the issue, but nothing has worked so far.

time=2025-01-29T21:15:25.499-03:00 level=INFO source=gpu.go:226 msg="looking for compatible GPUs"
time=2025-01-29T21:15:25.520-03:00 level=WARN source=amd_linux.go:61 msg="ollama recommends running the https://www.amd.com/en/support/linux-drivers" error="amdgpu version file missing: /sys/module/amdgpu/version stat /sys/module/amdgpu/version: no such file or directory"
time=2025-01-29T21:15:25.522-03:00 level=WARN source=amd_linux.go:378 msg="amdgpu is not supported (supported types:[gfx1010 gfx1012 gfx1030 gfx1100 gfx1101 gfx1102 gfx900 gfx906 gfx908 gfx90a gfx940 gfx941 gfx942])" gpu_type=gfx1031 gpu=0 library=/opt/rocm/lib
time=2025-01-29T21:15:25.522-03:00 level=WARN source=amd_linux.go:385 msg="See https://github.com/ollama/ollama/blob/main/docs/gpu.md#overrides for HSA_OVERRIDE_GFX_VERSION usage"
time=2025-01-29T21:15:25.522-03:00 level=INFO source=amd_linux.go:404 msg="no compatible amdgpu devices detected"
time=2025-01-29T21:15:25.522-03:00 level=INFO source=gpu.go:392 msg="no compatible GPUs were discovered"

### OS

Arch Linux

### GPU

AMD

### CPU

AMD

### Ollama version

0.5.7

**Comment by rick-github** [comment]
`HSA_OVERRIDE_GFX_VERSION` is not set in the server environment.  If it was, it wouldn't print the "amdgpu is not supported" line.  At the head of the log file it will show the environment variables, confirm that HSA_OVERRIDE_GFX_VERSION is set correctly.

**Comment by Guedxx** [comment]
The model inside my ollama.service is

.
.
[Service]
Environment="HSA_OVERRIDE_GFX_VERSION=10.3.0"
.
.
.

**Comment by rick-github** [comment]
At the head of the log file it will show the environment variables, confirm that HSA_OVERRIDE_GFX_VERSION is set correctly.

**Comment by Guedxx** [comment]
2025/01/30 21:03:27 routes.go:1187: INFO server config env="map[CUDA_VISIBLE_DEVICES: GPU_DEVICE_ORDINAL: HIP_VISIBLE_DEVICES: HSA_OVERRIDE_GFX_VERSION: HTTPS_PROXY: HTTP_PROXY: NO_PROXY: OLLAMA_DEBUG:false OLLAMA_FLASH_ATTENTION:false OLLAMA_GPU_OVERHEAD:0 OLLAMA_HOST:http://127.0.0.1:11434 OLLAMA_INTEL_GPU:false OLLAMA_KEEP_ALIVE:5m0s OLLAMA_KV_CACHE_TYPE: OLLAMA_LLM_LIBRARY: OLLAMA_LOAD_TIMEOUT:5m0s OLLAMA_MAX_LOADED_MODELS:0 OLLAMA_MAX_QUEUE:512 OLLAMA_MODELS:/home/.ollama/models OLLAMA_MULTIUSER_CACHE:false OLLAMA_NOHISTORY:false OLLAMA_NOPRUNE:false OLLAMA_NUM_PARALLEL:0 OLLAMA_ORIGINS:[http://localhost https://localhost http://localhost:* https://localhost:* http:// https:// http://* https://:* http://0.0.0.0 https://0.0.0.0 http://0.0.0.0:* https://0.0.0.0:* app://* file://* tauri://* vscode-webview://*] OLLAMA_SCHED_SPREAD:false ROCR_VISIBLE_DEVICES: http_proxy: https_proxy: no_proxy:]"
time=2025-01-30T21:03:27.938-03:00 level=INFO source=images.go:432 msg="total blobs: 5"
time=2025-01-30T21:03:27.938-03:00 level=INFO source=images.go:439 msg="total unused blobs removed: 0"
time=2025-01-30T21:03:27.939-03:00 level=INFO source=routes.go:1238 msg="Listening on 127.0.0.1:11434 (version 0.5.7)"
time=2025-01-30T21:03:27.940-03:00 level=INFO source=routes.go:1267 msg="Dynamic LLM libraries" runners="[cpu cpu_avx cpu_avx2 rocm_avx]"
time=2025-01-30T21:03:27.941-03:00 level=INFO source=gpu.go:226 msg="looking for compatible GPUs"
time=2025-01-30T21:03:27.965-03:00 level=WARN source=amd_linux.go:61 msg="ollama recommends running the https://www.amd.com/en/support/linux-drivers" error="amdgpu version file missing: /sys/module/amdgpu/version stat /sys/module/amdgpu/version: no such file or directory"
time=2025-01-30T21:03:27.970-03:00 level=WARN source=amd_linux.go:378 msg="amdgpu is not supported (supported types:[gfx1010 gfx1012 gfx1030 gfx1100 gfx1101 gfx1102 gfx900 gfx906 gfx908 gfx90a gfx940 gfx941 gfx942])" gpu_type=gfx1031 gpu=0 library=/opt/rocm/lib
time=2025-01-30T21:03:27.970-03:00 level=WARN source=amd_linux.go:385 msg="See https://github.com/ollama/ollama/blob/main/docs/gpu.md#overrides for HSA_OVERRIDE_GFX_VERSION usage"
time=2025-01-30T21:03:27.970-03:00 level=INFO source=amd_linux.go:404 msg="no compatible amdgpu devices detected"
time=2025-01-30T21:03:27.970-03:00 level=INFO source=gpu.go:392 msg="no compatible GPUs were discovered"
time=2025-01-30T21:03:27.970-03:00 level=INFO source=types.go:131 msg="inference compute" id=0 library=cpu variant=avx2 compute="" driver=0.0 name="" total="15.5 GiB" available="13.9 GiB"

**Comment by Guedxx** [comment]
### /usr/lib/systemd/system/ollama.service
# [Unit]
# Description=Ollama Service
# Wants=network-online.target
# After=network.target network-online.target
#
# [Service]
# ExecStart=/usr/bin/ollama serve
# WorkingDirectory=/var/lib/ollama
# Environment="HOME=/var/lib/ollama"
# Environment="OLLAMA_MODELS=/var/lib/ollama"
# Environment="HSA_OVERRIDE_GFX_VERSION=10.3.0"
# Environment="AMD_SERIALIZE_KERNEL=3"
# User=ollama
# Group=ollama
# Restart=on-failure
# RestartSec=3
# RestartPreventExitStatus=1
# Type=simple
# PrivateTmp=yes
# ProtectSystem=full
# ProtectHome=yes
#
#
# [Install]
# WantedBy=multi-user.target

**Comment by rick-github** [comment]
```
2025/01/30 21:03:27 routes.go:1187: INFO server config env="map[
  CUDA_VISIBLE_DEVICES:
  GPU_DEVICE_ORDINAL:
  HIP_VISIBLE_DEVICES:
  HSA_OVERRIDE_GFX_VERSION:
  HTTPS_PROXY:
...
  OLLAMA_MODELS:/home/.ollama/models
...
```
The variables you are setting in the service config are not being set in the server environment.  How are you starting the server?

**Comment by Guedxx** [comment]
ollama serve

**Comment by mxyng** [comment]
`ollama serve` does not and cannot use systemd configurations. Since you already have system configurations, you should use `systemctl restart ollama`. You may need sudo

**Comment by Guedxx** [comment]
THANK YOU it worked. Idk if is common sense, but it would be nice maybe to specify it in the article about it..

**Comment by rick-github** [comment]
https://github.com/ollama/ollama/blob/main/docs/linux.md#adding-ollama-as-a-startup-service-recommended
